#!/bin/sh

audio_conf=/etc/default/audio.conf
[ -e /etc/mpd.conf.sav ] && mpd_conf=/etc/mpd.conf.sav || mpd_conf=/etc/mpd.conf
[ -e /usr/local/etc/upmpdcli.conf.sav ] && upmpdcli_conf=/usr/local/etc/upmpdcli.conf.sav || upmpdcli_conf=/usr/local/etc/upmpdcli.conf

renderer_name () {

 clear
 echo -n "
 --------------------------------------------
  Change Renderer Name / 렌더러 이름 바꾸기
 --------------------------------------------


 [ $current_name ] Renderer Name / 렌더러 이름


 (m) Main / 주메뉴
 (q) Quit / 나가기

  * Input / 입력 (name|m|q) : "
 read i
 echo
 case $i in
  m) clear ; return ;;
  q) exit ;;
  *) sudo sed -i 's/^#*friendlyname.*/friendlyname = '"$i"'/' $upmpdcli_conf ;;
 esac
 return
}

until [ "$i" = "q" ] ; do

 current_name=$(grep ^#*friendlyname $upmpdcli_conf | cut -d ' ' -f3-)

 status_dop=$(grep -q '^dop' $mpd_conf && echo on || echo off)
 status_tag=$(grep -q '^metadata.*none' $mpd_conf && echo off || echo on)
 status_pcm=$(grep -A1 'plugin.*pcm' $mpd_conf | grep -q yes - && echo on || echo off)
 status_vol=$(grep -q 'mixer_type.*software' $mpd_conf && echo on || echo off)

 for i in airplay sqzlite; do
  eval status_$i="$(grep ^$i= $audio_conf | cut -d= -f2)"
 done

 clear
 echo -n "
 -----------------------------------
  Audio Configuration / 오디오 설정
 -----------------------------------

 (1) [ $([ "$status_dop"      = off ] && echo X || echo O) ] MPD DoP (DSD over PCM)
 (2) [ $([ "$status_pcm"      = off ] && echo X || echo O) ] MPD PCM Decoder
 (3) [ $([ "$status_vol"      = off ] && echo X || echo O) ] MPD Software Volume
 (4) [ $([ "$status_tag"      = off ] && echo X || echo O) ] MPD Tag Metadata

 (5) [ $([ "$status_airplay"  = off ] && echo X || echo O) ] Airplay
 (6) [ $([ "$status_sqzlite"  = off ] && echo X || echo O) ] Squeezebox

 (7) [ $current_name ] Renderer Name / 렌더러 이름 >>

 (q) Quit   / 나가기
 (r) Reboot / 재시작하여 적용

  *  Select / 선택 (1-7|q|r) : "
 read i
 echo
 case $i in
  1) if [ $status_dop = off ]; then
      sudo sed -i '/dop/s/^#*//g'                   $mpd_conf
     else
      sudo sed -i '/dop/s/^/#/g'                    $mpd_conf
     fi ;;
  2) if [ $status_pcm = off ]; then
      sudo sed -i '/plugin.*pcm/!b;n;s/".*"/"yes"/' $mpd_conf
     else
      sudo sed -i '/plugin.*pcm/!b;n;s/".*"/"no"/'  $mpd_conf
     fi ;;
  3) if [ $status_vol = off ]; then
      sudo sed -i '/mixer_type/s/".*"/"software"/'  $mpd_conf
     else
      sudo sed -i '/mixer_type/s/".*"/"none"/'      $mpd_conf
     fi ;;
  4) if [ $status_tag = off ]; then
      sudo sed -i '/metadata.*none/s/^/#/'          $mpd_conf
     else
      sudo sed -i '/metadata.*none/s/^#*//'         $mpd_conf
     fi ;;
  5) if [ $status_airplay = off ]; then
      sudo sed -i '/airplay=/s/=.*/=on/'            $audio_conf
     else
      sudo sed -i '/airplay=/s/=.*/=off/'           $audio_conf
     fi ;;
  6) if [ $status_sqzlite = off ]; then
      sudo sed -i '/sqzlite=/s/=.*/=on/'            $audio_conf
     else
      sudo sed -i '/sqzlite=/s/=.*/=off/'           $audio_conf
     fi ;;
  7) renderer_name ;;
  q) exit          ;;
  r) sudo reboot   ;;
  *) clear         ;;
 esac
done
