#!/bin/sh

renderer_name () {

 clear
 echo -n "
 --------------------------------------------
  Change Renderer Name / 렌더러 이름 바꾸기
 --------------------------------------------


 [ \e[32m"$current_name"\e[0m ] Renderer Name / 렌더러 이름


 (m) Main / 주메뉴
 (q) Quit / 나가기

  * Input / 입력 (name|m|q) : "
 read i
 echo
 case $i in
  m) clear ; return ;;
  q) exit ;;
  *) consf upmpd set "$i" ;;
 esac
 return
}

until [ "$i" = "q" ] ; do

 current_name=$(consf upmpd)

 for i in dop pcm vol sta tag; do
  eval status_$i="$(consf mpd $i)"
 done

 for i in airplay sqzlite; do
  eval status_$i="$(consf $i)"
 done

 clear
 echo -n "
 -----------------------------------
  Audio Configuration / 오디오 설정
 -----------------------------------

 (\e[33m1\e[0m) [ $([ "$status_dop"     = off ] && echo "\e[32mX\e[0m" || echo "\e[32mO\e[0m") ] MPD DoP (DSD over PCM)
 (\e[33m2\e[0m) [ $([ "$status_pcm"     = off ] && echo "\e[32mX\e[0m" || echo "\e[32mO\e[0m") ] MPD PCM Decoder
 (\e[33m3\e[0m) [ $([ "$status_vol"     = off ] && echo "\e[32mX\e[0m" || echo "\e[32mO\e[0m") ] MPD Software Volume
 (\e[33m4\e[0m) [ $([ "$status_sta"     = off ] && echo "\e[32mX\e[0m" || echo "\e[32mO\e[0m") ] MPD State File
 (\e[33m5\e[0m) [ $([ "$status_tag"     = off ] && echo "\e[32mX\e[0m" || echo "\e[32mO\e[0m") ] MPD Tag Metadata

 (\e[33m6\e[0m) [ $([ "$status_airplay" = off ] && echo "\e[32mX\e[0m" || echo "\e[32mO\e[0m") ] Airplay
 (\e[33m7\e[0m) [ $([ "$status_sqzlite" = off ] && echo "\e[32mX\e[0m" || echo "\e[32mO\e[0m") ] Squeezebox

 (\e[33mn\e[0m) [ \e[32m"$current_name"\e[0m ] Renderer Name / 렌더러 이름 >>

 (\e[33mq\e[0m) Quit   / 나가기
 (\e[33mr\e[0m) Reboot / 재시작하여 적용

  *  Select / 선택 (\e[33m1-7\e[0m|\e[33mn\e[0m|\e[33mq\e[0m|\e[33mr\e[0m) : "
 read i
 echo
 case $i in
  1) [ $status_dop     = off ] && consf mpd dop on || consf mpd dop off ;;
  2) [ $status_pcm     = off ] && consf mpd pcm on || consf mpd pcm off ;;
  3) [ $status_vol     = off ] && consf mpd vol on || consf mpd vol off ;;
  4) [ $status_sta     = off ] && consf mpd sta on || consf mpd sta off ;;
  5) [ $status_tag     = off ] && consf mpd tag on || consf mpd tag off ;;
  6) [ $status_airplay = off ] && consf airplay on || consf airplay off ;;
  7) [ $status_sqzlite = off ] && consf sqzlite on || consf sqzlite off ;;
  n) renderer_name ;;
  q) exit          ;;
  r) sudo reboot   ;;
  *) clear         ;;
 esac
done
