#!/bin/sh
#complete -W 'hdmi usb int def nodef' ./audio \~/audio

usage () {
 echo "Usage: $(basename "$0") [ls|hdmi|usb|int] # HDMI/USB/Internal"
 echo "   or: $(basename "$0") [def|nodef]       # PCM Default On/Off"
 echo "Manipulate ALSA output"
}

alsa_orig="/usr/share/alsa/alsa.conf.min"
alsa_conf="/dev/shm/alsa.conf"
card=$(grep -m1 -o 'card..' $alsa_conf | cut -b6)

case $1 in
 ls)
  #nr=0
  #
  #[ -e /proc/asound/cards ] && id=$(grep "^ $nr" /proc/asound/cards | sed 's/.* - //')
  #[ -e /proc/asound/card$nr/pcm0p/info ] && card=$(grep "^id: " /proc/asound/card$nr/pcm0p/info | cut -d' ' -f2-)
  #[ -z "$id" ] && card0="N/A" || card0="$id ($card)"
  #
  echo "+ ALSA Sound Card(s)"
  for nr in $(seq 0 9); do
   [ -e /proc/asound/cards ] && id=$(grep "^ $nr" /proc/asound/cards | sed 's/.* - //')
   for i in $(seq 0 9); do
    card=""
    [ -e /proc/asound/card$nr/pcm${i}p/info ] && card=$(grep "^id: " /proc/asound/card$nr/pcm${i}p/info | cut -d' ' -f2-)
    ! [ -z "$id" ] && ! [ -z "$card" ] && echo "$nr.$i: $id ($card)"
   done
  done ;;
 hdmi|usb|int)
  if [ "$1" = hdmi ]; then
   card=0; dev=3; IEC958=on;  irq=snd
  elif [ "$1" = usb ]; then
   card=1; dev=0; IEC958=off; irq=xhci
  else
   card=0; dev=0; IEC958=off; irq=snd
  fi

  if [ "$1" = hdmi ] || [ "$1" = usb ]; then
   sudo sed -i '1s/card../card '"$card"'/'    $alsa_conf
   sudo sed -i '1s/device../device '"$dev"'/'  $alsa_conf
  else
   sudo cp $alsa_orig $alsa_conf
  fi

  if grep -q ' \?ctl.default' $alsa_conf; then
   sudo sed -i '$ s/ \?ctl.*/\nctl.default{type hw card '"$card"'}/' $alsa_conf
  else
   sudo sed -i '$s/$/ctl.default{type hw card '"$card"'}/' $alsa_conf
  fi

  #amixer -q set IEC958 $IEC958
  #echo "* IEC985 is $(amixer get IEC958 | tail -1 | cut -d '[' -f2 | cut -d ']' -f1)"

  sudo sed -i '/^ctl.default/d; s/ctl.default.*//' $alsa_conf

#  for i in $(awk '/'"$irq"'/{print +$1}' /proc/interrupts); do
#   proc="/proc/irq/$i/smp_affinity"
#   sudo sh -c "echo $(echo "2^$(($(nproc --all)-1))" | bc) > $proc"
#   echo "* $proc = $(cat $proc) ($(awk '$1 ~ /'"$i"'/{print $NF}' /proc/interrupts))"
#  done
  ;;
 def)
  if ! grep -q 'pcm.default' $alsa_conf; then
#  sudo sed -i 's/pcm.default.*/pcm.default pcm.'"$card"'/' $alsa_conf
# else
#  sudo sed -i '1ipcm{default pcm.'"$card"'}' $alsa_conf
   sudo sed -i '1ipcm{default pcm.hw}' $alsa_conf
  fi ;;
 nodef)
   sudo cp $alsa_orig $alsa_conf ;;
 *) usage ;;
esac

set -x
cat $alsa_conf
cat $alsa_orig
