#!/bin/sh

url="http://saycast.sayclub.com/station/home/index/hifi"
host="127.0.0.1"

echo "\
* ClassicHiFi
  http://hifi.saycast.com (MP3 320kbps@48kHz)
  http://hificlass.inlive.co.kr (AAC 325kbps@96kHz)"

now=$(curl -s $url | grep -m1 "<div id=\"moreMusic\">" | cut -d\> -f2- | cut -d\< -f1)
[ -n "$now" ] && echo "$now"

if [ "$1" = play ]; then
 url=$(curl -s http://hificlass.inlive.co.kr/listen.pls | grep -m1 -i file | cut -d= -f2)
 [ -z "$url" ] || ! ffprobe -timeout 5 -listen_timeout 5 -v quiet "$url" && echo "${0##*/} stream ("$url") is not available!" && exit
 mpc -h $host add "$url" && mpc -h $host play $(mpc -h $host playlist | wc -l)
fi
