#!/bin/sh

ddif=$((($(date +%s)-$(date -d'2011-04-12' +%s))/(24*3600)))

case $(date +%_H) in
 16) n=1 ;;
 17) n=2 ;;
 18) n=3 ;;
 19) n=4 ;;
 20) n=5 ;;
 21) n=6 ;;
 22) n=7 ;;
 23) n=8 ;;
 *)  n=0 ;;
esac

printf "* Emergency code is \e[32m${ddif}4${n}33\e[0m\n"
