#!/bin/sh

ptzzz1 () {
 echo -n "."
 sleep 1
}

pgr_mpv=$(pgrep -nx gnome-mpv)

[ "$pgr_mpv" = "" ] && echo "Error: gnome-mpv is not running" && exit

times=0
until pstree -p $pgr_mpv | grep -q mpv/ao; do
 ptzzz1
 times=$(($times+1))
 [ "$times" -ge 10 ] && printf "\nNo audio output pid found!\n" && exit
done
sleep 1

m_task=$(($(nproc --all)-1)); h_task=0; s_task=0
[ "$m_task" -ge 3 ] && h_task=$((m_task-1)) && s_task=$((m_task-2))

echo
taskset -pc $s_task $pgr_mpv

echo "$(pstree -np $pgr_mpv)" | while read line; do
    proc=$(echo "$line" | cut -d "{" -f2 | cut -d "}" -f1 | cut -d ":" -f1)
 proc_nr=$(echo "$line" | cut -d "}" -f2 | cut -d "(" -f2 | cut -d ")" -f1)
 case $proc in
  dconf*|gmain|gdbus|gnome*)
   taskset -pc $h_task $proc_nr ;;
  mpv/demux|mpv/worker)
   taskset -pc $s_task $proc_nr ;;
  mpv/vo)
   taskset -pc $h_task $proc_nr ;;
  mpv/ao)
   taskset -pc $m_task $proc_nr ;;
  *)
   taskset -pc $h_task $proc_nr ;;
 esac
done
