#!/bin/sh

ptzzz1 () {
 echo -n "."
 sleep 1
}

pgr_mpv=$(pgrep -nx celluloid)

[ "$pgr_mpv" = "" ] && echo "Error: Celluloid is not running" && exit

times=0
until pstree -npt $pgr_mpv | grep -q mpv/ao; do
#ptzzz1
 times=$(($times+1))
 [ "$times" -ge 10 ] && printf "\nNo audio output pid found!\n" && exit
done
sleep 1

procnr=$(nproc --all)
if   [ "$procnr" -eq 2 ]; then
 m_task=0; s_task=1; h_task=1; o_task=1
elif [ "$procnr" -eq 4 ]; then
 m_task=2; s_task=0; h_task=3; o_task=1,3
elif [ "$procnr" -ge 8 ]; then
 m_task=6; s_task=4; h_task=2; o_task=1,3,5,7
else
 m_task=0; s_task=0; h_task=0; o_task=0
fi

#echo
#taskset -pc $s_task,$h_task,$o_task $pgr_mpv

echo "$(pstree -npt $pgr_mpv)" | while read line; do
    proc=$(echo "$line" | cut -d "{" -f2 | cut -d "}" -f1 | cut -d ":" -f1)
 proc_nr=$(echo "$line" | cut -d "}" -f2 | cut -d "(" -f2 | cut -d ")" -f1)
 case $proc in
  dconf*|gmain|gdbus|celluloid*)
   taskset -pc $s_task,$h_task,$o_task	$proc_nr ;;
#  mpv/demux|mpv/worker)
#   taskset -pc $s_task,$h_task,$o_task	$proc_nr ;;
#  mpv/vo)
#   taskset -pc $s_task,$h_task,$o_task	$proc_nr ;;
  mpv/ao)
   taskset -pc $m_task			$proc_nr ;;
#  *)
#   taskset -pc $s_task,$h_task,$o_task	$proc_nr ;;
 esac
done
