#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") on/off"
 echo "Run GMediaRender as UPnP Media Renderer"
}

case $1 in
 on)  gmediarender -d --gstout-audiosink=alsasink --gstout-audiodevice=pcm.0 ;;
 off) pkill gmediarender ;;
 *)   usage ;;
esac
