#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") [blank|dark|bright|0.96|mute|unmute|toggle]"
}

[ -z "$1" ] && usage && exit

monitor=$(xrandr -q | sed -n 2p | cut -d " " -f1)
vol=Master

case $1 in
 blank)	  xset dpms force off			     ;;
 dark)	  xrandr --output $monitor --brightness 0.7  ;;
 bright)  xrandr --output $monitor --brightness 1    ;;
 0.96)	  xrandr --output $monitor --brightness 0.96 ;;
 mute)	  vol mute   ;;
 unmute)  vol unmute ;;
 toggle)  vol toggle ;;
 *)	  usage
esac
