#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") [klive|kpodcast]"
 echo "Install Kodi Addo-ons for LibreELEC"
}

[ -z "$1" ] && usage && exit

 dest="/home/parkmino/Downloads/kodi/"
#dest="/storage/backup/"

klive () {
 url="https://github.com/soju6jan/KLive/archive/master.zip"

 [ -f ./master.zip ] && rm ./master.zip
 [ -d ./KLive-master ] && rm -rf ./KLive-master

 wget "$url"
 unzip master.zip KLive-master/plugin.video.klive/*
 unzip master.zip KLive-master/lib/*
 mv ./KLive-master/lib ./KLive-master/plugin.video.klive/resources

 cd ./KLive-master
 zip -r plugin.video.klive.zip plugin.video.klive/
 mv ./plugin.video.klive.zip "$dest"
 cd ..

 rm -rf ./master.zip ./KLive-master
}

kpodcast () {
 url="https://github.com/soju6jan/plugin.audio.kpodcast/archive/master.zip"

 [ -f ./master.zip ] && rm ./master.zip
 [ -d ./plugin.audio.kpodcast-master ] && rm -rf ./plugin.audio.kpodcast-master

 mkdir -p "$dest" "$dest"/

 wget "$url"
 unzip master.zip

 cd ./plugin.audio.kpodcast-master
 zip -r plugin.audio.kpodcast.zip plugin.audio.kpodcast/
 mv ./plugin.audio.kpodcast.zip "$dest"
 cd ..

 rm -rf ./master.zip ./plugin.audio.kpodcast-master
}

if   [ "$1" = klive ]; then
 klive
elif [ "$1" = kpodcast ]; then
 kpodcast
else
 usage
fi
