#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") [klive|kpodcast]"
 echo "Install Kodi Addo-ons for LibreELEC"
}

[ -z "$1" ] && usage && exit

klive () {
 url="https://github.com/soju6jan/KLive/archive/master.zip"
 dest="/home/parkmino/.kodi/addons/plugin.video.klive"

 [ -f ./master.zip ] && rm ./master.zip
 [ -d ./KLive-master ] && rm -rf ./KLive-master
 [ -d "$dest" ] && rm -rf "$dest"

 mkdir -p "$dest" "$dest"/

 wget "$url"
 unzip master.zip KLive-master/plugin.video.klive/*
 unzip master.zip KLive-master/lib/*
 mv ./KLive-master/lib ./KLive-master/plugin.video.klive/resources

 mv ./KLive-master/plugin.video.klive/* "$dest"

 rm -rf ./master.zip ./KLive-master
}

kpodcast () {
 url="https://github.com/soju6jan/plugin.audio.kpodcast/archive/master.zip"
 dest="/home/parkmino/.kodi/addons/plugin.audio.kpodcast"

 [ -f ./master.zip ] && rm ./master.zip
 [ -d ./plugin.audio.kpodcast-master ] && rm -rf ./plugin.audio.kpodcast-master
 [ -d "$dest" ] && rm -rf "$dest"

 mkdir -p "$dest" "$dest"/

 wget "$url"
 unzip master.zip

 mv ./plugin.audio.kpodcast-master/plugin.audio.kpodcast/* "$dest"

 rm -rf ./master.zip ./plugin.audio.kpodcast-master
}

if   [ "$1" = klive ]; then
 klive
elif [ "$1" = kpodcast ]; then
 kpodcast
else
 usage
fi
