#!/bin/sh

  my_ip=$(hostname -I | tr -d ' ')
ip_root=$(hostname -I | cut -d'.' -f1-3)
   port=6600

[ "$my_ip" = "" ] || [ "$my_ip" = "127.0.0.1" ] && echo "Network is not available and exit." && exit

for i in nmap fping nc; do # nmblookup
 [ -z "$(which $i)" ] && echo "$i is not installed and exit." && exit
done

sudo true

#sudo nmap -p $port --open ${ip_root}.1-254 && printf \\n

echo "$(fping -a -q -r0 -g ${ip_root}.1 ${ip_root}.254 | sort -V)" | while read ip; do
 printf "\33[2K\r💻️ $ip "
 if   [ "${#ip}" -eq 11 ]; then
  printf "  "
 elif [ "${#ip}" -eq 12 ]; then
  printf " "
 fi
 #name=$(nmblookup -A $ip | sed -n 2p | sed 's/^[ \t]//; s/[ \t].*//')
 #[ "$name" = "No" ] && name=""
 if [ "$ip" = "$my_ip" ]; then
  ping=$(echo ping | nc -w1 localhost $port | head -1 | sed 's/^OK //')
  mac=$(ifconfig | grep -m1 HWaddr | sed 's/.*HWaddr //; s/ .*//')
  name="localhost ($(cat /proc/sys/kernel/hostname))"
 else
  ping=$(echo ping | nc -w1 $ip $port | head -1 | sed 's/^OK //')
 #mac=$(arp -a $ip | cut -d' ' -f4)
  string=$(sudo nmap -sn $ip | grep -m1 ^MAC)
  mac=$(echo $string | cut -d' ' -f3)
  name=$(echo $string | cut -d'(' -f2 | cut -d')' -f1)
 fi
 [ -z "$ping" ] && printf "[$mac]            $name\n" || printf "[$mac] $ping $name\n"
done

printf "\33[2K\r"