#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") ch|ck|ls" 
}

[ "$#" -lt 1 ] && usage && exit

folder="/home/parkmino/Videos/iptv"

if [ "$1" = ls ]; then
 ls -1 Videos/iptv/channels_* | cut -d_ -f2 | cut -d. -f-4 > $folder/tvheadend.txt
elif [ "$1" = ck ]; then
 rm -f $folder/available/*
 echo "$(ls -1 $folder/channels*.m3u)" | while read line; do
  file="$(echo $line | cut -d/ -f6-)"
  printf "$(echo "$file" | cut -d_ -f2- | cut -d. -f1-4)"
  if ffprobe -v quiet $(cat "$line" | grep -m1 http://); then
   printf "\tOK\n"
   cp $line $folder/available/
  else
   printf "\n"
  fi
 done
else
 for i in $(seq 1 $#); do
  grep -i -A1 "$(eval echo "\$$i")" $folder/available/channels_* | grep -v -e -- | cut -d, -f2- | cut -d- -f2 | cut -d? -f1
 done
fi
