#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") [ip|ls|ck|queries]"
}

[ "$#" -lt 1 ] && usage && exit

url="https://www.extinf.com/category/korean/"
curl_opt="-s -m9 --connect-timeout 9"
folder="/home/parkmino/Videos/iptv"

if [ "$1" = ip ]; then
 printf "$url"
 ! curl $curl_opt "${url}" >/dev/null && printf " is not available!\n" && exit
 echo
 for i in $(curl $curl_opt "${url}" | grep -o http://[0-9]*.[0-9]*.[0-9]*.[0-9]*:9981/ | uniq); do
  curl $curl_opt "${i}playlist" >/dev/null && echo "${i}playlist"
 done
 for i in $(seq 2 30); do
  curl $curl_opt "${url}page/$i/" >/dev/null || break
  for j in $(curl $curl_opt "${url}page/$i/" | grep -o http://[0-9]*.[0-9]*.[0-9]*.[0-9]*:9981/ | uniq); do
   curl $curl_opt "${j}playlist" >/dev/null && printf "${j}playlist\t($i)\n"
  done
 done
elif [ "$1" = ls ]; then
 ls -1 $folder/channels_* | cut -d_ -f2 | cut -d. -f-4 > $folder/tvheadend.txt
elif [ "$1" = ck ]; then
 rm -f $folder/available/*
 echo "$(cat $folder/tvheadend.txt)" | while read line; do
  printf "$line\t"
  file=$folder/channels_$line.m3u
  curl -s -o /dev/null --connect-timeout 2 -m 3 http://$line:9981/playlist && printf "playlist "
  if ffprobe -v quiet $(grep -m1 ^http:// $file); then
   printf "stream\n"
   ln -sf $file $folder/available/
  else
   printf "\n"
  fi
 done
else
 for i in $(seq 1 $#); do
 #grep -i -A1 "$(eval echo "\$$i")" $folder/available/channels_* | grep -v -e -- | cut -d, -f2- | cut -d- -f2 | cut -d? -f1
  grep -i -A1 "$(eval echo "\$$i")" $folder/available/channels_* | grep -v -e -- -e EXTINF | cut -d- -f2 | cut -d? -f1
 done
fi
