#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") 1tv|2tv|w(orld)|24|d(rama)|j(oy)|l(ife)|k(ids)"
 echo "   or: $(basename "$0") 1fm|2fm|1r|2r|3r|scr|rki"
}

[ -z "$1" ] && usage && exit

m3u_dir="/home/parkmino/Videos"
fd=16

case $1 in
 1tv) ch=11  ;;
 2tv) ch=12  ;;
# w)  url=http://live.kbskme.gscdn.com/www_kbs_worldtv/_definst_/kbs_worldtv_5.stream/playlist.m3u8 ;;
 24)  ch=81  ;;
 d)   ch=N91 ;;
 j)   ch=N92 ;;
 W)   ch=N94 ;;
 l)   ch=N93 ;;
 k)   ch=N96 ;;
 1fm) ch=24  ;;
 2fm) ch=25  ;;
 1r)  ch=21  ;;
 2r)  ch=22  ;;
 3r)  ch=23  ;;
 scr) ch=I26 ;;
 rki) ch=I92 ;;
 *)   usage  ; exit ;;
esac

#api="$(curl -s http://cfpwwwapi.kbs.co.kr/api/v1/landing/live/$ch | cut -d\" -f$fd)"
#url="$(curl -s "https://onair.kbs.co.kr/index.html?sname=onair&stype=live&ch_code=$ch" | grep service_url | tail -1 | cut -d\" -f$fd | cut -d\\ -f1)"
[ -z "$url" ] && url="$(curl -s "https://onair.kbs.co.kr/index.html?sname=onair&stype=live&ch_code=$ch" | grep -o https://.*Key-Pair-Id=[0-9A-Z]* | cut -d\\ -f1)"
#url="$(echo "$api" | grep -o '.*/' | sed 's/_[1-4].stream/_5.stream/')$(curl -s "$api" | tail -1)"

echo "$url"

printf "#EXTM3U\n#EXTINF:-1,KBS $1\n$url\n" > $m3u_dir/kbs.m3u

#case $ch in
# 1[1,2,4]|81|N9[1-6]) mpv "$url" ;;
# *) mpc add "$url" && mpc play $(mpc playlist | wc -l) ;;
#esac
