#!/bin/sh

 host=127.0.0.1
#host=192.168.0.3
#host=192.168.0.9
#host=192.168.0.10
#host=192.168.0.13

api=$(curl -s http://pckong.kbs.co.kr/auth/api_auth.php?url=aHR0cDovL3Bja29uZy5rYnMuY28ua3IvbWtvbmcvYXBpLnBocD9hcGlfbmFtZT1saXZlX3N0cmVhbSZkZXZpY2VfdHlwZT1pcGhvbmUmYmV0YT0wJmlzX2JvcmE9TiZjaGFubmVsX2NvZGU9MjQmcmVxdHM9MjAxODA5MDUxMiZhdXRoY29kZT1FMzdGRjg2Rjc0NzAwRkVCRDc5NzE1NkI2QTQyRTMyMDZBRDQ0QThEODdGMjY2MTk3RjQ4RThGNzdFQzQwRUM1 | cut -d\" -f20)
url=$(echo "$api" | rev | cut -d\/ -f2- | rev)/$(curl -s "$api" | tail -1)

echo $url ; exit

mpc -h $host add "$url" && mpc -h $host play $(mpc -h $host playlist | wc -l)
#gst123 -qx -a alsa=pcm.0 $url
