#!/bin/sh
#complete -W '1fm 2fm 1r 2r 3r scr rki mbcm mbc4u mbcfm sbsp sbsl cbs tbs tbse gugak stop' kr2mpd ./kr2mpd \~/kr2mpd

 host="127.0.0.1"
#host="192.168.0.3"

usage () {
 echo "Usage: $(basename "$0") 1fm,2fm,1r,2r,3r,scr,rki(KBS라디오)"
 echo "   or: $(basename "$0") mbcm(MBC Channel M),mbc4u(MBC FM4U),mbcfm(MBC FM)"
 echo "   or: $(basename "$0") sbsp(SBS파워FM),sbsl(SBS러브FM)"
 echo "   or: $(basename "$0") cbs(CBS음악FM),tbs(tbsFM),tbse(tbseFM),gugak(국악방송)"
 echo "   or: $(basename "$0") http://...(Stream URL)"
 echo "   or: $(basename "$0") stop(정지)"
 echo "Play Korean Radio with MPD"
}

pls () {
 url=$(echo "$1" | grep -o '.*/')$(curl -s "$1" | tail -1)
}

kbsr () {
#url=$(curl -s "http://kong.kbs.co.kr/live_player/channelMini.php?id=kbsid&channel=$1" | tail -1)
#pls $(curl -s "http://cfpwwwapi.kbs.co.kr/api/v1/landing/live/$1" | cut -d\" -f16)
#if   [ "$1" = 21 ]; then
# pls $(curl -s http://serpent0.duckdns.org:8088/kbs1radio.pls | head -2 | tail -1 | cut -d\= -f2-)
#elif [ "$1" = 22 ]; then
# pls $(curl -s http://serpent0.duckdns.org:8088/kbs2radio.pls | head -2 | tail -1 | cut -d\= -f2-)
#elif [ "$1" = 24 ]; then
# pls $(curl -s http://serpent0.duckdns.org:8088/kbs1fm.pls | head -2 | tail -1 | cut -d\= -f2-)
#else
  url=$(curl -s "http://onair.kbs.co.kr/index.html?sname=onair&stype=live&ch_code=$1" | grep service_url | tail -1 | cut -d\" -f16 | cut -d\\ -f1)
#fi
}

mbcr () {
#pls $(curl -s "http://miniplay.imbc.com/WebLiveURL.ashx?channel=$1&agent=android&protocol=M3U8" | sed -n '3p' | cut -d\" -f2)
#url=$(curl -s http://serpent0.duckdns.org:8088/mbc$1.pls | head -2 | tail -1 | cut -d\= -f2-)
 pls $(curl -s "http://miniplay.imbc.com/AACLiveURL.ashx?channel=$1&agent=android&protocol=M3U8")
 [ ${#url} -lt 80 ] && url=
}

sbsr () {
#api=$(curl -s "http://apis.sbs.co.kr/play-api/1.0/onair/channel/S$1?v_type=2&platform=pcweb&protocol=hls" | grep -o 'mediaurl.*' | cut -d\" -f3)
#url=$(curl -s "$api" | tail -1)
 api=$(curl -s "http://api.sbs.co.kr/vod/_v1/Onair_Media_Auth_Security.jsp?channelPath=$1&streamName=$2.stream&playerType=mobile")
 url=$(curl -s $(sbs_dec.py "$api") | tail -1)
}

case $1 in
 1fm)   #kbsr 1
        kbsr 24
	;;
 2fm)   #kbsr 2
	kbsr 25
	;;
 1r)    #kbsr 3
	kbsr 21
	;;
 2r)    #kbsr 4
	kbsr 22
	;;
 3r)    #kbsr 5
	kbsr 23
	;;
 scr)   #kbsr 7
	kbsr I26
	;;
 rki)   #kbsr 8
	kbsr I92
	;;
 mbcm)  mbcr chm ;;
 mbc4u) mbcr mfm ;;
 mbcfm) mbcr sfm ;;
 sbsp)  #sbsr 07
	sbsr powerpc powerfm
	;;
 sbsl)  #sbsr 08
	sbsr lovepc  lovefm
	;;
 cbs)   pls "http://aac.cbs.co.kr/cbs939/cbs939.stream/playlist.m3u8" ;;
 tbs)   pls "http://tbs.hscdn.com/tbsradio/fm/playlist.m3u8" ;;
 tbse)  pls "http://tbs.hscdn.com/tbsradio/efm/playlist.m3u8" ;;
 gugak) pls "http://mgugaklive.nowcdn.co.kr/gugakradio/gugakradio.stream/playlist.m3u8" ;;
 stop)  mpc stop ; mpc del $(mpc playlist | wc -l) ; exit ;;
 *)     if [ -n "$1" ] && [ -z "${1##http*}" ]; then
         url="$1"
        else
         usage ; exit
        fi ;;
esac

[ -z "$url" ] && echo "$1 stream is not available!" && exit
mpc -h $host add "$url" && mpc -h $host play $(mpc -h $host playlist | wc -l)
