#!/bin/sh

#ffmpeg -i video.mkv -i audio.m4a -map 0:v -map 1:a -shortest -c copy output.mkv
#ffmpeg -i video.mkv -itsoffset 0.5 -i audio.m4a -map 0:v -map 1:a -shortest -c copy output.mkv
#ffmpeg -i video.mkv -vf scale=1920x1080:flags=lanczos video_1920x1080.mkv

usage () {
 echo "Usage: $(basename "$0") video_file audio_file"
}

[ ! $# -eq 2 ] && usage && exit

ffmpeg -i "$1" -i "$2" -map 0:v -map 1:a -shortest -c copy output.mkv
