#!/bin/sh

#ffmpeg -i video.mkv -i audio.m4a -c copy -map 0:v:0 -map 1:a:0 -shortest output.mkv

usage () {
 echo "Usage: $(basename "$0") video_file audio_file"
}

[ ! $# -eq 2 ] && usage && exit

ffmpeg -i "$1" -i "$2" -c copy -map 0:v:0 -map 1:a:0 -shortest /home/parkmino/Downloads/output.mkv
