#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") [umount]"
}

if [ "$1" = "umount" ]; then
 sudo umount /mnt/usb
 exit
fi

blkid | tac | while read line; do
  uuid=$(echo $line | grep -io uuid.* | cut -d\" -f2)
 drive=$(echo $line | cut -d: -f1)
 if [ -n "$uuid" ] && ! grep -q $uuid /etc/fstab && ! mount | grep -q "$drive"; then
  type=$(echo $line | grep -o TYPE.* | cut -d\" -f2)
  case $type in
   vfat) opt="ro,codepage=949,iocharset=utf8" ;;
   ntfs) opt="ro,umask=022" ;;
   *)    opt="ro" ;;
  esac
  sudo mount -o "$opt" "$drive" /mnt/usb
  break
 fi
done
