#!/bin/sh

times=0
until [ "$(pgrep -x mpd)" -gt 0 ] 2>/dev/null && $(pstree -npt "$(pgrep -x mpd)" 2>/dev/null | grep -q output); do
 sleep 1
 times=$(($times+1))
 [ "$times" -ge 10 ] && printf "\nNo MPD audio output and exit!\n" && exit
done
sleep 1

m_task=$(($(nproc --all)-1))
[ "$m_task" -ge 3 ] && s_task=$((m_task-2)) || s_task=0

pgr_mpd=$(pgrep -nx mpd)

taskset -pc $m_task $pgr_mpd

echo "$(pstree -npt $pgr_mpd)" | while read line ; do
 proc=$(echo "$line" | cut -d "{" -f2 | cut -d "}" -f1 | cut -d ":" -f1)
 proc_nr=$(echo "$line" | cut -d "}" -f2 | cut -d "(" -f2 | cut -d ")" -f1)
 case $proc in
  mpd)		 taskset -cp $s_task $proc_nr ;;
  io)		 taskset -cp $s_task $proc_nr ;;
  player)	 taskset -cp $s_task $proc_nr ;;
  decoder)	 taskset -cp $s_task $proc_nr ;;
  output)	 taskset -cp $m_task $proc_nr
		#sudo renice -1 -p   $proc_nr
		#ionice -c 2 -n 7 -p $proc_nr
		 chrt -opv 0	     $proc_nr ;;
 esac
done
