#!/bin/sh

pgr_mpv=$(pgrep -nx mpv)

[ -z "$pgr_mpv" ] && echo "Error: mpv is not running" && exit

times=0
until pstree -pt $pgr_mpv | grep -q mpv/ao; do
 #ptzzz1
 sleep 1
 times=$(($times+1))
 [ "$times" -ge 15 ] && printf "\nNo MPV audio output and exit!\n" && exit
done
sleep 1

m_task=$(($(nproc --all)-1)); h_task=0; s_task=0
[ "$m_task" -ge 3 ] && h_task=$((m_task-1)) && s_task=$((m_task-2))

taskset -pc $s_task $pgr_mpv

echo "$(pstree -npt $pgr_mpv)" | while read line; do
    proc=$(echo "$line" | cut -d "{" -f2 | cut -d "}" -f1)
 proc_nr=$(echo "$line" | cut -d "}" -f2 | cut -d "(" -f2 | cut -d ")" -f1)
 case $proc in
  mpv/demux)
   taskset -pc $s_task $proc_nr ;;
  mpv/vo|mpv/lua*)
   taskset -pc $h_task $proc_nr ;;
  mpv/worker)
   taskset -pc $m_task $proc_nr ;;
  mpv/ao)
   taskset -pc $m_task $proc_nr ;;
  *)
   taskset -pc $s_task $proc_nr ;;
 esac
done
