#!/bin/sh

pgr_mpv=$(pgrep -nx mpv)

[ -z "$pgr_mpv" ] && echo "Error: mpv is not running" && exit

times=0
until pstree -pt $pgr_mpv | grep -q mpv/ao; do
 #ptzzz1
 sleep 1
 times=$(($times+1))
 [ "$times" -ge 15 ] && printf "\nNo MPV audio output and exit!\n" && exit
done
sleep 1

procnr=$(nproc --all)

if   [ "$procnr" -eq 4 ]; then
 m_task=2; s_task=0; h_task=3; o_task=1,3
else
 m_task=0; s_task=0; h_task=0; o_task=0
fi

#taskset -pc $s_task,$o_task $pgr_mpv

echo "$(pstree -npt $pgr_mpv)" | while read line; do
    proc=$(echo "$line" | cut -d "{" -f2 | cut -d "}" -f1)
 proc_nr=$(echo "$line" | cut -d "}" -f2 | cut -d "(" -f2 | cut -d ")" -f1)
 case $proc in
  mpv/lua*|mpv/vo)
   taskset -pc $s_task,$h_task,$o_task	$proc_nr ;;
  mpv:disk*)
   taskset -pc $s_task,$h_task,$o_task	$proc_nr ;;
  mpv/worker)
   taskset -pc $s_task,$h_task,$o_task	$proc_nr ;;
  mpv/demux)
   taskset -pc 0-"$procnr"		$proc_nr ;;
  mpv/ao)
   taskset -pc $m_task			$proc_nr ;;
# *)
#  taskset -pc $s_task,$h_task,$o_task	$proc_nr ;;
 esac
done
