#!/bin/sh

ptzzz1 () {
 echo -n "."
 sleep 1
}

#ptzzz1

pgr_mpv=$(pgrep -nx mpv)

[ "$pgr_mpv" = "" ] && echo "Error: mpv is not running" && exit

times=0
until pstree -pt $pgr_mpv | grep -q mpv/ao; do
 #ptzzz1
 sleep 1
 times=$(($times+1))
 [ "$times" -ge 15 ] && printf "\nNo MPV audio output and exit!\n" && exit
done
sleep 1

echo
taskset -pc 3 $pgr_mpv

echo "$(pstree -npt $pgr_mpv)" | while read line; do
    proc=$(echo "$line" | cut -d "{" -f2 | cut -d "}" -f1 | cut -d ":" -f1)
 proc_nr=$(echo "$line" | cut -d "}" -f2 | cut -d "(" -f2 | cut -d ")" -f1)
 case $proc in
  mpv/terminal|mpv/lua*|mpv/cache|mpv/demix|pool)
   taskset -pc 1   $proc_nr ;;
  mpv/vo|mpv)
   taskset -pc 0,2 $proc_nr ;;
  mpv/ao)
   taskset -pc 3   $proc_nr ;;
  *)
   taskset -pc 1   $proc_nr ;;
 esac
done
