#!/bin/sh
#complete -W 'jtbc j tbs t yonhap h ytn y' ./mpvrun \~/mpvrun

usage () {
 echo "Usage: $(basename "$0") [file|url]"
 echo "   or: $(basename "$0") [jtbc(j)|kbs_news(k)|tbs(t)|yonhap(h)|ytn(y)|ytn_life(yl)|ytn_science(ys)]"
}

[ -z "$1" ] && usage && exit

             jtbc="https://youtu.be/q9u_z3ppyGU"
         kbs_news="https://youtu.be/kHfz5vER9jQ"
              tbs="https://youtu.be/CqERZQYOEPY"
           yonhap="https://youtu.be/5Kk5La-f7oY"
              ytn="https://youtu.be/aR8Fe1lTKHo"
	 ytn_life="https://youtu.be/g-Fhjcatieo"
      ytn_science="https://youtu.be/kRARhPoIfd0"
                j=$jtbc
                k=$kbs_news
                t=$tbs
                h=$yonhap
                y=$ytn
               yl=$ytn_life
	       ys=$ytn_science

if [ "$1" = jtbc ] || [ "$1" = j ] ; then
 echo "
▷  07:30 아침&
▷  14:30 뉴스 현장
▷  15:50 사건 반장
▷  17:10 정치부회의
▷  19:55 JTBC 뉴스룸

▶  공식 홈페이지 http://news.jtbc.co.kr
▶  공식 페이스북 https://www.facebook.com/jtbcnews
▶  공식 트위터 https://twitter.com/JTBC_news

방송사 : JTBC (http://www.jtbc.co.kr)
카테고리	뉴스/정치
라이선스	표준 YouTube 라이선스
"
 min=$(date +%R | awk -F: '{ print ($1 * 60) + $2 }')
 [ $min -lt  860 ] || [ $min -gt 1290 ] && printf "JTBC News might not be on air now!\n"
fi

case $1 in
 jtbc|j|tbs|t|yonhap|h|ytn|y)
  url=$(eval echo \"\$"$1"\")
  youtube-dl -qs "$url" || exit ;;
 jtbclive|jl)
  url=$(curl -s https://www.youtube.com/results?search_query=live+jtbc | grep data-context-item-id | sed 's/.*data-context-item-id="/https:\/\/youtu.be\//' | cut -d\" -f1 | head -1)
  youtube-dl -qs "$url" || exit ;;
 *)
  url="$1"
  if [ -z "${url##*http*youtu*be*}" ] ; then
   youtube-dl -qs "$url" || exit
  fi ;;
esac

pkill -x mpv # ps ax | grep -qsw [m]pv\ .* && pkill -x mpv
. /home/parkmino/mpv-bg &
mpv --no-terminal --ytdl-format='bestvideo[width<=1920][height<=1080]+bestaudio/best[width<=1920][height<=1080]' "$url" >/dev/null # 2>/dev/null # >/dev/null 2>&1
