#!/bin/sh

usage () {
 echo "Usage: $(basename $0) [up|down|on|off|scan|list|quit|stop|view]"
 echo "   or: $(basename $0) [usb] or [lan(wired)|home|mr|ss] or [bk|puppy|OpenESSID]"
 echo "Manage Network for personal use"
}

net_inf="/etc/network/interfaces"

if [ -z "$1" ]; then
 usage
 echo
 for i in bk home lan mr ss
  do
   if cmp -s $net_inf ${net_inf}.d/$i; then
    echo "#${net_inf}.d/$i"
   fi
  done
 echo "#$net_inf"
 grep -v '^ *#' $net_inf
 exit
fi

wlan=$(ifconfig -a | grep -o   '^wl\w*')
 lan=$(ifconfig -a | grep -o   '^enp.s.\w*')

if     ifconfig -a | grep -oqs '^usb\w*'; then
 usb=$(ifconfig -a | grep -o   '^usb\w*')
elif   ifconfig -a | grep -oqs '^enp.s..u.\w*'; then
 usb=$(ifconfig -a | grep -o   '^enp.s..u.\w*')
fi

quit_network () {
 ifquery --state $wlan >/dev/null && echo "Disconnecting WiFi ..." && sudo ifdown $wlan && sleep 3
 ifconfig | grep -qs $wlan && echo "Disconnecting WiFi ..." && sudo ifconfig $wlan down
 ifquery --state $lan >/dev/null && echo "Disconnecting LAN ..." && sudo ifdown $lan && sleep 3
 ifconfig | grep -qs $lan && echo "Disconnecting LAN ..." && sudo ifconfig $lan down
 [ -n "$usb" ] && sudo ifconfig $usb down
 ifconfig | grep -qs wpa-supplicant && sudo killall wpa_supplicant
    ps ax | grep -qs [d]hclient     && sudo killall dhclient
    ps ax | grep -qs [a]vahi-daemon && sudo killall avahi-daemon
 for i in $(ps ax | grep -s $wlan | grep -vs grep | awk '{print $1}'); do
  sudo killall $i
 done
 sudo ip address flush dev $wlan
}

check_wifi () {
 sudo iwlist $wlan scan | grep -qs ESSID:\""$1"\" || read -p "Wi-Fi($1) is not found, continue? [Y/n]" i
 [ "$i"  = n ] && exit
}

prepare_wifi () {
 ifconfig | grep -qs $wlan || sudo ifconfig $wlan up && sleep 3
}

case $1 in
 up|on)     ifconfig | grep -qs $wlan || sudo ifconfig $wlan up   ;;
 down|off)  ifconfig | grep -qs $wlan && sudo ifconfig $wlan down ;;
 quit|stop) quit_network ;;
 scan) 
  prepare_wifi
  sudo iwlist $wlan scan | sed -n '/Cell/,+8p' ;;
 list)
  prepare_wifi
  sudo iwlist $wlan scan | grep ESSID | cut -d':' -f2 | sort -u | nl -ba ;;
 view)
  for i in bk home lan mr ss
   do
    if cmp -s $net_inf ${net_inf}.d/$i; then
     echo "#${net_inf}.d/$i"
    fi
   done
  echo "#$net_inf"
  grep -v '^ *#' $net_inf ;;
 usb)
  if [ -z "$usb" ];then
   echo "Error: USB tethering is not detected"
   exit
  fi
  sudo ifconfig $usb up && sudo dhclient -v $usb ;;
 lan)
  sudo cp ${net_inf}.d/$1 $net_inf
  echo "#$net_inf"
  grep -v '^ *#' $net_inf
  ifconfig | grep -qs $lan || sudo ifconfig $lan up ;;
 home|mr|ss)
  sudo cp ${net_inf}.d/$1 $net_inf
  echo "#$net_inf"
  grep -v '^ *#' $net_inf ;;
#  ifconfig | grep -qs $lan || sudo ifconfig $lan up
#  ifconfig | grep -qs $wlan || sudo ifconfig $wlan up
#  sudo dhclient -v $lan ;;
#  sudo dhclient -v $wlan ;;
 bk)
  sudo cp ${net_inf}.d/$1 $net_inf
  echo "#$net_inf"
  grep -v '^ *#' $net_inf
  ifconfig | grep -qs $wlan || sudo ifconfig $wlan up ;;
 puppy)
  sudo sed -i '/^wpa-\|^wireless-/s/^/#/' $net_inf
  sudo sed -i '/wpa-ssid '"$1"'$/s/^#*//; /wpa-ssid '"$1"'$/!b;n;s/^#*//' $net_inf
  if ifconfig | grep -qs $wlan; then
   check_wifi "$1"
   quit_network
  else
   sudo ifconfig $wlan up
   sleep 3
   check_wifi "$1"
  fi
  sudo ifup $wlan ;;
 *)
  quit_network
  prepare_wifi
  check_wifi "$1"
  sudo iwconfig $wlan essid "$1"
  sudo dhclient -v $wlan ;;
esac