#!/bin/sh
cpu=$(grep 'cpu ' /proc/stat | awk '{printf 100*($2+$4)/($2+$4+$5)}')
mem=$(free | grep Mem | awk '{print 100*$3/$2}')
status=$(cat /sys/class/power_supply/BAT1/status)
charge=$(cat /sys/class/power_supply/BAT1/capacity)
ut=$(cat /proc/uptime | cut -d'.' -f1)
day=$(($ut/86400))
hrs=$(($ut%86400/3600))
min=$(($ut%3600/60))
sec=$(($ut%60))

printf "$(date +'%Y년%-m월%-d일(%a) %p%-I:%M:%S')"
printf " | ⏱️  %d+%02d:%02d:%02d | CPU \e[32m%0.1f%%\e[0m | MEM \e[32m%0.1f%%\e[0m |" $day $hrs $min $sec $cpu $mem

if [ "$status" = "Charging" ]; then
 printf " 🔌 "
elif [ "$status" = "Discharging" ]; then
 printf " 🔋 "
else
 printf " ❔️ "
fi

#printf "${green}$charge%%${normal}\n"

if [ $charge -lt 20 ] && [ $status != Charging ]; then
#printf " 😓\n"
 printf "\e[31m$charge%%\e[0m\n"
else
#printf " 🙂️"
 printf "\e[32m$charge%%\e[0m\n"
fi
