#!/bin/sh

pgr_sqz=$(pidof squeezelite)

if [ -n "$pgr_sqz" ]; then
 read -p "Quit Squeezelite? [Y/n]" i
 [ "$i" != n ] && pkill squeezelite && echo "Quit Squeezelite!"
 exit
fi

(
 sec=0
 until [ "$(pidof squeezelite)" -gt 0 ] 2>/dev/null; do
  sleep 1
  sec=$(($sec+1))
  [ "$sec" -ge 5 ] && printf "\nSqueezelite is not available!\n" && exit
 done

 sleep 1

 pgr_sqz=$(pidof squeezelite)

 [ -z "$pgr_sqz" ] 2>/dev/null || [ ! "$pgr_sqz" -ge 1 ] 2>/dev/null && echo "Wrong pid of Squeezelite !" && exit

 m_task=$(($(nproc --all)-1))
 [ "$m_task" -ge 3 ] && s_task=$((m_task-2)) || s_task=0

 sudo taskset -pc $s_task $pgr_sqz
 
 count=2

 echo "$(pstree -npt $pgr_sqz)" | while read line ; do
 #proc=$(echo "$line" | cut -d "{" -f2 | cut -d "}" -f1 | cut -d ":" -f1)
  proc_nr=$(echo "$line" | cut -d "}" -f2 | cut -d "(" -f2 | cut -d ")" -f1)
  case $count in
   3) taskset -cp $m_task $proc_nr ;;
   *) taskset -cp $s_task $proc_nr ;;
  esac
  count=$(($count+1))
 done
 pkill -x sqzlite
) &

[ ! -e /dev/shm/squeezelite ] && sudo cp /usr/bin/squeezelite /dev/shm/squeezelite
/dev/shm/squeezelite -C 1 -o pcm.hw -O ctl.hw>/dev/null</dev/null 2>/dev/null
