#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") torrent"
}

if [ -r "$*" ]; then
 aria2c --dir=/home/parkmino/Downloads --seed-time=0 --enable-dht6=false --disable-ipv6=true "$*"
else
 usage
 exit
fi

