#!/bin/sh

#prog_1="싱어게인2\t\t\e[36m(월 20:30-00:30)\e[0m"
#prog_0="비긴어게인 오픈마이크\t\e[36m(화 20:30-00:40)\e[0m"
 prog_1="팬텀싱어4\t\t\e[36m(금 20:50-23:20)\e[0m"
#prog_0="슈퍼밴드2\t\t\e[36m(월 20:50-23:10)\e[0m"
 prog_2="맛있는 녀석들\t\e[36m(금 20:00-21:20)\e[0m"
 prog_3="멜론"

nr=1

while true; do
 prog=$(eval echo \"\$prog_$nr\")
 [ -z "$prog" ] && break
 printf "(\e[32m%d\e[0m) %s\n" $nr "$prog"
 nr=$(($nr+1))
done

read -p " " i

case $i in
#0) [ $(date +%k) -ge 22 ] && time="today 21:30" || time="yesterday 21:30" ;;
#0) [ $(date +%u) -eq 5 ] && [ $(date +%k) -ge 22 ] && time="today 21:00" || time="last friday 21:00" ;;
#0) time="last friday   23:00"	;;
#0) time="last saturday 23:59"	;;
 1) time="last tuesday  23:59"	;;
#1) time="last monday   23:10"	;;
 2) [ $(date +%u) -eq 5 ] && [ $(date +%k) -ge 22 ] && time="today 21:20" || time="last friday 21:20" ;;
 3) time="yesterday"		;;
 *) exit			;;
esac

prog=$(eval echo \"\$prog_$i\" | cut -f1)

if [ "$time" = yesterday ]; then
 hour=24
 find="$prog 토렌트"
else
 hour=$((($(date +%s)-$(date +%s -d "$time"))/3600))
 [ $hour -le 0 ] && hour=1
 find="$prog $(date +%y%m%d -d "$time") 토렌트"
fi

#cmd="googler --colorize -t h$hour -n 9 --np "$find""
cmd="ddgr --colorize -n 9 --np -x "$find""
echo ; echo " $cmd"
$cmd | more

