#!/bin/sh

items=4

#prog_1="JTBC 뉴스룸"
 prog_1="보이스 코리아 2020"
 prog_2="팬텀싱어3"
 prog_3="비긴 어게인"
 prog_4="멜론"

for i in $(seq 1 $items); do
 printf "(%d) %s %s %s %s %s\n" $i $(eval echo \$prog_$i)
done

read -p " " i

case $i in
#1) [ $(date +%k) -ge 22 ] && time="today 21:30" || time="yesterday 21:30" ;;
 1) [ $(date +%u) -eq 5 ] && [ $(date +%k) -ge 22 ] && time="today 21:10" || time="last friday 21:10" ;;
 2) time="last friday 23:00"	;;
 3) time="last saturday 23:59"	;;
 4) time="yesterday"		;;
 *) exit			;;
esac

prog=$(eval echo \$prog_$i)

if [ "$time" = yesterday ]; then
 hour=24
 find="$prog 토렌트"
else
 hour=$((($(date +%s)-$(date +%s -d "$time"))/3600))
 [ $hour -le 0 ] && hour=1
 find="$prog $(date +%y%m%d -d "$time") 토렌트"
fi

cmd="googler --colorize -t h$hour -n 9 --np "$find""
echo ; echo " $cmd"
$cmd | more
