#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") [qq|tfreeca|tf|view|vw]"
 echo "Scrape torrent movies"
}

chk_url () {
 printf "\n[ %s ]\n\n" $url
 if ! fping -q $(echo "$url" | cut -d\/ -f3-) 2>&1 && ! wget --spider -q "$url" 2>&1; then
  echo "$url is not connected!"
  exit
 fi
}

curl_opt="-s --connect-timeout 9 --max-time 9"

chk_movie () {
 if [ -z "$movie" ]; then
  echo "$url"
  echo "Movies are not available"
  [ -e "$tmpfile" ] && rm "$tmpfile"
  exit
 elif [ "$movie" = en-US ]; then
  echo "$url"
  echo "Movies are not valid"
  [ -e "$tmpfile" ] && rm "$tmpfile"
  exit
 else
  printf "%2d.%s\n" $i "$movie"
 fi
}

torwal () {
 url="https://torrentwal.com"
 chk_url
 for i in $(seq 1 10); do
  movie=$(curl $curl_opt -L -k "$url" | grep -o '영화</a> 인기자료.*' | sed 's/>[0-9]*\. <a href='\''\.\./\n/g' | head -$((i+1)) | tail -1 | cut -d'>' -f2 | cut -d'<' -f1 | sed 's/^[ \t]*//' | sed 's/\&amp;/\&/g; s/&#39;\|&#039;/'\''/g')
  chk_movie
  printf "     \e[34m$url$(curl $curl_opt -L -k "$url" | grep -o '영화</a> 인기자료.*' | sed 's/>[0-9]*\. *<a href='\''\.\./\n/g' | head -$((i+1)) | tail -1 | cut -d\' -f1)\e[0m\n"
 done
}

torqq () {
#url="https://토렌트큐큐.net"
 url="https://torrentqq324.com"
 chk_url || return
 [ -z "${url##*큐큐*}" ] && url="$(curl $curl_opt -L "$url" | grep -o href=.* | cut -d\" -f2 | cut -d\/ -f-3)"
 url="$url/torrent/popular.html?period=w&board=mov"
 tmpfile=$(mktemp)
 curl $curl_opt -L "$url" | sed 's/title=/\n/g' > "$tmpfile"
 for i in $(seq 1 10); do
  movie=$(head -$((i+7)) "$tmpfile" | tail -1 | cut -d\" -f2 | sed 's/\&amp;/\&/g; s/&#39;\|&#039;/'\''/g')
  chk_movie
  printf "    \e[34m$(grep -o "http[s]://torrentqq[0-9]*.com/torrent/mov/[0-9]*.html" "$tmpfile" | head -$i | tail -1 | cut -d\" -f2)\e[0m\n"
 done
 rm "$tmpfile"
}

torview () {
 url="https://torrentview57.com"
 chk_url || return
 url="$url/bbs/board.php?bo_table=mov"
 tmpfile=$(mktemp)
 curl $curl_opt -L "$url" | grep -A 60 '인기 포스트' > "$tmpfile"
 for i in $(seq 1 10); do
  movie=$(grep '</a>' "$tmpfile" | head -$i | tail -1 | sed 's/ <\/a>//' | sed 's/\&amp;/\&/g; s/&#39;\|&#039;/'\''/g')
  chk_movie
  printf "    \e[34m$(grep '<a href=' "$tmpfile" | head -$i | tail -1 | cut -d\" -f2 | sed 's/\&amp;/\&/g')\e[0m\n"
 done
 rm "$tmpfile"
}

tfreeca () {
 url="https://tfreeca22.com"
 chk_url || return
 url="$url/top100.php?b_id=tmovie&hit=Week"
 tmpfile=$(mktemp)
 curl $curl_opt -L "$url" | grep -m 10 '<span class="ca">' > "$tmpfile"
 for i in $(seq 1 10); do
  movie=https://tfreeca22.com/$(grep '<span class="ca">' "$tmpfile" | head -$i | tail -1 | cut -d\" -f10)
  chk_movie
 #printf "    \e[34m$(grep '<a href=' "$tmpfile" | head -$i | tail -1 | cut -d\" -f11 | sed 's/^.*class> //g; s/ <\/a>.*//g')\e[0m\n"
  printf "    \e[34m$(grep '<span class="ca">' "$tmpfile" | head -$i | tail -1 | cut -d\" -f11- | sed 's/^ class=..> //; s/ <\/a>.*//g')\e[0m\n"
 done
 rm "$tmpfile"
}

case $1 in
 qq)           torqq   ;;
 view|vw)      torview ;;
 tfreeca|tf)   tfreeca ;;
 *)            torqq   ;;
esac
