#!/bin/sh

# sudo apt-get install mpg123 sox libttspico-utils
# https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
# Chinese - zh, English - en, Finnish - fi, French - fr, German - de, Japanese - ja, ...

alsa=$(head -1 /usr/share/alsa/alsa.conf | cut -d'.' -f1-2)
pico_wav="/home/parkmino/Downloads/tts.wav"

#ping -q -c1 -t1 -w1 -W1 google.com >/dev/null 2>&1 && tts_svc=google || tts_svc=pico
#curl -m1 -s http://translate.google.com >/dev/null 2>&1 && tts_svc=google || tts_svc=pico
wget -q --spider -T1 http://google.com && tts_svc=google || tts_svc=pico

case $tts_svc in
 google)
  if [ $# -eq 0 ]; then
   queue="tl=ko&q=지금 시각은 $(date +"%p %-I:%M") 입니다"
  #queue="tl=ko&q=저의 IP는 $(hostname -I) 입니다"
  elif [ $# -ge 2 ] && [ ${#1} -eq 2 ] && [ $(expr "$1" : "[a-z]*") -eq 2 ]; then
   tl=$1
   shift
   queue="tl=$tl&q=$*"
  else
   queue="tl=ko&q=$*"
  fi
  mpc stop >/dev/null 2>&1
  mpg123 -b 512 -q -o alsa -a $alsa "http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&$queue"&>/dev/null</dev/null& ;;
 pico)
  if [ -z "$1" ]; then
   pico2wave -w $pico_wav "Now the time is $(date +"%-I %-M")"
  #pico2wave -w $pico_wav "My IP is $(hostname -I)"
  else
   pico2wave -w $pico_wav "$*"
  fi
  mpc stop >/dev/null 2>&1
  AUDIODEV=$alsa play -q -V0 $pico_wav & ;;
esac

#mplayer -really-quiet "$url"			# -dumpstream -dumpfile tts.mp3
#mpv --really-quiet "$url"			# --stream-dump=tts.mp3
#gst123 -qx -a alsa=$alsa "$url"
