#!/bin/sh

# https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
# Chinese - zh, English - en, Finnish - fi, French - fr, German - de, Japanese - ja, ...

! wget -q --spider -T1 http://google.com && echo "Google is not reachable!" && exit

if [ $# -eq 0 ]; then
 queue="tl=ko&q=%EC%A0%80%EC%9D%98 IP%EB%8A%94 $(hostname -I) %EC%9E%85%EB%8B%88%EB%8B%A4 %ED%98%84%EC%9E%AC %EC%8B%9C%EA%B0%81%EC%9D%80%0D%0A $(date +"%-I:%M") %EC%9E%85%EB%8B%88%EB%8B%A4"
else
 case $1 in
  [a-z][a-z])
   tl=$1
   shift
   queue="tl=$tl&q=$(echo "$*" | jq -sRr @uri)" ;;
  *)
   queue="tl=ko&q=$(echo "$*" | jq -sRr @uri)" ;;
 esac
fi

mpc add $(echo "https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&$queue" | sed 's/ /+/g') && mpc -q play $(mpc playlist | wc -l) && mpc current --wait && mpc del $(mpc playlist | wc -l)
