#!/bin/sh

# https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
# Chinese - zh, English - en, Finnish - fi, French - fr, German - de, Japanese - ja, ...

! wget -q --spider -T1 http://google.com && echo "Google is not reachable!" && exit

if [ $# -eq 0 ]; then
 queue="tl=ko&q=지금 시각은 $(date +"%p %-I:%M") 입니다"
#queue="tl=ko&q=저의 IP는 $(hostname -I) 입니다"
elif [ $# -ge 2 ] && [ ${#1} -eq 2 ] && [ $(expr "$1" : "[a-z]*") -eq 2 ]; then
 tl=$1
 shift
 queue="tl=$tl&q=$*"
else
 queue="tl=ko&q=$*"
fi

mpc add $(echo "http://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&$queue" | sed 's/ /%20/g') && mpc play $(mpc playlist | wc -l) && mpc current --wait && mpc del $(mpc playlist | wc -l)
