#!/bin/sh
(
times=0
until [ "$(pgrep -x upmpdcli)" -gt 0 ] 2>/dev/null; do
 sleep 1
 times=$(($times+1))
 [ "$times" -ge 10 ] && printf "\nUpmpdcli is not running!\n" && exit
done
sleep 1

m_task=$(($(nproc --all)-1))
[ "$m_task" -ge 3 ] && s_task=$((m_task-2)) || s_task=0

taskset -acp $s_task $(pgrep -x upmpdcli)
) &

nohup /usr/bin/upmpdcli -D -c /etc/upmpdcli.conf>/dev/null</dev/null 2>/dev/null
