#!/bin/sh

m_task=$(($(nproc --all)-1))
[ "$m_task" -ge 3 ] && s_task=$((m_task-2)) || s_task=0

taskset -ac $s_task /dev/shm/nohup /usr/bin/upmpdcli -D -c /etc/upmpdcli.conf>/dev/null</dev/null 2>/dev/null
