#!/bin/sh

m_task=$(($(nproc --all)-1)); h_task=0; s_task=0
[ "$m_task" -ge 3 ] && h_task=$((m_task-1)) && s_task=$((m_task-2))

taskset -ac $h_task /usr/bin/upmpdcli -D -c /etc/upmpdcli.conf>/dev/null</dev/null 2>/dev/null
