#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") [ch|ck|m3u]"
 echo "Scrape and list U+TV channels"
}

[ -z "$1" ] && usage && exit

time=$(date +%Y%m%d%H%M%S)
m3u_dir="/home/parkmino/Videos"

ch_1=682; prog_1="tvN"
ch_2=696; prog_2="올리브"
ch_3=689; prog_3="O tvN"
ch_4=671; prog_4="XtvN"
ch_5=778; prog_5="온스타일"
ch_6=606; prog_6="JTBC2"
ch_7=662; prog_7="K스타"
ch_8=389; prog_8="KBSN PLUS"
ch_9=603; prog_9="라이프타임"
ch_10=690; prog_10="채널 다이아"
ch_11=767; prog_11="JTBC4"
ch_12=725; prog_12="중화TV"
ch_13=658; prog_13="아시아N"
ch_14=727; prog_14="STATV"
ch_15=747; prog_15="JTBC"
ch_16=750; prog_16="MBN"
ch_17=749; prog_17="채널A"
ch_18=746; prog_18="TV조선"
ch_19=596; prog_19="OBS"
ch_20=648; prog_20="OBS W"
ch_21=001; prog_21="프로야구1"
ch_22=011; prog_22="프로야구2"
ch_23=041; prog_23="프로야구3"
ch_24=021; prog_24="프로야구4"
ch_25=031; prog_25="프로야구5"
ch_26=667; prog_26="스포티비"
ch_27=383; prog_27="SPOTV2"
ch_28=381; prog_28="SBS스포츠"
ch_29=397; prog_29="프로야구 청백전1"
ch_30=398; prog_30="프로야구 청백전2"
ch_31=399; prog_31="프로야구 청백전3"
ch_32=602; prog_32="JTBC골프"
ch_33=614; prog_33="SBS골프"
ch_34=650; prog_34="스포티비 골프 앤 헬스"
ch_35=795; prog_35="JTBC골프앤스포츠"
ch_36=668; prog_36="빌리어즈TV"
ch_37=698; prog_37="YTN"
ch_38=734; prog_38="연합뉴스TV"
ch_39=729; prog_39="CNN International"
ch_40=771; prog_40="토마토TV"
ch_41=174; prog_41="CNBC"
ch_42=687; prog_42="엠넷"
ch_43=794; prog_43="가요TV"
ch_44=688; prog_44="GMTV"
ch_45=391; prog_45="PLAYY프리미엄"
ch_46=392; prog_46="PLAYY웰메이드"
ch_47=683; prog_47="바둑TV"
ch_48=665; prog_48="FTV"
ch_49=625; prog_49="피싱TV"
ch_50=726; prog_50="폴라리스TV"
ch_51=707; prog_51="브레인TV"
ch_52=703; prog_52="애니맥스"
ch_53=699; prog_53="애니플러스"
ch_54=761; prog_54="어린이TV"
ch_55=728; prog_55="브라보키즈"
ch_56=676; prog_56="GS샵"
ch_57=675; prog_57="현대홈쇼핑"
ch_58=672; prog_58="CJ오쇼핑"
ch_59=674; prog_59="롯데홈쇼핑"
ch_60=673; prog_60="NS홈쇼핑"
ch_61=649; prog_61="홈앤쇼핑"
ch_62=740; prog_62="GS마이샵"
ch_63=760; prog_63="현대홈쇼핑+샵"
ch_64=813; prog_64="W 쇼핑"
ch_65=681; prog_65="OGN"
ch_66=505; prog_66="EBS1"
ch_67=607; prog_67="EBS Kids"
ch_68=173; prog_68="EBS+2"
ch_69=172; prog_69="EBS+1"
ch_70=768; prog_70="EBSEnglish"
ch_71=793; prog_71="JEI EnglishTV"
ch_72=175; prog_72="플레이런TV"

uptv_ck () {
 ch="http://123.140.104.150/api/epg/v1/channel/virtual?access_key=C4A0697007C3548D389B&cp_id=S_LGU_HYUK0920&system_id=HDTV&SA_ID=500053434041&STB_MAC=v000.5343.4041&NSC_TYPE=LTE&BASE_GB=Y&BASE_CD=W172.017&YOUTH_YN=N&ORDER_GB=N&POOQ_YN=N&HDTV_VIEW_GB=R&SID=001010005638&CLIENT_IP=172.17.100.15&OS_INFO=android_4.4.2&NW_INFO=WIFI&APP_TYPE=ROSA&DEV_MODEL=SM-N935F&CARRIER_TYPE=E&UI_VER=04.38.04&NOW_PAGE=25&PRE_PAGE=&MENU_NM=&CONTS_GB=&TERM_BINVER=3.8.118.0106"
 times=$(curl -s "$ch" | grep -o "<service_id>" | wc -l)
 for i in $(seq 1 $times); do
  echo "ch_$i=$(curl -s "$ch" | grep -o "<service_id>[0-9]*" | cut -d\> -f2 | head -$i | tail -1); prog_$i=\"$(curl -s "$ch" | grep -o "<service_name>...................." | cut -d\> -f2 | cut -d\< -f1 | sed 's/^[ \t]//' | head -$i | tail -1)\""
 done
 echo
 for i in $(seq 1 $times); do
  printf "($i) $(curl -s "$ch" | grep -o "<service_name>...................." | cut -d\> -f2 | cut -d\< -f1 | sed 's/^[ \t]//' | head -$i | tail -1)"
  [ $(expr $i % 5) -eq 0 ] && printf '\n' || printf '\t'
 done
 [ $(expr $i % 5) -eq 0 ] || printf '\n'
}

uptv_m3u () {
 printf "#EXTM3U\n" > $m3u_dir/uptv.m3u
 for i in $(seq 1 78); do
 #url="http://1.214.67.74:80/$(eval echo \$ch_$i)HN.m3u8?VOD_RequestID=v2M2-0101-1010-7272-5050-0000$time;LTE;720p;WIFI&APPNAME=hdtv&ALBUM_ID=747&ma=D0:17:C2:CE:D7:A1"
  url="http://1.214.67.74:80/$(eval echo \$ch_$i)HN.m3u8?VOD_RequestID=v2M2-0101-1010-7272-5050-0000$time"
  printf "#EXTINF:-1,$(eval echo \$prog_$i)\n$url\n" >> $m3u_dir/uptv.m3u
 done
}

[ "$1" = ck  ] && uptv_ck  && exit
[ "$1" = m3u ] && uptv_m3u && exit

echo "\
(1) tvN		(2) 올리브	(3) O tvN	(4) XtvN	(5) 온스타일
(6) JTBC2	(7) K스타	(8) KBSN PLUS	(9) 라이프타임	(10) 채널 다이아
(11) JTBC4	(12) 중화TV	(13) 아시아N	(14) STATV	(15) JTBC
(16) MBN	(17) 채널A	(18) TV조선	(19) OBS	(20) OBS W
(21) 프로야구1	(22) 프로야구2	(23) 프로야구3	(24) 프로야구4	(25) 프로야구5
(26) 스포티비	(27) SPOTV2	(28) SBS스포츠	(29) 청백전1	(30) 청백전2
(31) 청백전3	(32) JTBC골프	(33) SBS골프	(34) 골프앤헬스 (35) 골프앤스포츠
(36) 빌리어즈TV	(37) YTN	(38) 연합뉴스TV	(39) CNN	(40) 토마토TV
(41) CNBC	(42) 엠넷	(43) 가요TV	(44) GMTV	(45) PLAYY프리
(46) PLAYY웰	(47) 바둑TV	(48) FTV	(49) 피싱TV	(50) 폴라리스TV
(51) 브레인TV	(52) 애니맥스	(53) 애니플러스 (54) 어린이TV	(55) 브라보키즈
(56) GS샵	(57) 현대홈쇼핑 (58) CJ오쇼핑	(59) 롯데홈쇼핑 (60) NS홈쇼핑
(61) 홈앤쇼핑	(62) GS마이샵	(63) 현대홈쇼핑 (64) W 쇼핑	(65) OGN
(66) EBS1	(67) EBS Kids	(68) EBS+2	(69) EBS+1	(70) EBSEnglish
(71) JEI English (72) 플레이런TV"

read -p " " i

case $i in
 [1-9]|[1-6][0-9]|7[0-5])
   #url="http://1.214.67.74:80/$(eval echo \$ch_$i)HN.m3u8?VOD_RequestID=v2M2-0101-1010-7272-5050-0000$time;LTE;720p;WIFI&APPNAME=hdtv&ALBUM_ID=747&ma=D0:17:C2:CE:D7:A1"
    url="http://1.214.67.74:80/$(eval echo \$ch_$i)HN.m3u8?VOD_RequestID=v2M2-0101-1010-7272-5050-0000$time"
    echo "$url"
    prog=$(eval echo \$prog_$i)
    printf "#EXTM3U\n#EXTINF:-1,$prog\n$url\n" > $m3u_dir/$prog.m3u ;;
 *) exit ;;
esac
