#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") [ch|ck|m3u]"
 echo "Scrape and list U+TV channels"
}

[ -z "$1" ] && usage && exit

time=$(date +%Y%m%d%H%M%S)
m3u_dir="/home/parkmino/Videos"

ch_1=747; prog_1="JTBC"
ch_2=750; prog_2="MBN"
ch_3=749; prog_3="채널A"
ch_4=746; prog_4="TV조선"
ch_5=596; prog_5="OBS"
ch_6=648; prog_6="OBS W"
ch_7=772; prog_7="더라이프"
ch_8=606; prog_8="JTBC2"
ch_9=662; prog_9="K스타"
ch_10=603; prog_10="라이프타임"
ch_11=767; prog_11="JTBC4"
ch_12=658; prog_12="아시아N"
ch_13=727; prog_13="STATV"
ch_14=001; prog_14="프로야구1"
ch_15=011; prog_15="프로야구2"
ch_16=041; prog_16="프로야구3"
ch_17=021; prog_17="프로야구4"
ch_18=031; prog_18="프로야구5"
ch_19=400; prog_19="프로야구6"
ch_20=667; prog_20="스포티비"
ch_21=383; prog_21="SPOTV2"
ch_22=381; prog_22="SBS스포츠"
ch_23=382; prog_23="MBC스포츠플러스"
ch_24=602; prog_24="JTBC골프"
ch_25=614; prog_25="SBS골프"
ch_26=650; prog_26="스포티비 골프 앤 헬스"
ch_27=795; prog_27="JTBC골프앤스포츠"
ch_28=668; prog_28="빌리어즈TV"
ch_29=698; prog_29="YTN"
ch_30=734; prog_30="연합뉴스TV"
ch_31=729; prog_31="CNN International"
ch_32=771; prog_32="토마토증권통"
ch_33=174; prog_33="CNBC"
ch_34=676; prog_34="GS샵"
ch_35=675; prog_35="현대홈쇼핑"
ch_36=672; prog_36="CJ온스타일"
ch_37=674; prog_37="롯데홈쇼핑"
ch_38=673; prog_38="NS홈쇼핑"
ch_39=649; prog_39="홈앤쇼핑"
ch_40=740; prog_40="GS마이샵"
ch_41=760; prog_41="현대홈쇼핑+샵"
ch_42=813; prog_42="W 쇼핑"
ch_43=390; prog_43="U+모바일TV 라이브"
ch_44=794; prog_44="가요TV"
ch_45=688; prog_45="GMTV"
ch_46=391; prog_46="PLAYY프리미엄"
ch_47=392; prog_47="PLAYY웰메이드"
ch_48=683; prog_48="바둑TV"
ch_49=665; prog_49="FTV"
ch_50=625; prog_50="피싱TV"
ch_51=726; prog_51="폴라리스TV"
ch_52=707; prog_52="브레인TV"
ch_53=703; prog_53="애니맥스"
ch_54=699; prog_54="애니플러스"
ch_55=761; prog_55="어린이TV"
ch_56=728; prog_56="브라보키즈"
ch_57=505; prog_57="EBS1"
ch_58=607; prog_58="EBS Kids"
ch_59=173; prog_59="EBS+2"
ch_60=172; prog_60="EBS+1"
ch_61=600; prog_61="EBS러닝 초등3"
ch_62=714; prog_62="EBS러닝 초등4"
ch_63=715; prog_63="EBS러닝 초등5"
ch_64=719; prog_64="EBS러닝 초등6"
ch_65=722; prog_65="EBS러닝 중학1"
ch_66=730; prog_66="EBS러닝 중학2"
ch_67=768; prog_67="EBSEnglish"
ch_68=793; prog_68="JEI EnglishTV"
ch_69=175; prog_69="플레이런TV"
ch_70=629; prog_70=""
ch_71=628; prog_71=""
ch_72=743; prog_72=""

uptv_ck () {
 ch="http://123.140.104.150/api/epg/v1/channel/virtual?access_key=C4A0697007C3548D389B&cp_id=S_LGU_HYUK0920&system_id=HDTV&SA_ID=500053434041&STB_MAC=v000.5343.4041&NSC_TYPE=LTE&BASE_GB=Y&BASE_CD=W172.017&YOUTH_YN=N&ORDER_GB=N&POOQ_YN=N&HDTV_VIEW_GB=R&SID=001010005638&CLIENT_IP=172.17.100.15&OS_INFO=android_4.4.2&NW_INFO=WIFI&APP_TYPE=ROSA&DEV_MODEL=SM-N935F&CARRIER_TYPE=E&UI_VER=04.38.04&NOW_PAGE=25&PRE_PAGE=&MENU_NM=&CONTS_GB=&TERM_BINVER=3.8.118.0106"
 times=$(curl -s "$ch" | grep -o "<service_id>" | wc -l)
 for i in $(seq 1 $times); do
  echo "ch_$i=$(curl -s "$ch" | grep -o "<service_id>[0-9]*" | cut -d\> -f2 | head -$i | tail -1); prog_$i=\"$(curl -s "$ch" | grep -o "<service_name>...................." | cut -d\> -f2 | cut -d\< -f1 | sed 's/^[ \t]//' | head -$i | tail -1)\""
 done
 echo
 for i in $(seq 1 $times); do
  printf "($i) $(curl -s "$ch" | grep -o "<service_name>...................." | cut -d\> -f2 | cut -d\< -f1 | sed 's/^[ \t]//' | head -$i | tail -1)"
  [ $(expr $i % 5) -eq 0 ] && printf '\n' || printf '\t'
 done
 [ $(expr $i % 5) -eq 0 ] || printf '\n'
}

uptv_m3u () {
 nr=1
 printf "#EXTM3U\n" > $m3u_dir/uptv.m3u
 while true; do
  ch=$(eval echo \$ch_$nr)
  [ -z "$ch" ] && break
 #url="http://1.214.67.74:80/${ch}HN.m3u8?VOD_RequestID=v2M2-0101-1010-7272-5050-0000$time;LTE;720p;WIFI&APPNAME=hdtv&ALBUM_ID=747&ma=D0:17:C2:CE:D7:A1"
  url="http://1.214.67.74:80/${ch}HN.m3u8?VOD_RequestID=v2M2-0101-1010-7272-5050-0000$time"
  printf "#EXTINF:-1,$(eval echo \$prog_$nr)\n$url\n" >> $m3u_dir/uptv.m3u
  nr=$(($nr+1))
 done
}

uptv_ch () {
 echo "\
(1)  JTBC	(2)  MBN	(3)  채널A	(4)  TV조선	(5)  OBS
(6)  OBS W	(7)  더라이프	(8)  JTBC2	(9)  K스타	(10) 라이프타임
(11) JTBC4	(12) 아시아N	(13) STATV	(14) 프로야구1	(15) 프로야구2
(16) 프로야구3	(17) 프로야구4	(18) 프로야구5	(19) 프로야구6	(20) 스포티비
(21) SPOTV2	(22) SBS스포츠	(23) MBC스포츠+	(24) JTBC골프	(25) SBS골프
(26) 골프앤헬스 (27) JTBC골프	(28) 빌리어즈TV	(29) YTN	(30) 연합뉴스TV
(31) CNN	(32) 토마토증권 (33) CNBC	(34) GS샵	(35) 현대홈쇼핑
(36) CJ온스타일	(37) 롯데홈쇼핑 (38) NS홈쇼핑	(39) 홈앤쇼핑	(40) GS마이샵
(41) 현대홈쇼핑 (42) W 쇼핑	(43) U+ 라이브	(44) 가요TV	(45) GMTV
(46) PLAYY프리	(47) PLAYY웰메	(48) 바둑TV	(49) FTV	(50) 피싱TV
(51) 폴라리스TV	(52) 브레인TV	(53) 애니맥스	(54) 애니플러스 (55) 어린이TV
(56) 브라보키즈 (57) EBS1	(58) EBS Kids	(59) EBS+2	(60) EBS+1
(61) EBS 초등3	(62) EBS 초등4	(63) EBS 초등5	(64) EBS 초등6	(65) EBS 중학1
(66) EBS 중학2	(67) EBSEnglish	(68) JEI 영어TV	(69) 플레이런TV"

 read -p " " i

 ch=$(eval echo \$ch_$i)
 [ -z "$ch" ] && exit
#url="http://1.214.67.74:80/${ch}HN.m3u8?VOD_RequestID=v2M2-0101-1010-7272-5050-0000$time;LTE;720p;WIFI&APPNAME=hdtv&ALBUM_ID=747&ma=D0:17:C2:CE:D7:A1"
 url="http://1.214.67.74:80/${ch}HN.m3u8?VOD_RequestID=v2M2-0101-1010-7272-5050-0000$time"
 prog=$(eval echo \$prog_$i)
 [ -z "$prog" ] && prog=$i
 echo " $prog"
 echo " $url"
 printf "#EXTM3U\n#EXTINF:-1,$prog\n$url\n" > $m3u_dir/$prog.m3u
}

case "$1" in
 ch)	uptv_ch  ;;
 ck)	uptv_ck  ;;
 m3u)	uptv_m3u ;;
 *)	usage    ;;
esac
