#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") [jtbc|kbs_news|tbs|yonhap|ytn|ytn_life|ytn_science|rtv]"
 echo "Scrape youtube live url for kodi"
}

[ -z "$1" ] && usage && exit

dir="/home/parkmino/.kodi/userdata/playlists/video/YOUTUBE"

[ "$1" = jtbc        ] && url="user/JTBC10news" 
[ "$1" = kbs_news    ] && url="user/NewsKBS"
[ "$1" = tbs         ] && url="user/seoultbstv/featured"
[ "$1" = yonhap      ] && url="channel/UCTHCOPwqNfZ0uiKOvFyhGwg"
[ "$1" = ytn         ] && url="user/ytnnews24"
[ "$1" = ytn_life    ] && url="channel/UCDww6ExpwQS0TzmREIOo40Q"
[ "$1" = ytn_science ] && url="user/ytnscience"
[ "$1" = rtv         ] && url="channel/UCvogIa1elSl9iwF4MbRXmAQ"

url=$(curl -s "https://www.youtube.com/$url" | grep -m1 -o data-context-item-id.* | cut -d\" -f2)
#[ -n "$url" ] && echo "https://youtu.be/$url"
 [ -n "$url" ] && printf "plugin://plugin.video.youtube/play/?video_id=$url"
