#!/bin/sh

echo "\
(j) JTBC 뉴스
(k) KBS 뉴스
(m) MBC 뉴스
(s) SBS 뉴스
(t) tbs TV
(y) 연합뉴스TV
(v) YTN LIVE
(f) YTN 라이프
(c) YTN 사이언스
(g) 맛있는 녀석들" # (r) RTV 시민방송

read -p " " i

case $i in
 j) ch=jtbcnews    ; url="https://www.youtube.com/user/JTBC10news"                  ;;
 k) ch=kbsnews     ; url="https://www.youtube.com/user/NewsKBS"                     ;;
 m) ch=mbcnews     ; url="https://www.youtube.com/channel/UCF4Wxdo3inmxP-Y59wXDsFw" ;;
 s) ch=sbsnews     ; url="https://www.youtube.com/channel/UCkinYTS9IHqOEwR1Sze2JTw" ;;
 t) ch=tbs         ; url="https://www.youtube.com/user/seoultbstv/featured"         ;;
 y) ch=yonhap      ; url="https://www.youtube.com/channel/UCTHCOPwqNfZ0uiKOvFyhGwg" ;;
 v) ch=ytn         ; url="https://www.youtube.com/user/ytnnews24"                   ;;
 f) ch=ytn_life    ; url="https://www.youtube.com/channel/UCDww6ExpwQS0TzmREIOo40Q" ;;
 c) ch=ytn_science ; url="https://www.youtube.com/user/ytnscience"                  ;;
 r) ch=rtv         ; url="https://www.youtube.com/channel/UCvogIa1elSl9iwF4MbRXmAQ" ;;
 g) ch=tastyguys   ; url="https://www.youtube.com/channel/UCsOW9TPy2TKkqCchUHL04Fg" ;;
 *) exit ;;
esac

if [ "$i" = g ]; then
 uturl=$(curl -s "$url" | grep '실시간 스트리밍 중' | grep -o '"videoId":"[0-9A-Za-z_-]*"' | head -1 | cut -d\" -f4)
  if [ -n "$uturl" ]; then
   label=$(curl -s "$url" | grep -o '"label":.*' | cut -d\" -f4)
   [ -z "$label" ] && printf "  정보 없음\n  https://youtu.be/$uturl\n" && exit
   days=$(echo "$label" | sed 's/.*) //; s/ 조회수.*//')
   prog=$(echo "$label" | sed 's/ \[맛있는.*//')
   printf "\e[32m$prog ($days)\e[0m\n"
  fi
else
 uturl=$(curl -s "$url" | grep -o data-context-item-id.* | head -1 | cut -d\" -f2)
fi

[ -z "$uturl" ] && echo "YouTube url is not found !" && exit

 printf "\e[34m$url\e[0m\n$ch - https://youtu.be/$uturl\n"
#printf "\e[34m$url\e[0m\n$ch - plugin://plugin.video.youtube/play/?video_id=$uturl\n"

printf "#EXTM3U\n#EXTINF:-1,$(echo "$ch" | tr a-z A-Z)\nhttps://youtu.be/$uturl\n" > /home/parkmino/Videos/$ch.m3u
