#!/bin/sh

echo "\
(j) JTBC 뉴스
(k) KBS 뉴스
(m) MBC 뉴스
(s) SBS 뉴스
(t) tbs TV
(y) 연합뉴스TV
(v) YTN LIVE
(f) YTN 라이프
(s) YTN 사이언스" # (r) RTV 시민방송

read -p " " i

case $i in
 j) ch=jtbcnews    ; url="https://www.youtube.com/user/JTBC10news"                  ;;
 k) ch=kbsnews     ; url="https://www.youtube.com/user/NewsKBS"                     ;;
 m) ch=mbcnews     ; url="https://www.youtube.com/channel/UCF4Wxdo3inmxP-Y59wXDsFw" ;;
 s) ch=sbsnews     ; url="https://www.youtube.com/channel/UCkinYTS9IHqOEwR1Sze2JTw" ;;
 t) ch=tbs         ; url="https://www.youtube.com/user/seoultbstv/featured"         ;;
 y) ch=yonhap      ; url="https://www.youtube.com/channel/UCTHCOPwqNfZ0uiKOvFyhGwg" ;;
 v) ch=ytn         ; url="https://www.youtube.com/user/ytnnews24"                   ;;
 f) ch=ytn_life    ; url="https://www.youtube.com/channel/UCDww6ExpwQS0TzmREIOo40Q" ;;
 s) ch=ytn_science ; url="https://www.youtube.com/user/ytnscience"                  ;;
 r) ch=rtv         ; url="https://www.youtube.com/channel/UCvogIa1elSl9iwF4MbRXmAQ" ;;
 *) exit ;;
esac

uturl=$(curl -s "$url" | grep -m1 -o data-context-item-id.* | cut -d\" -f2)
 [ -n "$uturl" ] && printf "  $ch - https://youtu.be/$uturl\n( $url )\n"
#[ -n "$uturl" ] && printf "  $ch - plugin://plugin.video.youtube/play/?video_id=$uturl\n( $url )\n"

m3u_dir="/home/parkmino/Videos"

printf "#EXTM3U\n#EXTINF:-1,$(echo "$ch" | tr a-z A-Z)\nhttps://youtu.be/$uturl\n" > $m3u_dir/$ch.m3u
