#!/bin/sh

echo "\
(\e[32mj\e[0m) JTBC 뉴스
(\e[32mk\e[0m) KBS 뉴스
(\e[32mm\e[0m) MBC 뉴스
(\e[32ms\e[0m) SBS 뉴스
(\e[32mt\e[0m) tbs TV
(\e[32my\e[0m) 연합뉴스TV
(\e[32mv\e[0m) YTN LIVE
(\e[32mf\e[0m) YTN 라이프
(\e[32mc\e[0m) YTN 사이언스
(\e[32mg\e[0m) 맛있는 녀석들" # (\e[32mr\e[0m) RTV 시민방송

read -p " " i

case $i in
 j) ch=jtbcnews    ; url="https://www.youtube.com/user/JTBC10news"                  ;;
 k) ch=kbsnews     ; url="https://www.youtube.com/user/NewsKBS"                     ;;
 m) ch=mbcnews     ; url="https://www.youtube.com/channel/UCF4Wxdo3inmxP-Y59wXDsFw" ;;
 s) ch=sbsnews     ; url="https://www.youtube.com/channel/UCkinYTS9IHqOEwR1Sze2JTw" ;;
 t) ch=tbs         ; url="https://www.youtube.com/user/seoultbstv/featured"         ;;
 y) ch=yonhap      ; url="https://www.youtube.com/channel/UCTHCOPwqNfZ0uiKOvFyhGwg" ;;
 v) ch=ytn         ; url="https://www.youtube.com/user/ytnnews24"                   ;;
 f) ch=ytn_life    ; url="https://www.youtube.com/channel/UCDww6ExpwQS0TzmREIOo40Q" ;;
 c) ch=ytn_science ; url="https://www.youtube.com/user/ytnscience"                  ;;
 r) ch=rtv         ; url="https://www.youtube.com/channel/UCvogIa1elSl9iwF4MbRXmAQ" ;;
 g) ch=tastyguys   ; url="https://www.youtube.com/channel/UCsOW9TPy2TKkqCchUHL04Fg" ;;
 *) exit ;;
esac

uturl=$(curl -s "$url" | grep '실시간 스트리밍 중' | grep -o '"videoId":"[0-9A-Za-z_-]*"' | head -1 | cut -d\" -f4)

[ -z "$uturl" ] && printf "YouTube live streaming is not available!\n\e[34m$url\e[0m\n" && exit

if [ "$i" = g ]; then
 label=$(curl -s "$url" | grep -o '"label":.*' | cut -c -300 | sed 's/\\"//g' | cut -d\" -f4)
 [ -z "$label" ] && printf "\e[32m정보 없음\e[0m\n\e[36mhttps://youtu.be/$uturl\e[0m\n" && exit
 days=$(echo "$label" | sed 's/.*) //; s/ 조회수.*//')
 prog=$(echo "$label" | sed 's/ \[맛있는.*//')
 printf "\e[32m$prog ($days)\e[0m\n"
fi

 printf "\e[34m$url\e[0m\n$ch - https://youtu.be/$uturl\n"
#printf "\e[34m$url\e[0m\n$ch - plugin://plugin.video.youtube/play/?video_id=$uturl\n"

printf "#EXTM3U\n#EXTINF:-1,$(echo "$ch" | tr a-z A-Z)\nhttps://youtu.be/$uturl\n" > /home/parkmino/Videos/$ch.m3u
