#!/bin/sh
#youtube-dl -f 'best[width<=2048][height<=2048]' -o '/home/parkmino/Downloads/%(title)s-%(id)s.%(ext)s' --external-downloader aria2c "$@"
youtube-dl -f 'bestvideo[width<=2048][height<=2048]+bestaudio/best[width<=2048][height<=2048]' -o '/home/parkmino/Downloads/%(title)s-%(id)s.%(ext)s' --external-downloader aria2c "$@"