#!/bin/sh

echo "\
(1) JTBC 뉴스
(2) KBS 뉴스
(3) tbs TV
(4) 연합뉴스TV
(5) YTN LIVE
(6) YTN 라이프
(7) YTN 사이언스"

read -p " " i

case $i in
 1) ch=jtbc        ; url="https://www.youtube.com/user/JTBC10news"                  ;;
 2) ch=kbsnews     ; url="https://www.youtube.com/user/NewsKBS"                     ;;
 3) ch=tbs         ; url="https://www.youtube.com/user/seoultbstv/featured"         ;;
 4) ch=yonhap      ; url="https://www.youtube.com/channel/UCTHCOPwqNfZ0uiKOvFyhGwg" ;;
 5) ch=ytn         ; url="https://www.youtube.com/user/ytnnews24"                   ;;
 6) ch=ytn_life    ; url="https://www.youtube.com/channel/UCDww6ExpwQS0TzmREIOo40Q" ;;
 7) ch=ytn_science ; url="https://www.youtube.com/user/ytnscience"                  ;;
 8) ch=rtv         ; url="https://www.youtube.com/channel/UCvogIa1elSl9iwF4MbRXmAQ" ;;
 *) exit ;;
esac

utube="/home/parkmino/mpvrun"
jtbc_m3u="/home/parkmino/Videos/jtbc.m3u"

echo "You will watch it for 7 seconds"
url=$(curl -s "$url" | grep -m1 -o data-context-item-id.* | cut -d\" -f2)
echo "https://youtu.be/$url"
#echo "https://youtu.be/$url" | xclip -selection c
mpv --length=7 https://youtu.be/$url

if [ "$ch" = jtbc ]; then
 read -p "* Update $ch live? [Y/n]" answer
 if [ "$answer" != n ]; then
 #sed -i '/'"$ch"'=/s/".*"/"https:\/\/youtu.be\/'"$url"'"/' $utube
 #grep $ch= $utube
  sed -i 's/youtu.be.*/youtu.be\/'"$url"'/' $jtbc_m3u && echo "$ch live url was updated as $(tail -1 $jtbc_m3u)"
 else
  echo "$ch live was not updated"
 fi
fi
