#!/bin/sh

echo 'Input number to find youtube or any other key to quit
(1) JTBC 뉴스
(2) KBS 뉴스
(3) tbs TV
(4) 연합뉴스TV
(5) YTN LIVE
(6) YTN 라이프
(7) YTN 사이언스' # (8) RTV 시민방송
read -p "*" i
case $i in
 1) ch=jtbc        ; query="\[LIVE%2FJTBC+뉴스\]+$(date +%_m)월+$(date +%_d)일" ;;
 2) ch=kbs_news    ; query="대한민국의+오늘+KBS뉴스" ;;
 3) ch=tbs         ; query="tbs+tv+live+실시간" ;;
 4) ch=yonhap      ; query="연합뉴스TV+생방송" ;;
 5) ch=ytn         ; query="ytn실시간" ;;
 6) ch=ytn_life    ; query="ytn+라이프+HD+생방송" ;;
 7) ch=ytn_science ; query="ytn+science+live" ;;
 8) ch=rtv         ; query="RTV+시민방송님의+실시간+스트리밍" ;;
 *) exit ;;
esac

utube="/home/parkmino/mpvrun"
mkm3u="/home/parkmino/mkm3u"
jtbc_m3u="/home/parkmino/Videos/jtbc.m3u"

echo "You will watch it for 7 secs to check!"
url=$(curl -s "https://www.youtube.com/results?search_query=$query" | grep data-context-item-id | sed 's/.*data-context-item-id="//' | cut -d\" -f1 | head -1)
echo "https://youtu.be/$url"
#echo "https://youtu.be/$url" | xclip -selection c
mpv --length=7 https://youtu.be/$url

read -p "* $ch live is correct? [Y/n]" answer
if [ "$answer" != n ]; then
 sed -i '/'"$ch"'=/s/".*"/"https:\/\/youtu.be\/'"$url"'"/' $utube
 grep $ch= $utube
 read -p "* Update mkm3u? [Y/n]" answer
 if [ "$answer" != n ]; then
  $mkm3u
  #grep $ch= $utube
  [ "$ch" = jtbc ] && sed -i 's/youtu.be.*/youtu.be\/'"$url"'/' $jtbc_m3u && echo "JTBC News url is $(tail -1 $jtbc_m3u)"
 fi
else
 echo "$ch live was not updated"
fi
