#!/bin/sh

echo "\
(1) JTBC 뉴스
(2) KBS 뉴스
(3) tbs TV
(4) 연합뉴스TV
(5) YTN LIVE
(6) YTN 라이프
(7) YTN 사이언스" # (8) RTV 시민방송

read -p " " i

case $i in
 1) ch=jtbc        ; url="https://www.youtube.com/user/JTBC10news"                  ;;
 2) ch=kbsnews     ; url="https://www.youtube.com/user/NewsKBS"                     ;;
 3) ch=tbs         ; url="https://www.youtube.com/user/seoultbstv/featured"         ;;
 4) ch=yonhap      ; url="https://www.youtube.com/channel/UCTHCOPwqNfZ0uiKOvFyhGwg" ;;
 5) ch=ytn         ; url="https://www.youtube.com/user/ytnnews24"                   ;;
 6) ch=ytn_life    ; url="https://www.youtube.com/channel/UCDww6ExpwQS0TzmREIOo40Q" ;;
 7) ch=ytn_science ; url="https://www.youtube.com/user/ytnscience"                  ;;
 8) ch=rtv         ; url="https://www.youtube.com/channel/UCvogIa1elSl9iwF4MbRXmAQ" ;;
 *) exit ;;
esac

url=$(curl -s "$url" | grep -m1 -o data-context-item-id.* | cut -d\" -f2)
 [ -n "$url" ] && echo "https://youtu.be/$url"
#[ -n "$url" ] && echo "plugin://plugin.video.youtube/play/?video_id=$url"

if [ "$ch" = jtbc ]; then
 echo "You will watch it for 7 seconds"
 mpv --length=7 https://youtu.be/$url
 read -p "* Update $ch live? [Y/n]" answer
 if [ "$answer" != n ]; then
 #sed -i '/'"$ch"'=/s/[0-9a-zA-Z_-]\{11\}/'"$url"'"/' $utube
 #grep $ch= $utube
  sed -i '$s/[0-9a-zA-Z_-]\{11\}$/'"$url"'/' $jtbc_m3u && echo "$ch live url was updated as $(tail -1 $jtbc_m3u)"
 else
  echo "$ch live was not updated"
 fi
fi