#!/bin/sh

echo "\
(1) JTBC 뉴스
(2) KBS 뉴스
(3) tbs TV
(4) 연합뉴스TV
(5) YTN LIVE
(6) YTN 라이프
(7) YTN 사이언스" # (8) RTV 시민방송

read -p " " i

case $i in
 1) ch=jtbc        ; url="https://www.youtube.com/user/JTBC10news"                  ;;
 2) ch=kbsnews     ; url="https://www.youtube.com/user/NewsKBS"                     ;;
 3) ch=tbs         ; url="https://www.youtube.com/user/seoultbstv/featured"         ;;
 4) ch=yonhap      ; url="https://www.youtube.com/channel/UCTHCOPwqNfZ0uiKOvFyhGwg" ;;
 5) ch=ytn         ; url="https://www.youtube.com/user/ytnnews24"                   ;;
 6) ch=ytn_life    ; url="https://www.youtube.com/channel/UCDww6ExpwQS0TzmREIOo40Q" ;;
 7) ch=ytn_science ; url="https://www.youtube.com/user/ytnscience"                  ;;
 8) ch=rtv         ; url="https://www.youtube.com/channel/UCvogIa1elSl9iwF4MbRXmAQ" ;;
 *) exit ;;
esac

url=$(curl -s "$url" | grep -m1 -o data-context-item-id.* | cut -d\" -f2)
 [ -n "$url" ] && echo "https://youtu.be/$url"
#[ -n "$url" ] && echo "plugin://plugin.video.youtube/play/?video_id=$url"

m3u_dir="/home/parkmino/Videos"

printf "#EXTM3U\n#EXTINF:-1,$(echo "$ch" | tr a-z A-Z)\nhttps://youtu.be/$url\n" > $m3u_dir/$ch.m3u
