#!/bin/sh

sudo hdparm -B255 /dev/sda

m_task=$(($(nproc --all)-1)); h_task=0; s_task=0
[ "$m_task" -ge 3 ] && h_task=$((m_task-1)) && s_task=$((m_task-2))

for i in $(awk '/snd/{print +$1}' /proc/interrupts); do
 proc="/proc/irq/$i/smp_affinity"
 sudo sh -c "echo $(echo "2^$m_task" | bc) > $proc" || true
 echo "$proc = $(cat $proc) ($(awk '$1 ~ /'"$i"'/{print $NF}' /proc/interrupts))"
done

for i in $(awk '/enp3s0|1f.2/{print +$1}' /proc/interrupts); do
 proc="/proc/irq/$i/smp_affinity"
 sudo sh -c "echo $(echo "2^$s_task" | bc) > $proc" || true
 echo "$proc = $(cat $proc) ($(awk '$1 ~ /'"$i"'/{print $NF}' /proc/interrupts))"
done

for i in $(awk '/mei|nvkm|i915|iwlwifi|xhci/{print +$1}' /proc/interrupts); do
 proc="/proc/irq/$i/smp_affinity"
 sudo sh -c "echo $(echo "2^$h_task" | bc) > $proc" || true
 echo "$proc = $(cat $proc) ($(awk '$1 ~ /'"$i"'/{print $NF}' /proc/interrupts))"
done

proc="/proc/irq/default_smp_affinity"
sudo sh -c "echo $(echo "2^$h_task" | bc) > $proc"
echo "$proc = $(cat $proc) ($(echo $proc | cut -d'/' -f4))"

/home/parkmino/pri set

grep ' sysctl.*\| echo.*sys' /etc/rc.local | while read line ; do
 sudo sh -c "$line"
done

for i in $(ls /proc/sys/net/ipv4/conf/*/promote_secondaries | cut -d\/ -f4-); do
 sudo sysctl -w $i=0
done

ls -al /dev/shm/libasound.so* /usr/share/alsa/alsa.conf

for i in /dev/snd/*D[1-9]* /dev/snd/*c /dev/snd/hw* /dev/snd/seq /dev/snd/timer; do # /dev/snd/control*
 [ -f "$i" ] && sudo rm "$i"
done

numlockx off

