#!/bin/sh

sudo hdparm -B255 /dev/sda

m_task=$(($(nproc --all)-1)); h_task=0; s_task=0
[ "$m_task" -ge 3 ] && h_task=$((m_task-1)) && s_task=$((m_task-2))

for i in $(awk '/snd/{print +$1}' /proc/interrupts); do
 proc="/proc/irq/$i/smp_affinity"
 sudo sh -c "echo $(echo "2^$m_task" | bc) > $proc"
 echo "$proc = $(cat $proc) ($(awk '$1 ~ /'"$i"'/{print $NF}' /proc/interrupts))"
done

for i in $(awk '/enp3s0|iwlwifi|1f.2/{print +$1}' /proc/interrupts); do
 proc="/proc/irq/$i/smp_affinity"
 sudo sh -c "echo $(echo "2^$h_task" | bc) > $proc"
 echo "$proc = $(cat $proc) ($(awk '$1 ~ /'"$i"'/{print $NF}' /proc/interrupts))"
done

proc="/proc/irq/default_smp_affinity"
sudo sh -c "echo $(echo "2^$h_task" | bc) > $proc"
echo "$proc = $(cat $proc) ($(echo $proc | cut -d'/' -f4))"

/home/parkmino/pri set

grep -E '( sysctl.*|ln.*libasound|ln.*alsa)' /etc/rc.local | while read line ; do
 sudo $line
done

#sudo ln -sf /dev/shm/libasound.so.2.0.0 /usr/lib/x86_64-linux-gnu/libasound.so.2
ls -al /usr/lib/x86_64-linux-gnu/libasound.so.2 /usr/share/alsa/alsa.conf
numlockx off