#!/bin/bash

audio_conf=/storage/.config/audio.conf
rc_local=/storage/.config/autostart.sh
config_txt=/flash/config.txt

sound_card_initial () {
 mount -o remount,rw /flash
 sed -i '/dtoverlay=allo\|dtoverlay=applepi\|dtoverlay=i-sabre\|dtoverlay=dionaudio\|dtoverlay=hifiberry\|dtoverlay=iqaudio\|dtoverlay=justboom\|dtoverlay=rpi-dac/d' $config_txt
}

sound_card_selector () {
 sound_card_initial
 sudo sed -i '$adtoverlay='"$1"'' $config_txt
 mount -o remount,ro /flash
 grep -e allo -e applepi -e i-sabre -e dionaudio -e hifiberry -e iqaudio -e justboom -e rpi-dac $config_txt
}

sound_card () {
clear
printf "
 ------------------------------
  Sound Card / 사운드카드 설정
 ------------------------------

 (\e[32m0\e[0m)  USB Audio Class 2.0\t\t(\e[32m11\e[0m) HiFiBerry Amp/Amp+
 (\e[32m1\e[0m)  Allo Boss DAC\t\t\t(\e[32m12\e[0m) HiFiBerry DAC
 (\e[32m2\e[0m)  Allo DigiOne\t\t\t(\e[32m13\e[0m) HiFiBerry DAC+ADC
 (\e[32m3\e[0m)  Allo Katana DAC\t\t\t(\e[32m14\e[0m) HifiBerry DAC+ADC Pro
 (\e[32m4\e[0m)  Allo Piano DAC\t\t\t(\e[32m15\e[0m) HiFiBerry DAC+/DAC+ Pro
 (\e[32m5\e[0m)  Allo Piano DAC+\t\t\t(\e[32m16\e[0m) HiFiBerry Digi/Digi+
 (\e[32m6\e[0m)  Allo Piano DAC+ (+Kali board)\t(\e[32m17\e[0m) HiFiBerry Digi+ Pro
 (\e[32m7\e[0m)  ApplePi DAC\t\t\t(\e[32m18\e[0m) IQaudIO DAC
 (\e[32m8\e[0m)  Audiophonics I-SABRE Q2M DAC\t(\e[32m19\e[0m) IQaudIO DAC+
 (\e[32m9\e[0m)  Dion Audio LOCO DAC-AMP\t\t(\e[32m20\e[0m) IQaudIO DigiAMP+
 (\e[32m10\e[0m) Dion Audio LOCO-V2 DAC-AMP\t(\e[32m21\e[0m) IQaudIO Digi+
\t\t\t\t\t(\e[32m22\e[0m) JustBoom DAC
\t\t\t\t\t(\e[32m23\e[0m) JustBoom Digi
\t\t\t\t\t(\e[32m24\e[0m) RPi DAC
 (\e[32mm\e[0m) Main / 주메뉴
 (\e[32mq\e[0m) Quit / 나가기

 * Select / 선택 (\e[32m0-24\e[0m|\e[32mm\e[0m|\e[32mq\e[0m) : "
read i
echo
case $i in
 0)  sound_card_initial ; mount -o remount,ro /flash			;;
 1)  sound_card_selector allo-boss-dac-pcm512x-audio			;;
 2)  sound_card_selector allo-digione					;;
 3)  sound_card_selector allo-katana-dac-audio				;;
 4)  sound_card_selector allo-piano-dac-pcm512x-audio			;;
 5)  sound_card_selector allo-piano-dac-plus-pcm512x-audio		;;
 6)  sound_card_selector allo-piano-dac-plus-pcm512x-audio,glb_mclk	;;
 7)  sound_card_selector applepi-dac					;;
 8)  sound_card_selector i-sabre-q2m					;;
 9)  sound_card_selector dionaudio-loco					;;
 10) sound_card_selector dionaudio-loco-v2				;;
 11) sound_card_selector hifiberry-amp					;;
 12) sound_card_selector hifiberry-dac					;;
 13) sound_card_selector hifiberry-dacplusadc				;;
 14) sound_card_selector hifiberry-dacplusadcpro			;;
 15) sound_card_selector hifiberry-dacplus				;;
 16) sound_card_selector hifiberry-digi					;;
 17) sound_card_selector hifiberry-digi-pro				;;
 18) sound_card_selector iqaudio-dac					;;
 19) sound_card_selector iqaudio-dacplus				;;
 20) sound_card_selector iqaudio-dacplus,unmute_amp			;;
 21) sound_card_selector iqaudio-digi-wm8804-audio			;;
 22) sound_card_selector justboom-dac					;;
 23) sound_card_selector justboom-digi					;;
 24) sound_card_selector rpi-dac					;;
 m) clear ; return ;;
 q) exit ;;
esac
return
}

usb_signal_power () {
clear
echo -ne "
 --------------------------------------
  USB Signal & Power / USB 신호와 전원
 --------------------------------------

              [USB ]      [USB4]
   [LAN]      [USB3]      [USB5]
  =============================== 
  -  RasPi 1B+/2B/3B Back Port        -  라즈베리 파이 1B+/2B/3B 뒷면
  -  USB3 is recommended for DAC      -  DAC은 USB3을 추천합니다

 (\e[32m1\e[0m) Enable  All USB Signal & Power  (\e[32m1\e[0m) 모든 USB 신호와 전원 켜기 (기본값)
 (\e[32m2\e[0m) Disable All USB Signal & Power  (\e[32m2\e[0m) 모든 USB 신호와 전원 끄기 (I2S DAC)
 (\e[32m3\e[0m) Disable USB 4,5 Signal          (\e[32m3\e[0m) USB 4,5 신호만 끄기
 (\e[32m4\e[0m) Disable USB 4,5 Signal & Power  (\e[32m4\e[0m) USB 4,5 신호와 전원 끄기
    (for Powered USB DAC)               (자체 전원 USB DAC)

 (\e[32mm\e[0m) Main                            (\e[32mm\e[0m) 주메뉴
 (\e[32mq\e[0m) Quit                            (\e[32mq\e[0m) 나가기

 * Select / 선택 (\e[32m1-4\e[0m|\e[32mm\e[0m|\e[32mq\e[0m) : "
read i
echo
case $i in
 1) sed -i '/usb=/s/=.*/=on/'      $audio_conf ;;
 2) sed -i '/usb=/s/=.*/=2,3,4,5/' $audio_conf ;;
 3) sed -i '/usb=/s/=.*/=4,5/'     $audio_conf ;;
 4) sed -i '/usb=/s/=.*/=2,4,5/'   $audio_conf ;;
 m) clear ; return ;;
 q) exit ;;
esac
return
}

until [ "$i" == "q" ] ; do
 for i in lirc nfs pulse vpn wpa tweak; do
  eval status_$i="$(grep ^$i= $audio_conf | cut -d= -f2)"
 done
 clear
 echo -ne "
 ---------------------------------
  Audio Main Menu / 오디오 주메뉴
 ---------------------------------

 (\e[32m1\e[0m) Audio Device	      (\e[32m1\e[0m) 오디오 장치
 (\e[32m2\e[0m) USB Signal & Power >>    (\e[32m2\e[0m) USB 신호와 전원 >>

 (\e[32m3\e[0m) [ $(if [ "$status_lirc"  = off ]; then echo "\e[33mX\e[0m"; elif [ "$status_lirc"  = on ]; then echo "\e[33mO\e[0m"; else echo "\e[33mNA\e[0m"; fi) ] LIRC
 (\e[32m4\e[0m) [ $([ "$status_nfs"   = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] NFS
 (\e[32m5\e[0m) [ $([ "$status_pulse" = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] Pulseaudio
 (\e[32m6\e[0m) [ $([ "$status_vpn"   = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] VPN
 (\e[32m7\e[0m) [ $([ "$status_wpa"   = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] Wi-Fi

 (\e[32m8\e[0m) [ $([ "$status_tweak" = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] More Tweaks / 추가 트윅

 (\e[32mq\e[0m) Quit                     (\e[32mq\e[0m) 나가기
 (\e[32mr\e[0m) Reboot to apply          (\e[32mr\e[0m) 재시작하여 적용
 (\e[32mp\e[0m) Power off                (\e[32mp\e[0m) 전원 끄기

 * Select / 선택 (\e[32m0-8\e[0m|\e[32mq\e[0m|\e[32mr\e[0m|\e[32mp\e[0m) : "
 read i
 echo
 case $i in
  1) sound_card ;;
  2) usb_signal_power	;;
  3) if [ $status_lirc = off ]; then
      sed -i '/lirc=/s/=.*/=on/'   $audio_conf
     else
      sed -i '/lirc=/s/=.*/=off/'  $audio_conf
     fi ;;
  4) if [ $status_nfs = off ]; then
      sed -i '/nfs=/s/=.*/=on/'    $audio_conf
     else
      sed -i '/nfs=/s/=.*/=off/'   $audio_conf
     fi ;;
  5) if [ $status_pulse = off ]; then
      sed -i '/pulse=/s/=.*/=on/'  $audio_conf
     else
      sed -i '/pulse=/s/=.*/=off/' $audio_conf
     fi ;;
  6) if [ $status_vpn = off ]; then
      sed -i '/vpn=/s/=.*/=on/'    $audio_conf
     else
      sed -i '/vpn=/s/=.*/=off/'   $audio_conf
     fi ;;
  7) if [ $status_wpa = off ]; then
      sed -i '/wpa=/s/=.*/=on/'    $audio_conf
     else
      sed -i '/wpa=/s/=.*/=off/'   $audio_conf
     fi ;;
  8) if [ $status_tweak = off ]; then
      sed -i '/tweak=/s/=.*/=on/'  $audio_conf
     else
      sed -i '/tweak=/s/=.*/=off/' $audio_conf
     fi ;;
  q) exit		;;
  r) reboot   && exit	;;
  p) poweroff && exit	;;
  *) clear		;;
 esac
done
