#!/bin/sh

# Audio patch

if [ ! -e /storage/.config/audio_patched ] && [ -d /storage/.config/ ] && [ -d /storage/.config/modprobe.d/ ] && [ -d /storage/.config/sysctl.d/ ]; then
 echo -en "\033[?25l"
 if [ -f /sys/devices/virtual/graphics/fbcon/cursor_blink ] ; then
  echo 0 > /sys/devices/virtual/graphics/fbcon/cursor_blink
 fi
 echo "Audio tunings will be applied and reboot..."
 printf 'blacklist bcm2835_gpiomem\nblacklist fixed' > /storage/.config/modprobe.d/libreelec-blacklist.conf
 cp /etc/sysctl.conf /storage/.config/sysctl.d/
 cp /etc/audio.conf /etc/autostart.sh /storage/.config/
 cp /etc/plugin.*.zip /storage/backup/
 cp /etc/advancedsettings.xml /storage/.kodi/userdata/
 touch /storage/.config/audio_patched
 sync
 sleep 1
 reboot --reboot
fi
