#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") mpd [dop|pcm|vol|sta|tag] [on|off]"
 echo "   or: $(basename "$0") upmpd [set]"
 echo "   or: $(basename "$0") upnp|lms|sqzlite|roonbridge|roonserver [on|off]"
 echo "   or: $(basename "$0") build"
 echo "Consult and configure UPnP/MPD and other features"
}

audio_conf=/etc/default/audio.conf
[ -e /etc/mpd.conf.sav ] && mpd_conf=/etc/mpd.conf.sav || mpd_conf=/etc/mpd.conf
[ -e /etc/upmpdcli.conf.sav ] && upmpdcli_conf=/etc/upmpdcli.conf.sav || upmpdcli_conf=/etc/upmpdcli.conf

case "$1:$2:$3" in
 upnp:on:*)     	sed  -i '/upnp=/s/=.*/=on/'  $audio_conf ;;
 upnp:off:*)    	sed  -i '/upnp=/s/=.*/=off/' $audio_conf ;;
 upnp:*)        	grep ^upnp= $audio_conf | cut -d= -f2 ;;
 mpd:dop:on)    	sed  -i '/dop/s/^#*//g' $mpd_conf ;;
 mpd:dop:off)   	sed  -i '/dop/s/^/#/g'  $mpd_conf ;;
 mpd:dop:*)     	grep -q '^dop' $mpd_conf && echo on || echo off ;;
 mpd:pcm:on)    	sed  -i '/plugin.*pcm/!b;n;s/".*"/"yes"/' $mpd_conf ;;
 mpd:pcm:off)   	sed  -i '/plugin.*pcm/!b;n;s/".*"/"no"/'  $mpd_conf ;;
 mpd:pcm:*)     	grep -A1 'plugin.*pcm' $mpd_conf | grep -q yes - && echo on || echo off ;;
 mpd:vol:on)    	sed  -i '/mixer_type/s/"none"/"software"/g' $mpd_conf ;;
 mpd:vol:off)   	sed  -i '/mixer_type/s/"software"/"none"/g' $mpd_conf ;;
 mpd:vol:*)     	grep -q 'mixer_type.*software' $mpd_conf && echo on || echo off ;;
 mpd:sta:on)    	sed  -i '/state_file/s/^#*//' $mpd_conf ;;
 mpd:sta:off)   	sed  -i '/state_file/s/^/#/'  $mpd_conf ;;
 mpd:sta:*)     	grep -q '^state_file' $mpd_conf && echo on || echo off ;;
 mpd:tag:on)    	sed  -i '/metadata.*none/s/^/#/'  $mpd_conf ;;
 mpd:tag:off)   	sed  -i '/metadata.*none/s/^#*//' $mpd_conf ;;
 mpd:tag:*)     	grep -q '^metadata.*none' $mpd_conf && echo off || echo on ;;
 upmpd:set:*)   	shift; shift
                	sed  -i 's/^#*friendlyname.*/friendlyname = '"$@"'/' $upmpdcli_conf ;;
 upmpd:*)       	grep ^#*friendlyname $upmpdcli_conf | cut -d ' ' -f3- ;;
 lms:on:*)  		sed  -i '/lms=/s/=.*/=on/'  $audio_conf ;;
 lms:off:*) 		sed  -i '/lms=/s/=.*/=off/' $audio_conf ;;
 lms:*)     		grep ^lms= $audio_conf | cut -d= -f2 ;;
 sqzlite:on:*)  	sed  -i '/sqzlite=/s/=.*/=on/'  $audio_conf ;;
 sqzlite:off:*) 	sed  -i '/sqzlite=/s/=.*/=off/' $audio_conf ;;
 sqzlite:*)     	grep ^sqzlite= $audio_conf | cut -d= -f2 ;;
 roonbridge:on:*)	sed  -i '/roonbridge=/s/=.*/=on/'  $audio_conf ;;
 roonbridge:off:*)	sed  -i '/roonbridge=/s/=.*/=off/' $audio_conf ;;
 roonbridge:*)		grep ^roonbridge= $audio_conf | cut -d= -f2 ;;
 roonserver:on:*)	sed  -i '/roonserver=/s/=.*/=on/'  $audio_conf ;;
 roonserver:off:*)	sed  -i '/roonserver=/s/=.*/=off/' $audio_conf ;;
 roonserver:*)		grep ^roonserver= $audio_conf | cut -d= -f2 ;;
 airplay:on:*)		sed -i '/airplay=/s/=.*/=on/'  $audio_conf ;;
 airplay:off:*)		sed -i '/airplay=/s/=.*/=off/' $audio_conf ;;
 airplay:*)		grep ^airplay= $audio_conf | cut -d= -f2 ;;
 librespot:on:*)	sed -i '/librespot=/s/=.*/=on/'  $audio_conf ;;
 librespot:off:*)	sed -i '/librespot=/s/=.*/=off/' $audio_conf ;;
 librespot:*)		grep ^spotify= $audio_conf | cut -d= -f2 ;;
 build:*)		grep -o [0-9].* /etc/release ;;
 *)			usage ;;
esac
