#!/bin/bash

[ -e /etc/mpd.conf.sav ] && mpd_conf=/etc/mpd.conf.sav || mpd_conf=/etc/mpd.conf
[ -e /etc/upmpdcli.conf.sav ] && upmpdcli_conf=/etc/upmpdcli.conf.sav || upmpdcli_conf=/etc/upmpdcli.conf
audio_conf=/etc/default/audio.conf

ethernet_ip () {
i=$(whiptail --title "Ethernet IP / 유선 IP 설정" --menu "Ethernet IP / 유선 IP 설정" --ok-button "Select/선택" --cancel-button "Back/이전" --backtitle "Bann Audio Sylphid Network Player" 9 45 2 \
"1" "Dynamic IP (DHCP)       자동 IP" \
"2" "Static  IP              수동 IP   >" 3>&1 1>&2 2>&3)

[ -n "$(which connmanctl)" ] && eth=$(connmanctl services | grep -om1 ethernet.*)

case $i in
 1) sudo connmanctl config $eth --ipv4 dhcp ;;
 2) user_ip=$(whiptail --title "Ethernet IP / 유선 IP 설정" --inputbox "\

Input Static IP address to use.       사용할 수동 IP를 입력합니다.
Current IP is listed below.           아래는 현재 주소입니다.
Otherwise, 192.168.0.9 will be used.  아니면 192.168.0.9로 설정합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Bann Audio Sylphid Network Player" 11 75 $(hostname -I) 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     if [ -z "$user_ip" ]; then
      ip_1st=$(echo "$(hostname -I)" | cut -d "." -f1)
      ip_2nd=$(echo "$(hostname -I)" | cut -d "." -f2)
      ip_3rd=$(echo "$(hostname -I)" | cut -d "." -f3)
      ip_4th=$(echo "$(hostname -I)" | cut -d "." -f4)
     else
      ip_1st=$(echo "$user_ip" | cut -d "." -f1)
      ip_2nd=$(echo "$user_ip" | cut -d "." -f2)
      ip_3rd=$(echo "$user_ip" | cut -d "." -f3)
      ip_4th=$(echo "$user_ip" | cut -d "." -f4)
     fi
     if [ "$ip_1st" -ge "1" ] 2>/dev/null && [ "$ip_1st" -le "254" ] 2>/dev/null && [ "$ip_1st" -ne "127" ] 2>/dev/null && [ "$ip_2nd" -ge "0" ] 2>/dev/null && [ "$ip_2nd" -le "255" ] 2>/dev/null && [ "$ip_3rd" -ge "0" ] 2>/dev/null && [ "$ip_3rd" -le "255" ] 2>/dev/null && [ "$ip_4th" -ge "2" ] 2>/dev/null && [ "$ip_4th" -le "254" ] 2>/dev/null ; then
      ip=$ip_1st.$ip_2nd.$ip_3rd
      ip_all=$ip_1st.$ip_2nd.$ip_3rd.$ip_4th
     else
      ip=192.168.0
      ip_all=192.168.0.9
     fi
     sudo connmanctl config $eth --ipv4 manual $ip_all 255.255.255.0 $ip.1
     sudo systemctl disable dhcpcd.service
    fi ;;
esac
}

wifi_client () {
i=$(whiptail --title "Wi-Fi Client / 무선 연결" --menu "Wi-Fi Client / 무선 연결" --ok-button "Select/선택" --cancel-button "Back/이전" --backtitle "Bann Audio Sylphid Network Player" 9 50 2 \
"1" "Enable  Wi-Fi       무선 연결        >" \
"2" "Disable Wi-Fi       무선 연결 안 함" 3>&1 1>&2 2>&3)
#"0" "Scan    Wi-Fi       무선 검색" \

[ -n "$(which connmanctl)" ] && eth=$(connmanctl services | grep -om1 ethernet.*)

case $i in
 0) wpa_cli -iwlan0 scan && echo "$(wpa_cli scan_results)" > ~/scan_wifi.txt
    whiptail --title "Scan Wi-Fi / 무선 검색" --scrolltext --textbox ~/scan_wifi.txt --ok-button "OK/확인" --backtitle "Bann Audio Sylphid Network Player" 18 75 ;;
 1) wifi=$(whiptail --title "Wi-Fi Client / 무선 연결" --inputbox "\

Input AP and password to use.   공유기와 비밀번호를 입력합니다.
Use space in between.           사이에 빈 칸을 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Bann Audio Sylphid Network Player" 11 67 "AP password" 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     ap=$(echo "$wifi" | cut -d " " -f1)
     pass=$(echo "$wifi" | rev | cut -d " " -f1 | rev)
    fi
    if [ -n "$ap" ] && [ -n "$pass" ]; then
     sudo wpa_passphrase $ap $pass >> /etc/wpa_supplicant/wpa_supplicant.conf
     sudo systemctl unmask wpa_supplicant
     sudo systemctl start  wlan_dhcp
     sudo systemctl start  wpa_supplicant
     sudo systemctl enable wlan_dhcp
     sudo systemctl enable wpa_supplicant
     sudo dhclient wlan0
    fi ;;
 2) sudo sed -i '/^network={/,$d' /etc/wpa_supplicant/wpa_supplicant.conf
    sudo systemctl disable wpa_supplicant
    sudo systemctl disable wlan_dhcp
    sudo systemctl mask    wpa_supplicant ;;
esac
}

mpd_options () {
i=$(whiptail --title "MPD options / MPD 옵션" --checklist "MPD options / MPD 옵션" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "audio-config" 11 67 5 \
"dop" "Enable DoP (DSD over PCM)   DoP 사용"              $(consf mpd dop) \
"pcm" "Enable PCM Decoder          PCM 디코더 사용"       $(consf mpd pcm) \
"vol" "Enable Software Volume      소프트웨어 볼륨 사용" $(consf mpd vol) \
"sta" "Enable State File           상태 파일 사용"       $(consf mpd sta) \
"tag" "Enable Tag Metadata         태그 메타데이터 사용" $(consf mpd tag) 3>&1 1>&2 2>&3)

exitstatus=$?
if [ "$exitstatus" = 0 ]; then
 [[ $i =~ dop ]] && consf mpd dop on || consf mpd dop off
 [[ $i =~ pcm ]] && consf mpd pcm on || consf mpd pcm off
 [[ $i =~ vol ]] && consf mpd vol on || consf mpd vol off
 [[ $i =~ sta ]] && consf mpd sta on || consf mpd sta off
 [[ $i =~ tag ]] && consf mpd tag on || consf mpd tag off
fi
}

renderer_name () {
 current_name="$(consf upmpd)"
 i="$(whiptail --title "Change renderer name / 렌더러 이름 바꾸기" --inputbox "\

Input renderer name to change.   바꿀 렌더러 이름을 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "audio-config" 9 67 "$current_name" 3>&1 1>&2 2>&3)"
 [ "$i" != "$current_name" ] && [ "$i" != "" ] && consf upmpd set "$i"
}

features () {
i=$(whiptail --title "Roon Bridge, Squeezebox, UPnP/DLNA" --checklist "Roon Bridge, Squeezebox, UPnP/DLNA" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "audio-config" 9 59 3 \
"roon"    "Enable Roon Bridge   룬 브리지  사용" $(consf roon) \
"sqzlite" "Enable Squeezebox    스퀴즈박스 사용" $(consf sqzlite) \
"upnp"    "Enable UPnP/DLNA     UPnP/DLNA  사용" $(consf upnp) 3>&1 1>&2 2>&3)

exitstatus=$?
if [ "$exitstatus" = 0 ]; then
 [[ $i =~ roon    ]] && consf roon    on || consf roon    off
 [[ $i =~ sqzlite ]] && consf sqzlite on || consf sqzlite off
 [[ $i =~ upnp    ]] && consf upnp    on || consf upnp    off
fi
}

while true; do
 i=$(whiptail --title "audio-config / 오디오 설정" --menu "audio-config / 오디오 설정" --ok-button "Select/선택" --cancel-button "Finish/마침" --backtitle "Bann Audio Sylphid Network Player" 10 61 3 \
"1" "MPD options              MPD 옵션               >" \
"2" "Change renderer name     렌더러 이름 바꾸기     >" \
"3" "Roon Bridge, Squeezebox, UPnP/DLNA              >" 3>&1 1>&2 2>&3)

 exitstatus=$?
 [ "$exitstatus" != 0 ] && break

 case $i in
  e) ethernet_ip ;;
  w) wifi_client ;;
  1) mpd_options ;;
  2) renderer_name ;;
  3) features ;;
 esac
done

if (whiptail --title "Reboot / 다시 시작" --backtitle "Bann Audio Sylphid Network Player" --yes-button "Yes/예" --no-button "No/아니오" --yesno "  To take effect,         바뀐 설정을 적용하려면,
  reboot is necessary.    다시 시작해야 합니다.

  Reboot this system?     시스템을 다시 시작할까요?" 10 57); then
 sudo reboot
fi
