#!/bin/sh

renderer_name () {

 clear
 echo -n "
 --------------------------------------------
  Change Renderer Name / 렌더러 이름 바꾸기
 --------------------------------------------


 [ \e[33m"$current_name"\e[0m ] Renderer Name / 렌더러 이름


 (m) Main / 주메뉴
 (q) Quit / 나가기

  * Input / 입력 (name|m|q) : "
 read i
 echo
 case $i in
  m) clear ; return ;;
  q) exit ;;
  *) consf upmpd set "$i" ;;
 esac
 return
}

until [ "$i" = "q" ] ; do

 current_name=$(consf upmpd)

 for i in dop pcm vol sta tag; do
  eval status_$i="$(consf mpd $i)"
 done

 for i in airplay roon spotify sqzlite; do
  eval status_$i="$(consf $i)"
 done

 clear
 echo -n "
 -----------------------------------
  Audio Configuration / 오디오 설정
 -----------------------------------

 (\e[32m1\e[0m) [ $([ "$status_dop"     = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] MPD DoP (DSD over PCM)
 (\e[32m2\e[0m) [ $([ "$status_pcm"     = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] MPD PCM Decoder
 (\e[32m3\e[0m) [ $([ "$status_vol"     = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] MPD Software Volume
 (\e[32m4\e[0m) [ $([ "$status_sta"     = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] MPD State File
 (\e[32m5\e[0m) [ $([ "$status_tag"     = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] MPD Tag Metadata

 (\e[32m6\e[0m) [ $([ "$status_roon"    = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] Roon Bridge
 (\e[32m7\e[0m) [ $([ "$status_sqzlite" = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] Squeezebox
 (\e[32m8\e[0m) [ $([ "$status_upnp"    = off ] && echo "\e[33mX\e[0m" || echo "\e[33mO\e[0m") ] UPnP/DLNA

 (\e[32mn\e[0m) [ \e[33m"$current_name"\e[0m ] Renderer Name / 렌더러 이름 >>

 (\e[32mq\e[0m) Quit   / 나가기
 (\e[32mr\e[0m) Reboot / 재시작하여 적용

  *  Select / 선택 (\e[32m1-9\e[0m|\e[32mn\e[0m|\e[32mq\e[0m|\e[32mr\e[0m) : "
 read i
 echo
 case $i in
  1) [ $status_dop     = off ] && consf mpd dop on || consf mpd dop off ;;
  2) [ $status_pcm     = off ] && consf mpd pcm on || consf mpd pcm off ;;
  3) [ $status_vol     = off ] && consf mpd vol on || consf mpd vol off ;;
  4) [ $status_sta     = off ] && consf mpd sta on || consf mpd sta off ;;
  5) [ $status_tag     = off ] && consf mpd tag on || consf mpd tag off ;;
  6) [ $status_roon    = off ] && consf roon    on || consf roon    off ;;
  7) [ $status_sqzlite = off ] && consf sqzlite on || consf sqzlite off ;;
  8) [ $status_upnp    = off ] && consf upnp    on || consf upnp    off ;;
  n) renderer_name ;;
  q) exit          ;;
  r) sudo reboot   ;;
  *) clear         ;;
 esac
done
