#!/bin/sh

arch=armv7hf

sudo mv /opt/RoonBridge/Bridge/RoonBridge /opt/RoonBridge/Bridge/RoonBridge.tweak

#[ ! -d /home/pi ] && mkdir /home/pi
wget -O /home/pi/RoonBridge_linux$arch.tar.bz2 http://download.roonlabs.com/builds/RoonBridge_linux$arch.tar.bz2
sudo systemctl stop roonbridge roonbridgetoram
sudo tar -xvf /root/copy/RoonBridge_linux$arch.tar.bz2 -C /opt/
sudo strip --strip-debug /opt/RoonBridge/Bridge/processreaper
find /opt/RoonBridge/ -name *.so -exec sudo chmod -x {} \; -exec sudo strip --strip-debug {} 2>/dev/null \;

sudo mv /opt/RoonBridge/Bridge/RoonBridge       /opt/RoonBridge/Bridge/RoonBridge.orig
sudo mv /opt/RoonBridge/Bridge/RoonBridge.tweak /opt/RoonBridge/Bridge/RoonBridge

sync
cat /opt/RoonBridge/VERSION

printf "\n* Finished and reboot to take effect. \n* 완료되어 시스템을 다시 시작하면 적용됩니다. (^_^)\n"
