#!/bin/sh

 host=127.0.0.1
#host=192.168.0.3

usage () {
 echo "Usage: $(basename "$0") YouTube_URL"
}

[ -z "$1" ] && usage && exit

if yt-dlp -qs "$1" ; then
 next=$(($(mpc -h $host playlist | wc -l)+1))
 mpc -h $host add $(yt-dlp -f bestaudio/best -g "$1") && mpc -h $host play $next
else
 echo "* The requested YouTube URL is not correct or supported!"
fi
