#!/bin/sh

usage () {
 echo "Usage: $(basename "$0") YouTube_URL"
}

[ -z "$1" ] && usage && exit

if youtube-dl -qs "$1" ; then
 next=$(($(mpc playlist | wc -l)+1))
 mpc add  $(youtube-dl -f bestaudio/best -g "$1") && mpc play $next
else
 echo "* The requested YouTube URL is not correct or supported!"
fi
