#!/bin/sh
remountrw
#chmod -R -w /lib/modules/*/kernel/sound/
sed -i 's/9995%/9992799689968994%/' /etc/mpd.conf.sav
sed -i '/wakeup_granularity_ns/s/= .*/= 388306/; /sched_latency_ns/s/= .*/= 1394017/' /etc/sysctl.conf
chmod +w /sbin/init /etc/init.d/rc /lib/startpar/startpar /etc/rc.local /bin/bash /usr/share/alsa/alsa.conf.sav /usr/lib/i386-linux-gnu/libasound.so.2.0.0.sav /usr/bin/mpd /etc/mpd.conf.sav /usr/bin/upmpdcli /etc/upmpdcli.conf
chmod -R +w /usr/lib/i386-linux-gnu/ /lib/modules/*/kernel/sound/
printf 'pcm.0{type hw,card 1,device 0,subdevice  0}' > /usr/share/alsa/alsa.conf.sav