#!/bin/bash

sound_card_initial () {
 sudo sed -i '/dtoverlay=allo\|dtoverlay=hifiberry\|dtoverlay=iqaudio/d' /boot/config.txt
}

sound_card_show () {
 grep -e allo -e hifiberry -e iqaudio /boot/config.txt
 echo
}

sound_card_intaudio () {
 sudo sed -i '/card/s/[1-9]/0/g'  /usr/share/alsa/alsa.conf
 grep card /usr/share/alsa/alsa.conf
}

sound_card_usbaudio () {
 sudo sed -i '/card/s/[02-9]/1/g' /usr/share/alsa/alsa.conf
 grep card /usr/share/alsa/alsa.conf
}

iqaudio () {
 i=$(whiptail --title "IQaudIO Mute / IQaudIO 음소거" --menu "Choose/선택" --ok-button "OK/확인" --cancel-button "Cancel/나가기" --backtitle "Audio-config" 10 67 2 \
"u" "Unmute IQaudIO  IQaudIO 음소거 제거" \
"m" "Mute   IQaudIO  IQaudIO 음소거" 3>&1 1>&2 2>&3)

case $i in
 u) sudo sed -i '/\/sys\/class\/gpio/s/^#*//g'        /etc/rc.local
    grep /sys/class/gpio /etc/rc.local ;;
 m) sudo sed -i '/\/sys\/class\/gpio/s/^echo/#echo/g' /etc/rc.local
    grep /sys/class/gpio /etc/rc.local ;;
esac
}

sound_card () {
i=$(whiptail --title "Sound Card / 사운드카드 설정" --menu "Choose/선택" --ok-button "OK/확인" --cancel-button "Cancel/나가기" --backtitle "Audio-config" 19 55 11 \
"1"  "USB Audio Class 2.0" \
"2"  "Allo Piano DAC" \
"3"  "HiFiBerry Amp/Amp+" \
"4"  "HiFiBerry DAC" \
"5"  "HiFiBerry DAC+/DAC+ Pro" \
"6"  "HiFiBerry DAC+ Pro (Slave mode/종속 모드)" \
"7"  "HiFiBerry Digi/Digi+" \
"8"  "HiFiBerry Digi+ Pro" \
"9"  "IQaudIO DAC" \
"10" "IQaudIO DAC+" \
"11" "IQaudIO Digi+" 3>&1 1>&2 2>&3)

case $i in
 1)  sound_card_initial
     sound_card_show
     #sound_card_usbaudio
     ;;
 2)  sound_card_initial
     sudo sed -i '$adtoverlay=allo-piano-dac-pcm512x-audio' /boot/config.txt
     sound_card_show
     #sound_card_intaudio
     ;;
 3)  sound_card_initial
     sudo sed -i '$adtoverlay=hifiberry-amp' /boot/config.txt
     sound_card_show
     #sound_card_intaudio
     ;;
 4)  sound_card_initial
     sudo sed -i '$adtoverlay=hifiberry-dac' /boot/config.txt
     sound_card_show
     #sound_card_intaudio
     ;;
 5)  sound_card_initial
     sudo sed -i '$adtoverlay=hifiberry-dacplus' /boot/config.txt
     sound_card_show
     #sound_card_intaudio
     ;;
 6)  sound_card_initial
     sudo sed -i '$adtoverlay=hifiberry-dacplus,slave' /boot/config.txt
     sound_card_show
     #sound_card_intaudio
     ;;
 7)  sound_card_initial
     sudo sed -i '$adtoverlay=hifiberry-digi' /boot/config.txt
     sound_card_show
     #sound_card_intaudio
     ;;
 8)  sound_card_initial
     sudo sed -i '$adtoverlay=hifiberry-digi-pro' /boot/config.txt
     sound_card_show
     #sound_card_intaudio
     ;;
 9)  sound_card_initial
     sudo sed -i '$adtoverlay=iqaudio-dac' /boot/config.txt
     sound_card_show
     #sound_card_intaudio
     iqaudio
     ;;
 10) sound_card_initial
     sudo sed -i '$adtoverlay=iqaudio-dacplus' /boot/config.txt
     sound_card_show
     #sound_card_intaudio
     iqaudio
     ;;
 11) sound_card_initial
     sudo sed -i '$adtoverlay=iqaudio-digi-wm8804-audio' /boot/config.txt
     sound_card_show
     #sound_card_intaudio
     iqaudio
     ;;
esac
main
}

usb_signal_power () {
i=$(whiptail --title "USB Signal & Power / USB 신호와 전원" --menu "Choose/선택\n             {USB } {USB4}\n       {LAN} {USB3} {USB5}\n      =====================[Back Port/뒷면]\n      USB3 is recommended for DAC/DAC은 USB3을 추천합니다" --ok-button "OK/확인" --cancel-button "Cancel/나가기" --backtitle "Audio-config" 16 67 4 \
"1" "Enable  All USB Signal & Power   모든 USB 신호와 전원 켜기" \
"2" "Disable All USB Signal & Power   모든 USB 신호와 전원 끄기" \
"3" "Disable USB 4/5 Signal           USB 4/5 신호만 끄기" \
"4" "Disable USB 4/5 Signal & Power   USB 4/5 신호와 전원 끄기" 3>&1 1>&2 2>&3)

case $i in
 1) sudo sed -i '/hub-ctrl -h 0 -P [2-5]/s/^/#/g'   /etc/rc.local
    grep hub-ctrl /etc/rc.local ;;
 2) sudo sed -i '/hub-ctrl -h 0 -P [2-5]/s/^#*//g'  /etc/rc.local
    grep hub-ctrl /etc/rc.local ;;
 3) sudo sed -i '/hub-ctrl -h 0 -P [4-5]/s/^#*//g'  /etc/rc.local
    sudo sed -i '/hub-ctrl -h 0 -P [2-3]/s/^/#/g'   /etc/rc.local
    grep hub-ctrl /etc/rc.local ;;
 4) sudo sed -i '/hub-ctrl -h 0 -P [24-5]/s/^#*//g' /etc/rc.local
    sudo sed -i '/hub-ctrl -h 0 -P 3/s/^/#/g'       /etc/rc.local
    grep hub-ctrl /etc/rc.local ;;
esac
main
}

static_ip () {
i=$(whiptail --title "Static IP / 수동 IP" --menu "Choose/선택" --ok-button "OK/확인" --cancel-button "Cancel/나가기" --backtitle "Audio-config" 10 45 2 \
"d" "Dynamic IP (DHCP)   자동 IP (DHCP)" \
"s" "Static  IP          수동 IP" 3>&1 1>&2 2>&3)

case $i in
 d) sudo sed -i '/iface eth0 inet manual/s/^#*//' /etc/network/interfaces
    sudo sed -i '/iface eth0 inet static/,+6d'    /etc/network/interfaces
    cat /etc/network/interfaces
    sudo systemctl enable dhcpcd.service ;;
 s) user_ip=$(whiptail --title "Static IP / 수동 IP" --inputbox "Input Static IP address to use      사용할 수동 IP를 입력합니다.\nEnter will use the current IP       엔터는 현재 주소를 사용합니다.\nOtherwise 192.168.0.3 will be used  아니면 192.168.0.3으로 설정됩니다." --ok-button "OK/확인" --cancel-button "Cancel/나가기" --backtitle "Audio-config" 10 75 $(hostname -I) 3>&1 1>&2 2>&3)
    exitstatus=$?
    [ "$exitstatus" != 0 ] && exit
    if [ -z "$user_ip" ]; then
     ip_1st=$(echo "$(hostname -I)" | cut -d "." -f1)
     ip_2nd=$(echo "$(hostname -I)" | cut -d "." -f2)
     ip_3rd=$(echo "$(hostname -I)" | cut -d "." -f3)
     ip_4th=$(echo "$(hostname -I)" | cut -d "." -f4)
    else
     ip_1st=$(echo "$user_ip" | cut -d "." -f1)
     ip_2nd=$(echo "$user_ip" | cut -d "." -f2)
     ip_3rd=$(echo "$user_ip" | cut -d "." -f3)
     ip_4th=$(echo "$user_ip" | cut -d "." -f4)
    fi
    if [ "$ip_1st" -ge "1" ] 2>/dev/null && [ "$ip_1st" -le "254" ] 2>/dev/null && [ "$ip_1st" -ne "127" ] 2>/dev/null && [ "$ip_2nd" -ge "0" ] 2>/dev/null && [ "$ip_2nd" -le "255" ] 2>/dev/null && [ "$ip_3rd" -ge "0" ] 2>/dev/null && [ "$ip_3rd" -le "255" ] 2>/dev/null && [ "$ip_4th" -ge "2" ] 2>/dev/null && [ "$ip_4th" -le "254" ] 2>/dev/null ; then
     ip=$ip_1st.$ip_2nd.$ip_3rd
     ip_all=$ip_1st.$ip_2nd.$ip_3rd.$ip_4th
    else
     ip=192.168.0
     ip_all=192.168.0.3
    fi
    sudo sed -i '/iface eth0 inet manual/s/^/#/' /etc/network/interfaces
    sudo sed -i '/iface eth0 inet static/,$d'    /etc/network/interfaces
    sudo sed -i "\$aiface eth0 inet static\n address\t\t$ip_all\n netmask\t\t255.255.255.0\n broadcast\t\t$ip.255\n network\t\t$ip.0\n gateway\t\t$ip.1\n#dns-nameservers\t168.126.63.1" /etc/network/interfaces
    sudo systemctl disable dhcpcd.service
    echo "My assumption may be wrong, please edit with the following command.\n'sudo nano /etc/network/interfaces'\n제 추정은 틀릴 수 있으므로, 위 명령어로 직접 수정하시기 바랍니다.\n\n-----------------------\n/etc/network/interfaces\n-----------------------\n$(cat /etc/network/interfaces)" > ~/static_ip.txt
    whiptail --title "Static IP / 수동 IP" --scrolltext --textbox ~/static_ip.txt --ok-button "OK/확인" --backtitle "Audio-config" 18 75
    ;;
esac
main
}

main () {
i=$(whiptail --title "Audio Renderer Main / 오디오 렌더러 주메뉴" --menu "Choose/선택" --ok-button "OK/확인" --cancel-button "Cancel/나가기" --backtitle "Audio-config" 16 55 8 \
"1"  "Audio Device            오디오 장치" \
"2"  "USB Signal & Power      USB 신호와 전원" \
"3"  "IP address              IP 설정" \
"4"  "DBus/DoP/Music Folder   DBus/DoP/음원 폴더" \
"5"  "ALSA Reinstall          ALSA 재설치" \
"6"  "Raspbian Update         Raspbian 업데이트" \
"7"  "Reboot                  재시작" \
"8"  "Power off               전원 끄기" 3>&1 1>&2 2>&3)

case $i in
 1)  sound_card ;;
 2)  usb_signal_power ;;
 3)  static_ip ;;
 4)  
     i=$(whiptail --title "DBus/DoP/Music Folder / DBus/DoP/음원 폴더 설정" --checklist "Check/확인" --ok-button "OK/확인" --cancel-button "Cancel/나가기" --backtitle "Audio-config" 11 57 3 \
"D-Bus"  "Enable D-Bus         D-Bus 사용" OFF \
"DoP"    "Enable DoP           DoP 사용" OFF \
"Folder" "Enable Music Folder  음원 폴더 사용" ON 3>&1 1>&2 2>&3)

     if [ "$D-Bus" == ON ]; then
      sudo sed -i 's/dbus #/# dbus/g' /etc/rc.local
     else
      sudo sed -i 's/# dbus/dbus #/g' /etc/rc.local
     fi

     if [ "$DoP" == ON ]; then
      sudo sed -i '/dop/s/^#*//g' /etc/mpd.conf
     else
      sudo sed -i '/dop/s/^/#/g'  /etc/mpd.conf
     fi

     if [ "$Folder" == ON ]; then
      sudo sed -i '/^#music_directory\|^#db_file/s/^#//' /etc/mpd.conf
     else
      sudo sed -i '/^music_directory\|^db_file/s/^/#/g'   /etc/mpd.conf
     fi
     ;;
 5)  sudo cp /usr/share/alsa/alsa.conf /usr/share/alsa/alsa.conf.bak
     sudo apt-get install --reinstall libasound2 libasound2-data
     sudo cp /usr/share/alsa/alsa.conf.bak /usr/share/alsa/alsa.conf ;;
 6)  sudo apt-get update
     sudo apt-get upgrade
     sudo apt-get dist-upgrade ;;
 7)  sudo reboot ;;
 8)  sudo poweroff ;;
esac
}

main