#!/bin/bash

sound_card_initial () {
 sudo sed -i '/dtoverlay=allo\|dtoverlay=hifiberry\|dtoverlay=iqaudio/d' /boot/config.txt
}

sound_card_intaudio () {
 sudo sed -i '/card/s/[1-9]/0/g'  /usr/share/alsa/alsa.conf
}

sound_card_usbaudio () {
 sudo sed -i '/card/s/[02-9]/1/g' /usr/share/alsa/alsa.conf
}

iqaudio () {
 if (whiptail --title "Unmute IQaudIO / IQaudIO 음소거 제거" --yesno "   Unmute IQaudIO?   IQaudIO 음소거를 제거할까요?" --yes-button "Yes/예" --no-button "No/아니오" 8 56) then
  sudo sed -i '/\/sys\/class\/gpio/s/^#*//g' /etc/rc.local
 else
  sudo sed -i '/\/sys\/class\/gpio/s/^echo/#echo/g' /etc/rc.local
 fi
}

sound_card () {
i=$(whiptail --title "Audio device / 오디오 장치" --menu "Choose/선택" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 20 55 12 \
"1"  "USB Audio Class 2.0" \
"2"  "Allo Boss DAC" \
"3"  "Allo Boss DAC (Slave mode/종속 모드)" \
"4"  "Allo Piano DAC" \
"5"  "Allo Piano DAC+" \
"6"  "Allo Piano DAC+ (+Kali board)" \
"7"  "Allo DigiOne" \
"8"  "HiFiBerry Amp/Amp+" \
"9"  "HiFiBerry DAC" \
"10" "HiFiBerry DAC+/DAC+ Pro" \
"11" "HiFiBerry DAC+ Pro (Slave mode/종속 모드)" \
"12" "HiFiBerry Digi/Digi+" \
"13" "HiFiBerry Digi+ Pro" \
"14" "IQaudIO DAC" \
"15" "IQaudIO DAC+" \
"16" "IQaudIO Digi+" 3>&1 1>&2 2>&3)

case $i in
 1)  sound_card_initial
     #sound_card_usbaudio
     ;;
 2)  sound_card_initial
     sudo sed -i '$adtoverlay=allo-boss-dac-pcm512x-audio' /boot/config.txt
     #sound_card_intaudio
     ;;
 3)  sound_card_initial
     sudo sed -i '$adtoverlay=allo-boss-dac-pcm512x-audio,slave' /boot/config.txt
     #sound_card_intaudio
     ;;
 4)  sound_card_initial
     sudo sed -i '$adtoverlay=allo-piano-dac-pcm512x-audio' /boot/config.txt
     #sound_card_intaudio
     ;;
 5)  sound_card_initial
     sudo sed -i '$adtoverlay=allo-piano-dac-pcm512x-audio' /boot/config.txt
     #sound_card_intaudio
     ;;
 6)  sound_card_initial
     sudo sed -i '$adtoverlay=allo-piano-dac-pcm512x-audio,glb_mclk' /boot/config.txt
     #sound_card_intaudio
     ;;
 7)  sound_card_initial
     sudo sed -i '$adtoverlay=allo-digione' /boot/config.txt
     #sound_card_intaudio
     ;;
 8)  sound_card_initial
     sudo sed -i '$adtoverlay=hifiberry-amp' /boot/config.txt
     #sound_card_intaudio
     ;;
 9)  sound_card_initial
     sudo sed -i '$adtoverlay=hifiberry-dac' /boot/config.txt
     #sound_card_intaudio
     ;;
 10) sound_card_initial
     sudo sed -i '$adtoverlay=hifiberry-dacplus' /boot/config.txt
     #sound_card_intaudio
     ;;
 11) sound_card_initial
     sudo sed -i '$adtoverlay=hifiberry-dacplus,slave' /boot/config.txt
     #sound_card_intaudio
     ;;
 12) sound_card_initial
     sudo sed -i '$adtoverlay=hifiberry-digi' /boot/config.txt
     #sound_card_intaudio
     ;;
 13) sound_card_initial
     sudo sed -i '$adtoverlay=hifiberry-digi-pro' /boot/config.txt
     #sound_card_intaudio
     ;;
 14) sound_card_initial
     sudo sed -i '$adtoverlay=iqaudio-dac' /boot/config.txt
     #sound_card_intaudio
     iqaudio
     ;;
 15) sound_card_initial
     sudo sed -i '$adtoverlay=iqaudio-dacplus' /boot/config.txt
     #sound_card_intaudio
     iqaudio
     ;;
 16) sound_card_initial
     sudo sed -i '$adtoverlay=iqaudio-digi-wm8804-audio' /boot/config.txt
     #sound_card_intaudio
     iqaudio
     ;;
esac
}

usb_signal_power () {
i=$(whiptail --title "USB signal & power / USB 신호와 전원" --menu "\
Choose/선택
                [USB ] [USB4]
          [LAN] [USB3] [USB5]
         =====================(Back Port/뒷면)
         USB3 is recommended for DAC./DAC은 USB3을 추천합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 16 75 4 \
"1" "Enable  USB all signal & power      USB 모든 신호와 전원 켜기" \
"2" "Disable USB all signal & power      USB 모든 신호와 전원 끄기" \
"3" "Disable USB 4/5 signal              USB 4/5 신호만 끄기" \
"4" "Disable USB 4/5 signal & all power  USB 4/5 신호와 모든 전원 끄기" 3>&1 1>&2 2>&3)

case $i in
 1) sudo sed -i '/hub-ctrl -h 0 -P [2-5]/s/^/#/g'   /etc/rc.local ;;
 2) sudo sed -i '/hub-ctrl -h 0 -P [2-5]/s/^#*//g'  /etc/rc.local ;;
 3) sudo sed -i '/hub-ctrl -h 0 -P [4-5]/s/^#*//g'  /etc/rc.local
    sudo sed -i '/hub-ctrl -h 0 -P [2-3]/s/^/#/g'   /etc/rc.local ;;
 4) sudo sed -i '/hub-ctrl -h 0 -P [24-5]/s/^#*//g' /etc/rc.local
    sudo sed -i '/hub-ctrl -h 0 -P 3/s/^/#/g'       /etc/rc.local ;;
esac
}

static_ip () {
i=$(whiptail --title "IP address / IP 설정" --menu "Choose/선택" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 10 45 2 \
"1" "Dynamic IP (DHCP)   자동 IP" \
"2" "Static  IP          수동 IP  >" 3>&1 1>&2 2>&3)

case $i in
 1) sudo sed -i '/iface eth0 inet manual/s/^#*//' /etc/network/interfaces
    sudo sed -i '/iface eth0 inet static/,+6d'    /etc/network/interfaces
    cat /etc/network/interfaces
    sudo systemctl enable dhcpcd.service ;;
 2) user_ip=$(whiptail --title "Static IP / 수동 IP" --inputbox "\

Input Static IP address to use.       사용할 수동 IP를 입력합니다.
Current IP is listed below.           아래는 현재 주소입니다.
Otherwise, 192.168.0.9 will be used.  아니면 192.168.0.9로 설정합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 11 75 $(hostname -I) 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     if [ -z "$user_ip" ]; then
      ip_1st=$(echo "$(hostname -I)" | cut -d "." -f1)
      ip_2nd=$(echo "$(hostname -I)" | cut -d "." -f2)
      ip_3rd=$(echo "$(hostname -I)" | cut -d "." -f3)
      ip_4th=$(echo "$(hostname -I)" | cut -d "." -f4)
     else
      ip_1st=$(echo "$user_ip" | cut -d "." -f1)
      ip_2nd=$(echo "$user_ip" | cut -d "." -f2)
      ip_3rd=$(echo "$user_ip" | cut -d "." -f3)
      ip_4th=$(echo "$user_ip" | cut -d "." -f4)
     fi
     if [ "$ip_1st" -ge "1" ] 2>/dev/null && [ "$ip_1st" -le "254" ] 2>/dev/null && [ "$ip_1st" -ne "127" ] 2>/dev/null && [ "$ip_2nd" -ge "0" ] 2>/dev/null && [ "$ip_2nd" -le "255" ] 2>/dev/null && [ "$ip_3rd" -ge "0" ] 2>/dev/null && [ "$ip_3rd" -le "255" ] 2>/dev/null && [ "$ip_4th" -ge "2" ] 2>/dev/null && [ "$ip_4th" -le "254" ] 2>/dev/null ; then
      ip=$ip_1st.$ip_2nd.$ip_3rd
      ip_all=$ip_1st.$ip_2nd.$ip_3rd.$ip_4th
     else
      ip=192.168.0
      ip_all=192.168.0.9
     fi
     sudo sed -i '/iface eth0 inet manual/s/^/#/' /etc/network/interfaces
     sudo sed -i '/iface eth0 inet static/,$d'    /etc/network/interfaces
     sudo sed -i "\$aiface eth0 inet static\n address\t\t$ip_all\n netmask\t\t255.255.255.0\n broadcast\t\t$ip.255\n network\t\t$ip.0\n gateway\t\t$ip.1\n#dns-nameservers\t168.126.63.1" /etc/network/interfaces
     sudo systemctl disable dhcpcd.service
     echo "\
My assumption may be wrong, please edit with the following command.
'sudo nano /etc/network/interfaces'
제 추정은 틀릴 수 있으므로, 위 명령어로 직접 수정하시기 바랍니다.

-----------------------
/etc/network/interfaces
-----------------------

$(cat /etc/network/interfaces)" > ~/static_ip.txt
     whiptail --title "Static IP / 수동 IP" --scrolltext --textbox ~/static_ip.txt --ok-button "OK/확인" --backtitle "Audio-config" 18 75
    fi
    ;;
esac
}

dbus_dop_folder () {
i=$(whiptail --title "DBus, DoP, Music Folder / 음원 폴더" --checklist "Check/확인" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 11 58 3 \
"dbus"   "Enable DBus           DBus 사용" OFF \
"dop"    "Enable DoP            DoP 사용" OFF \
"folder" "Enable Music Folder   음원 폴더 사용" ON 3>&1 1>&2 2>&3)

exitstatus=$?
if [ "$exitstatus" = 0 ]; then
 [[ $i =~ dbus ]] && sudo sed -i 's/dbus #/# dbus/g' /etc/rc.local || sudo sed -i 's/# dbus/dbus #/g' /etc/rc.local
 [[ $i =~ dop ]] && sudo sed -i '/dop/s/^#*//g' /etc/mpd.conf || sudo sed -i '/dop/s/^/#/g' /etc/mpd.conf
 [[ $i =~ folder ]] && sudo sed -i '/^#music_directory\|^#db_file/s/^#//' /etc/mpd.conf || sudo sed -i '/^music_directory\|^db_file/s/^/#/g'   /etc/mpd.conf
fi
}

renderer_name () {
 current_name=$(grep ^#*friendlyname /etc/upmpdcli.conf | cut -d ' ' -f3)
 i=$(whiptail --title "Change renderer name / 렌더러 이름 바꾸기" --inputbox "\

Input renderer name to change.   바꿀 렌더러 이름을 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 9 67 $current_name 3>&1 1>&2 2>&3)
 [ "$i" != $current_name ] && [ "$i" != "" ] && sudo sed -i 's/^#*friendlyname.*/friendlyname = '"$i"'/' /etc/upmpdcli.conf
}

while true; do
 i=$(whiptail --title "Audio-config / 오디오 설정" --menu "Choose/선택" --ok-button "OK/확인" --cancel-button "Exit/나가기" --backtitle "Audio-config" 18 62 10 \
 "1"  "Audio device              오디오 장치           >" \
 "2"  "USB signal & power        USB 신호와 전원       >" \
 "3"  "IP address                IP 설정               >" \
 "4"  "DBus, DoP, Music Folder   DBus, DoP, 음원 폴더  >" \
 "5"  "Change renderer name      렌더러 이름 바꾸기    >" \
 "6"  "Disable SSH               SSH 사용 안 함" \
 "7"  "ALSA reinstall            ALSA 재설치" \
 "8"  "Raspbian update           Raspbian 업데이트" \
 "9"  "Reboot                    재시작" \
"10"  "Power off                 전원 끄기" 3>&1 1>&2 2>&3)

 exitstatus=$?
 [ "$exitstatus" != 0 ] && exit

 case $i in
  1)  sound_card ;;
  2)  usb_signal_power ;;
  3)  static_ip ;;
  4)  dbus_dop_folder ;;
  5)  renderer_name ;;
  6)  sudo touch /boot/.nossh ;;
  7)  sudo cp /usr/share/alsa/alsa.conf /usr/share/alsa/alsa.conf.bak
      sudo apt-get install --reinstall libasound2 libasound2-data
      sudo cp /usr/share/alsa/alsa.conf.bak /usr/share/alsa/alsa.conf ;;
  8)  sudo apt-get update
      sudo apt-get upgrade
      sudo apt-get dist-upgrade ;;
  9)  sudo reboot ;;
  10) sudo poweroff ;;
 esac
done
