#!/bin/bash

[ -e /etc/mpd.conf.sav ] && mpd_conf=/etc/mpd.conf.sav || mpd_conf=/etc/mpd.conf
[ -e /etc/upmpdcli.conf.sav ] && upmpdcli_conf=/etc/upmpdcli.conf.sav || upmpdcli_conf=/etc/upmpdcli.conf
spotifyd_conf=/home/pi/spotifyd.conf

sound_card_initial () {
 sudo sed -i '/dtoverlay=allo\|dtoverlay=applepi\|dtoverlay=dionaudio\|dtoverlay=hifiberry\|dtoverlay=iqaudio/d' /boot/config.txt
}

sound_card_selector () {
 sound_card_initial
 sudo sed -i '$adtoverlay='"$1"'' /boot/config.txt
}

sound_card_intaudio () {
 sudo sed -i 's/card=[1-9]/card=0/g'  /usr/share/alsa/alsa.conf
}

sound_card_usbaudio () {
 sudo sed -i 's/card=[02-9]/card=1/g' /usr/share/alsa/alsa.conf
}

iqaudio () {
 if (whiptail --title "Unmute IQaudIO / IQaudIO 음소거 제거" --yesno "   Unmute IQaudIO?   IQaudIO 음소거를 제거할까요?" --yes-button "Yes/예" --no-button "No/아니오" 8 56) then
  sudo sed -i '/\/sys\/class\/gpio/s/^#*//g' /etc/rc.local
 else
  sudo sed -i '/\/sys\/class\/gpio/s/^echo/#echo/g' /etc/rc.local
 fi
}

sound_card () {
i=$(whiptail --title "Audio device / 오디오 장치" --menu "Select/선택" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 20 55 12 \
"1"  "USB Audio Class 2.0" \
"2"  "Allo Boss DAC" \
"3"  "Allo Boss DAC (Slave mode/종속 모드)" \
"4"  "Allo Piano DAC" \
"5"  "Allo Piano DAC+" \
"6"  "Allo Piano DAC+ (+Kali board)" \
"7"  "Allo DigiOne" \
"8"  "Allo Katana DAC" \
"9"  "ApplePi DAC" \
"10" "Dion Audio LOCO DAC-AMP" \
"11" "Dion Audio LOCO-V2 DAC-AMP" \
"12" "HiFiBerry Amp/Amp+" \
"13" "HiFiBerry DAC" \
"14" "HiFiBerry DAC+/DAC+ Pro" \
"15" "HiFiBerry DAC+ Pro (Slave mode/종속 모드)" \
"16" "HiFiBerry Digi/Digi+" \
"17" "HiFiBerry Digi+ Pro" \
"18" "IQaudIO DAC" \
"19" "IQaudIO DAC+" \
"20" "IQaudIO Digi+" \
"21" "JustBoom DAC" \
"22" "JustBoom Digi" \
"23" "RPi DAC" 3>&1 1>&2 2>&3)

case $i in
 1)  sound_card_initial ;;
 2)  sound_card_selector allo-boss-dac-pcm512x-audio			;;
 3)  sound_card_selector allo-boss-dac-pcm512x-audio,slave		;;
 4)  sound_card_selector allo-piano-dac-pcm512x-audio			;;
 5)  sound_card_selector allo-piano-dac-plus-pcm512x-audio		;;
 6)  sound_card_selector allo-piano-dac-plus-pcm512x-audio,glb_mclk	;;
 7)  sound_card_selector allo-digione					;;
 8)  sound_card_selector allo-katana-dac-audio				;;
 9)  sound_card_selector applepi-dac					;;
 10) sound_card_selector dionaudio-loco					;;
 11) sound_card_selector dionaudio-loco-v2				;;
 12) sound_card_selector hifiberry-amp					;;
 13) sound_card_selector hifiberry-dac					;;
 14) sound_card_selector hifiberry-dacplus				;;
 15) sound_card_selector hifiberry-dacplus,slave			;;
 16) sound_card_selector hifiberry-digi					;;
 17) sound_card_selector hifiberry-digi-pro				;;
 18) sound_card_selector iqaudio-dac			; iqaudio	;;
 19) sound_card_selector iqaudio-dacplus		; iqaudio	;;
 20) sound_card_selector iqaudio-digi-wm8804-audio	; iqaudio	;;
 21) sound_card_selector justboom-dac					;;
 22) sound_card_selector justboom-digi					;;
 23) sound_card_selector rpi-dac					;;
esac
}

usb_signal_power () {
i=$(whiptail --title "USB signal & power / USB 신호와 전원" --menu "\
Select/선택
                [USB ] [USB4]
          [LAN] [USB3] [USB5]
         =====================(Back Port/뒷면)
         USB3 is recommended for DAC./DAC은 USB3을 추천합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 16 75 4 \
"1" "Enable  USB all signal & power      USB 모든 신호와 전원 켜기" \
"2" "Disable USB all signal & power      USB 모든 신호와 전원 끄기" \
"3" "Disable USB 4/5 signal              USB 4/5 신호만 끄기" \
"4" "Disable USB 4/5 signal & all power  USB 4/5 신호와 모든 전원 끄기" 3>&1 1>&2 2>&3)

case $i in
 1) sudo sed -i '/hub-ctrl -h 0 -P [2-5]/s/^/#/g'   /etc/rc.local ;;
 2) sudo sed -i '/hub-ctrl -h 0 -P [2-5]/s/^#*//g'  /etc/rc.local ;;
 3) sudo sed -i '/hub-ctrl -h 0 -P [4-5]/s/^#*//g'  /etc/rc.local
    sudo sed -i '/hub-ctrl -h 0 -P [2-3]/s/^/#/g'   /etc/rc.local ;;
 4) sudo sed -i '/hub-ctrl -h 0 -P [24-5]/s/^#*//g' /etc/rc.local
    sudo sed -i '/hub-ctrl -h 0 -P 3/s/^/#/g'       /etc/rc.local ;;
esac
}

static_ip () {
i=$(whiptail --title "IP address / IP 설정" --menu "Select/선택" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 10 45 2 \
"1" "Dynamic IP (DHCP)       자동 IP" \
"2" "Static  IP              수동 IP   >" 3>&1 1>&2 2>&3)

case $i in
 1) sudo sed -i '/iface eth0 inet manual/s/^#*//' /etc/network/interfaces
    sudo sed -i '/iface eth0 inet static/,+6d'    /etc/network/interfaces
    cat /etc/network/interfaces
    sudo systemctl enable dhcpcd.service ;;
 2) user_ip=$(whiptail --title "Static IP / 수동 IP" --inputbox "\

Input Static IP address to use.       사용할 수동 IP를 입력합니다.
Current IP is listed below.           아래는 현재 주소입니다.
Otherwise, 192.168.0.9 will be used.  아니면 192.168.0.9로 설정합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 11 75 $(hostname -I) 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     if [ -z "$user_ip" ]; then
      ip_1st=$(echo "$(hostname -I)" | cut -d "." -f1)
      ip_2nd=$(echo "$(hostname -I)" | cut -d "." -f2)
      ip_3rd=$(echo "$(hostname -I)" | cut -d "." -f3)
      ip_4th=$(echo "$(hostname -I)" | cut -d "." -f4)
     else
      ip_1st=$(echo "$user_ip" | cut -d "." -f1)
      ip_2nd=$(echo "$user_ip" | cut -d "." -f2)
      ip_3rd=$(echo "$user_ip" | cut -d "." -f3)
      ip_4th=$(echo "$user_ip" | cut -d "." -f4)
     fi
     if [ "$ip_1st" -ge "1" ] 2>/dev/null && [ "$ip_1st" -le "254" ] 2>/dev/null && [ "$ip_1st" -ne "127" ] 2>/dev/null && [ "$ip_2nd" -ge "0" ] 2>/dev/null && [ "$ip_2nd" -le "255" ] 2>/dev/null && [ "$ip_3rd" -ge "0" ] 2>/dev/null && [ "$ip_3rd" -le "255" ] 2>/dev/null && [ "$ip_4th" -ge "2" ] 2>/dev/null && [ "$ip_4th" -le "254" ] 2>/dev/null ; then
      ip=$ip_1st.$ip_2nd.$ip_3rd
      ip_all=$ip_1st.$ip_2nd.$ip_3rd.$ip_4th
     else
      ip=192.168.0
      ip_all=192.168.0.9
     fi
     sudo sed -i '/iface eth0 inet manual/s/^/#/' /etc/network/interfaces
     sudo sed -i '/iface eth0 inet static/,$d'    /etc/network/interfaces
     sudo sed -i "\$aiface eth0 inet static\n address\t\t$ip_all\n netmask\t\t255.255.255.0\n broadcast\t\t$ip.255\n network\t\t$ip.0\n gateway\t\t$ip.1\n#dns-nameservers\t168.126.63.1" /etc/network/interfaces
     sudo systemctl disable dhcpcd.service
     echo "\
My assumption may be wrong, please edit with the following command.
'sudo nano /etc/network/interfaces'
제 추정은 틀릴 수 있으므로, 위 명령어로 직접 수정하시기 바랍니다.

-----------------------
/etc/network/interfaces
-----------------------

$(cat /etc/network/interfaces)" > ~/static_ip.txt
     whiptail --title "Static IP / 수동 IP" --scrolltext --textbox ~/static_ip.txt --ok-button "OK/확인" --backtitle "Audio-config" 18 75
    fi
    ;;
esac
}

dbus_tts () {
i=$(whiptail --title "IP TTS, DBus / IP TTS와 DBus" --checklist "Check/확인" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 11 63 3 \
"tts"    "Enable booting IP TTS   부팅 시 IP TTS 사용" $(grep -q '^tts' /etc/rc.local && echo ON || echo OFF) \
"eng"    "Enable English IP TTS   영어 IP TTS 사용" $(grep -q '^tts en' /etc/rc.local && echo ON || echo OFF) \
"dbus"   "Enable DBus             DBus 사용" $(grep -q '# dbus' /etc/rc.local && echo OFF || echo ON) 3>&1 1>&2 2>&3)

exitstatus=$?
if [ "$exitstatus" = 0 ]; then
 [[ $i =~ dbus ]] && sudo sed -i 's/dbus #/# dbus/g' /etc/rc.local || sudo sed -i 's/# dbus/dbus #/g' /etc/rc.local
 [[ $i =~ tts  ]] && sudo sed -i '/tts/s/^#//' /etc/rc.local || sudo sed -i '/tts/s/^/#/' /etc/rc.local
 [[ $i =~ eng  ]] && sudo sed -i '/tts/s/.*/tts en My I P is $(hostname -I)/' $mpd_conf || sudo sed -i '/tts/s/.*/tts/' $mpd_conf
fi
}

renderer_name () {
 current_name=$(grep ^#*friendlyname $upmpdcli_conf | cut -d ' ' -f3)
 i=$(whiptail --title "Change renderer name / 렌더러 이름 바꾸기" --inputbox "\

Input renderer name to change.   바꿀 렌더러 이름을 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 9 67 $current_name 3>&1 1>&2 2>&3)
 [ "$i" != $current_name ] && [ "$i" != "" ] && sudo sed -i 's/^#*friendlyname.*/friendlyname = '"$i"'/' $upmpdcli_conf
}

mpd_settings () {
i=$(whiptail --title "MPD settings / MPD 설정" --checklist "Check/확인" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 11 64 3 \
"dop"      "Enable DoP (DSD over PCM)   DoP 사용" $(grep -q '^dop' $mpd_conf && echo ON || echo OFF) \
"folder"   "Enable Music Folder         음악 폴더 사용" $(grep -q '^music_directory' $mpd_conf && echo ON || echo OFF) \
"tag"      "Enable Metadata             태그 사용" $(grep -q '^metadata.*none' $mpd_conf && echo OFF || echo ON) 3>&1 1>&2 2>&3)

exitstatus=$?
if [ "$exitstatus" = 0 ]; then
 [[ $i =~ dop    ]] && sudo sed -i '/dop/s/^#*//g' $mpd_conf || sudo sed -i '/dop/s/^/#/g' $mpd_conf
 [[ $i =~ folder ]] && sudo sed -i '/^#music_directory\|^#db_file/s/^#//' $mpd_conf || sudo sed -i '/^music_directory\|^db_file/s/^/#/g' $mpd_conf
 [[ $i =~ tag    ]] && sudo sed -i '/metadata.*none/s/^/#/' $mpd_conf || sudo sed -i '/metadata.*none/s/^#*//' $mpd_conf
fi
}

spotify_qobuz_tidal () {
while true; do

i=$(whiptail --title "Spotify / Spotify 설정" --menu "\
Select/선택

     Remove any item to disable the function.
  한 항목이라도 지우면 그 기능을 사용하지 않습니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 13 60 2 \
"1"  "Spotify ┬ username     사용자        >" \
"2"  "        └ password     비밀번호      >" 3>&1 1>&2 2>&3)

exitstatus=$?
[ "$exitstatus" != 0 ] && return

case $i in
 1) spotify_user=$(grep username $spotifyd_conf | cut -d' ' -f3)
    input_user=$(whiptail --title "Spotify username / Spotify 사용자" --inputbox "\

Input Spotify username.   Spotify 사용자를 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 10 58 $spotify_user 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     if [ -n "$input_user" ]; then
      sudo sed -i '/username/s/=.*/= '"$input_user"'/' $spotifyd_conf
      sudo sed -i '/spotifyd &/s/^#*//' /etc/rc.local
     else
      sudo sed -i '/spotifyd &/s/^/#/' /etc/rc.local
     fi
    fi ;;
 2) spotify_pwd=$(grep password $spotifyd_conf | cut -d' ' -f3)
    input_pwd=$(whiptail --title "Spotify password / Spotify 비밀번호" --inputbox "\

Input Spotify password.   Spotify 비밀번호를 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 10 60 $spotify_pwd 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     if [ -n "$input_pwd" ]; then
      sudo sed -i '/password/s/=.*/= '"$input_pwd"'/' $spotifyd_conf
      sudo sed -i '/spotifyd &/s/^#*//' /etc/rc.local
     else
      sudo sed -i '/spotifyd &/s/^/#/' /etc/rc.local
     fi
    fi ;;
 3) qobuz_id=$(grep -A1 qobuz $mpd_conf | tail -1 | cut -d\" -f2)
    input_id=$(whiptail --title "Qobuz app_id / Qobuz 앱_id" --inputbox "\

Input Qobuz app_id.   Qobuz 앱_id를 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 10 51 $qobuz_id 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     if [ -n "$input_id" ]; then
      sudo sed -i '/"qobuz"/!b;n;s/".*"/"'"$input_id"'"/' $mpd_conf
      sudo sed -i '/"qobuz"/!b;n;n;n;n;n;n;s/no/yes/'     $mpd_conf
     else
      sudo sed -i '/"qobuz"/!b;n;s/".*"/""/'              $mpd_conf
      sudo sed -i '/"qobuz"/!b;n;n;n;n;n;n;s/yes/no/'     $mpd_conf
     fi
    fi ;;
 4) qobuz_sec=$(grep -A2 qobuz $mpd_conf | tail -1 | cut -d\" -f2)
    input_sec=$(whiptail --title "Qobuz app_secret / Qobuz 앱_secret" --inputbox "\

Input Qobuz app_secret.   Qobuz 앱_secret를 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 10 59 $qobuz_sec 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     if [ -n "$input_sec" ]; then
      sudo sed -i '/"qobuz"/!b;n;n;s/".*"/"'"$input_sec"'"/' $mpd_conf
      sudo sed -i '/"qobuz"/!b;n;n;n;n;n;n;s/no/yes/'        $mpd_conf
     else
      sudo sed -i '/"qobuz"/!b;n;n;s/".*"/""/'               $mpd_conf
      sudo sed -i '/"qobuz"/!b;n;n;n;n;n;n;s/yes/no/'        $mpd_conf
     fi
    fi ;;
 5) qobuz_user=$(grep -A3 qobuz $mpd_conf | tail -1 | cut -d\" -f2)
    input_user=$(whiptail --title "Qobuz app_username / Qobuz 사용자" --inputbox "\

Input Qobuz app_username.   Qobuz 사용자를 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 10 58 $qobuz_user 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     if [ -n "$input_user" ]; then
      sudo sed -i '/"qobuz"/!b;n;n;n;s/".*"/"'"$input_user"'"/' $mpd_conf
      sudo sed -i '/"qobuz"/!b;n;n;n;n;n;n;s/no/yes/'           $mpd_conf
     else
      sudo sed -i '/"qobuz"/!b;n;n;n;s/".*"/""/'                $mpd_conf
      sudo sed -i '/"qobuz"/!b;n;n;n;n;n;n;s/yes/no/'           $mpd_conf
     fi
    fi ;;
 6) qobuz_pwd=$(grep -A4 qobuz $mpd_conf | tail -1 | cut -d\" -f2)
    input_pwd=$(whiptail --title "Qobuz app_password / Qobuz 비밀번호" --inputbox "\

Input Qobuz app_password.   Qobuz 비밀번호를 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 10 60 $qobuz_pwd 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     if [ -n "$input_pwd" ]; then
      sudo sed -i '/"qobuz"/!b;n;n;n;n;s/".*"/"'"$input_pwd"'"/' $mpd_conf
      sudo sed -i '/"qobuz"/!b;n;n;n;n;n;n;s/no/yes/'            $mpd_conf
     else
      sudo sed -i '/"qobuz"/!b;n;n;n;n;s/".*"/""/'               $mpd_conf
      sudo sed -i '/"qobuz"/!b;n;n;n;n;n;n;s/yes/no/'            $mpd_conf
     fi
    fi ;;
 7) qobuz_fmt=$(grep format_id $mpd_conf | cut -d\" -f2)
    i=$(whiptail --title "Qobuz format_id / Qobuz 포맷" --radiolist "Select/선택" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 11 57 4 \
"5"    "MP3 320"                                 $([ "$qobuz_fmt" -eq 5 ]  && echo ON || echo OFF) \
"6"    "FLAC Lossless"                           $([ "$qobuz_fmt" -eq 6 ]  && echo ON || echo OFF) \
"7"    "FLAC Hi-Res 24 bit =< 96kHz"             $([ "$qobuz_fmt" -eq 7 ]  && echo ON || echo OFF) \
"27"   "FLAC Hi-Res 24 bit >96 kHz & =< 192 kHz" $([ "$qobuz_fmt" -eq 27 ] && echo ON || echo OFF) 3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     case $i in
      5)  sudo sed -i '/format_id/s/".*"/"5"/'  $mpd_conf ;;
      6)  sudo sed -i '/format_id/s/".*"/"6"/'  $mpd_conf ;;
      7)  sudo sed -i '/format_id/s/".*"/"7"/'  $mpd_conf ;;
      27) sudo sed -i '/format_id/s/".*"/"27"/' $mpd_conf ;;
     esac
    fi ;;
 8) tidal_token=$(grep -A1 tidal $mpd_conf | tail -1 | cut -d\" -f2)
    input_token=$(whiptail --title "Tidal token / Tidal 토큰" --inputbox "\

Input Tidal token.   Tidal 토큰을 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 10 49 $tidal_token 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     if [ -n "$input_token" ]; then
      sudo sed -i '/"tidal"/!b;n;s/".*"/"'"$input_token"'"/' $mpd_conf
      sudo sed -i '/"tidal"/!b;n;n;n;n;n;s/no/yes/'          $mpd_conf
     else
      sudo sed -i '/"tidal"/!b;n;s/".*"/""/'                 $mpd_conf
      sudo sed -i '/"tidal"/!b;n;n;n;n;n;s/yes/no/'          $mpd_conf
     fi
    fi ;;
 9) tidal_user=$(grep -A2 tidal $mpd_conf | tail -1 | cut -d\" -f2)
    input_user=$(whiptail --title "Tidal username / Tidal 사용자" --inputbox "\

Input Tidal username.   Tidal 사용자를 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 10 54 $tidal_user 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     if [ -n "$input_user" ]; then
      sudo sed -i '/"tidal"/!b;n;n;s/".*"/"'"$input_user"'"/' $mpd_conf
      sudo sed -i '/"tidal"/!b;n;n;n;n;n;s/no/yes/'           $mpd_conf
     else
      sudo sed -i '/"tidal"/!b;n;n;s/".*"/""/'                $mpd_conf
      sudo sed -i '/"tidal"/!b;n;n;n;n;n;s/yes/no/'           $mpd_conf
     fi
    fi ;;
 10) tidal_pwd=$(grep -A3 tidal $mpd_conf | tail -1 | cut -d\" -f2)
    input_pwd=$(whiptail --title "Tidal password / Tidal 비밀번호" --inputbox "\

Input Tidal password.   Tidal 비밀번호를 입력합니다." --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 10 56 $tidal_pwd 3>&1 1>&2 2>&3)
    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     if [ -n "$input_pwd" ]; then
      sudo sed -i '/"tidal"/!b;n;n;n;s/".*"/"'"$input_pwd"'"/' $mpd_conf
      sudo sed -i '/"tidal"/!b;n;n;n;n;n;s/no/yes/'            $mpd_conf
     else
      sudo sed -i '/"tidal"/!b;n;n;n;s/".*"/""/'               $mpd_conf
      sudo sed -i '/"tidal"/!b;n;n;n;n;n;s/yes/no/'            $mpd_conf
     fi
    fi ;;
 11) tidal_aq=$(grep audioquality $mpd_conf | cut -d\" -f2)
    i=$(whiptail --title "Tidal audioquality / Tidal 오디오 품질" --radiolist "Select/선택" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 11 46 4 \
"1"   "HI_RES"    $([ "$tidal_aq" = HI_RES ]   && echo ON || echo OFF) \
"2"   "LOSSELESS" $([ "$tidal_aq" = LOSELESS ] && echo ON || echo OFF) \
"3"   "HIGH"      $([ "$tidal_aq" = HIGH ]     && echo ON || echo OFF) \
"4"   "LOW"       $([ "$tidal_aq" = LOW ]      && echo ON || echo OFF) 3>&1 1>&2 2>&3)

    exitstatus=$?
    if [ "$exitstatus" = 0 ]; then
     case $i in
      1) sudo sed -i '/audioquality/s/".*"/"HI_RES"/'   $mpd_conf ;;
      2) sudo sed -i '/audioquality/s/".*"/"LOSELESS"/' $mpd_conf ;;
      3) sudo sed -i '/audioquality/s/".*"/"HIGH"/'     $mpd_conf ;;
      4) sudo sed -i '/audioquality/s/".*"/"LOW"/'      $mpd_conf ;;
     esac
    fi ;;
esac

done
}

read_only () {
i=$(whiptail --title "MicroSD Read-only / MicroSD 읽기 전용" --menu "Choose/선택" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 10 72 2 \
"1" "MicroSD Read-only                 MicroSD 읽기 전용" \
"2" "MicroSD Read-Write (Default)      MicroSD 읽고 쓰기 (기본값)" 3>&1 1>&2 2>&3)

case $i in
 1) sudo sed -i '/remountro/s/^#*//' /etc/rc.local ;;
 2) sudo sed -i '/remountro/s/^/#/'  /etc/rc.local ;;
esac
}

roon_bridge () {
i=$(whiptail --title "Roon Bridge / 룬 브리지" --checklist "Check/확인" --ok-button "OK/확인" --cancel-button "Cancel/취소" --backtitle "Audio-config" 9 55 1 \
"roon"   "Enable Roon Bridge   룬 브리지 사용" $(grep -q '^(roon_bridge' /etc/rc.local && echo ON || echo OFF) 3>&1 1>&2 2>&3)

exitstatus=$?
if [ "$exitstatus" = 0 ]; then
 if [[ $i =~ roon ]]; then
  sudo sed -i '/(roon_bridge/s/^#*//' /etc/rc.local
 else
  sudo sed -i '/(roon_bridge/s/^/#/' /etc/rc.local
 fi
fi
}

while true; do
 i=$(whiptail --title "Audio-config / 오디오 설정" --menu "Choose/선택" --ok-button "OK/확인" --cancel-button "Exit/나가기" --backtitle "Audio-config" 20 61 12 \
 "1"  "Audio device           오디오 장치            >" \
 "2"  "USB signal & power     USB 신호와 전원        >" \
 "3"  "MPD settings           MPD 설정               >" \
 "4"  "Renderer name          렌더러 이름 바꾸기     >" \
 "5"  "IP address             IP 설정                >" \
 "6"  "IP TTS, DBus           IP TTS와 DBus          >" \
 "7"  "Roon Bridge            룬 브리지              >" \
 "8"  "Spotify                Spotify 설정           >" \
 "9"  "SSH turn-off           SSH 사용 안 함" \
"10"  "Raspbian update        Raspbian 업데이트" \
"11"  "Reboot                 재시작" \
"12"  "Power off              전원 끄기" 3>&1 1>&2 2>&3)

 exitstatus=$?
 [ "$exitstatus" != 0 ] && exit

 case $i in
  1)  sound_card ;;
  2)  usb_signal_power ;;
  3)  mpd_settings ;;
  4)  renderer_name ;;
  5)  static_ip ;;
  6)  dbus_tts ;;
  7)  roon_bridge ;;
  8)  spotify_qobuz_tidal ;;
  9)  sudo touch /boot/.nossh ;;
  10) sudo apt-get update
      sudo apt-get upgrade
      sudo apt-get dist-upgrade ;;
  11) sudo reboot ;;
  12) sudo poweroff ;;
 esac
done
