#!/bin/sh
#complete -W '1fm 2fm 1r 2r 3r dmb scr rki cbs tbs tbse gugak stop' kr2mpd ./kr2mpd \~/kr2mpd

usage () {
 echo "Usage: $(basename "$0") 1fm|2fm|1r|2r|3r|dmb|scr|rki(KBS라디오)"
 echo "   or: $(basename "$0") cbs(CBS음악FM)|tbs(tbsFM)|tbse(tbseFM)|gugak(국악방송)"
 echo "   or: $(basename "$0") stop(정지)"
 echo "Play Korean radio with MPD"
}

kbsr () {
 url=$(curl -s "http://kong.kbs.co.kr/live_player/channelMini.php?id=kbsid&channel=$1" | tail -1)
}

case $1 in
 1fm)   kbsr 1 ;;
 2fm)   kbsr 2 ;;
 1r)    kbsr 3 ;;
 2r)    kbsr 4 ;;
 3r)    kbsr 5 ;;
 dmb)   kbsr 6 ;;
 scr)   kbsr 7 ;;
 rki)   kbsr 8 ;;
 cbs)   url="http://aac.cbs.co.kr/cbs939/_definst_/cbs939.stream/playlist.m3u8" ;;
 tbs)   url="http://tbs.hscdn.com/tbsradio/fm/playlist.m3u8" ;;
 tbse)  url="http://tbs.hscdn.com/tbsradio/efm/playlist.m3u8" ;;
 gugak) url="http://mgugaklive.nowcdn.co.kr/gugakradio/gugakradio.stream/playlist.m3u8" ;;
 stop)  mpc stop ; mpc del $(mpc playlist | wc -l) ; exit ;;
 *)     usage ; exit ;;
esac

mpc add $url && mpc play $(mpc playlist | wc -l)
