#!/bin/sh
#complete -W '1fm 2fm 1r 2r 3r dmb scr rki mbcm mbc4u mbcfm sbsp sbsl cbs tbs tbse gugak stop' kr2mpd ./kr2mpd \~/kr2mpd

usage () {
 echo "Usage: $(basename "$0") 1fm|2fm|1r|2r|3r|dmb|scr|rki(KBS라디오)"
 echo "   or: $(basename "$0") mbcm(MBC Channel M)|mbc4u(MBC FM4U)|mbcfm(MBC FM)"
 echo "   or: $(basename "$0") sbsp(SBS파워FM)|sbsl(SBS러브FM)"
 echo "   or: $(basename "$0") cbs(CBS음악FM)|tbs(tbsFM)|tbse(tbseFM)|gugak(국악방송)"
 echo "   or: $(basename "$0") stop(정지)"
 echo "Play Korean radio with MPD"
}

pls () {
 url=$(echo "$1" | grep -o '.*/')$(curl -s "$1" | tail -1)
}

kbsr () {
#url=$(curl -s "http://kong.kbs.co.kr/live_player/channelMini.php?id=kbsid&channel=$1" | tail -1)
#url=$(curl -s http://cfpwwwapi.kbs.co.kr/api/v1/landing/live/$1 | cut -d\" -f16 | cut -d\/ -f-6)/$(curl -s $(curl -s http://cfpwwwapi.kbs.co.kr/api/v1/landing/live/$1 | cut -d\" -f16) | tail -1)
#api=$(curl -s http://cfpwwwapi.kbs.co.kr/api/v1/landing/live/$1 | cut -d\" -f16)
#url=$(echo "$api" | cut -d\/ -f-6)/$(curl -s "$api" | tail -1)
 pls $(curl -s http://cfpwwwapi.kbs.co.kr/api/v1/landing/live/$1 | cut -d\" -f16)
}

mbcr () {
#url=$(curl -s "http://miniplay.imbc.com/WebLiveURL.ashx?channel=$1&agent=android&protocol=M3U8&nocash=" | sed -n '3p' | cut -d\" -f2)
#api=$(curl -s "http://miniplay.imbc.com/WebLiveURL.ashx?channel=$1&agent=android&protocol=M3U8&nocash=" | sed -n '3p' | cut -d\" -f2)
#url=$(echo "$api" | cut -d\/ -f-6)/$(curl -s "$api" | tail -1)
 pls $(curl -s "http://miniplay.imbc.com/WebLiveURL.ashx?channel=$1&agent=android&protocol=M3U8&nocash=" | sed -n '3p' | cut -d\" -f2)
}

sbsr () {
 api=$(curl -s "http://apis.sbs.co.kr/play-api/1.0/onair/channel/S$1?v_type=2&platform=pcweb&protocol=hls" | sed 's/.*mediaurl":"//; s/".*//')
 url=$(curl -s "$api" | tail -1)
}

case $1 in
 1fm)   #kbsr 1
        kbsr 24
	#url="http://112.175.138.137:1935/$1/$1.stream/playlist.m3u8"
	#echo $url ; exit
	;;
 2fm)   #kbsr 2
	kbsr 25
	#url="http://112.175.138.137:1935/$1/$1.stream/playlist.m3u8"
	;;
 1r)    #kbsr 3
	kbsr 21
	#url="http://112.175.138.137:1935/${1}adio/${1}adio.stream/playlist.m3u8"
	;;
 2r)    #kbsr 4
	kbsr 22
	#url="http://112.175.138.137:1935/${1}adio/${1}adio.stream/playlist.m3u8"
	;;
 3r)    #kbsr 5
	kbsr 23
	;;
 dmb)   #kbsr 6
	kbsr dmb
	#url="http://112.175.138.137:1935/$1/$1.stream/playlist.m3u8"
	;;
 scr)   #kbsr 7
	kbsr I26
	;;
 rki)   #kbsr 8
	kbsr I92
	;;
 mbcm)  mbcr chm
	;;
 mbc4u) mbcr mfm ;;
 mbcfm) mbcr sfm ;;
 sbsp)  sbsr 07  ;;
 sbsl)  sbsr 08  ;;
 cbs)   #url="http://aac.cbs.co.kr/cbs939/cbs939.stream/playlist.m3u8"
	pls "http://aac.cbs.co.kr/cbs939/cbs939.stream/playlist.m3u8"
	;;
 tbs)   #url="http://tbs.hscdn.com/tbsradio/fm/playlist.m3u8"
        pls "http://tbs.hscdn.com/tbsradio/fm/playlist.m3u8"
	;;
 tbse)  #url="http://tbs.hscdn.com/tbsradio/efm/playlist.m3u8"
	pls "http://tbs.hscdn.com/tbsradio/efm/playlist.m3u8"
	;;
 gugak) #url="http://mgugaklive.nowcdn.co.kr/gugakradio/gugakradio.stream/playlist.m3u8"
	pls "http://mgugaklive.nowcdn.co.kr/gugakradio/gugakradio.stream/playlist.m3u8"
	;;
 stop)  mpc stop ; mpc del $(mpc playlist | wc -l) ; exit ;;
 *)     usage ; exit ;;
esac

mpc add $url && mpc play $(mpc playlist | wc -l)
