#!/bin/sh

  kbs1="http://juoradio.appspot.com/kbs1"
  kbs2="http://juoradio.appspot.com/kbs2"
 kbs1r="http://juoradio.appspot.com/kbs1r"
 kbs2r="http://juoradio.appspot.com/kbs2r"
 kbs3r="http://juoradio.appspot.com/kbs3r"
kbsscr="http://juoradio.appspot.com/kbsscr"
kbsrki="http://juoradio.appspot.com/kbsrki"
 cbsfm="rtmp://aac.cbs.co.kr/cbs939/_definst_/cbs939.stream"

usage () {
 echo "$(basename "$0"): missing option"
 echo "Usage: $(basename "$0") [kbs1/2|kbs1/2/3r|kbsscr|kbsrki|cbsfm|stop]"
}

[ -z "$1" ] && usage && exit

case $1 in
 kbs1|kbs2|kbs1r|kbs2r|kbs3r|kbsscr|kbsrki|cbsfm)
  http_proxy=""
  sudo sleep 0.1
  /usr/bin/mplayer -novideo $(eval echo \"\$"$1"\") >/dev/null 2>&1 & ;;
 stop) pkill mplayer ; exit ;;
 *)    usage         ; exit ;;
esac

until [ $(pgrep mplayer | wc -l) -ge 2 ]; do
 sleep 1
done

opg_mplayer=$(pgrep -o mplayer)
npg_mplayer=$(pgrep -n mplayer)

taskset -pc 1     $opg_mplayer
taskset -pc 3     $npg_mplayer
sudo renice -1 -p $opg_mplayer
sudo renice -2 -p $npg_mplayer
