#!/bin/sh
#complete -W 'kbs1 kbs2 kbs1r kbs2r kbs3r kbsscr kbsrki cbsfm' ./kradio \~/kradio

  kbs1="http://juoradio.appspot.com/kbs1"
  kbs2="http://juoradio.appspot.com/kbs2"
 kbs1r="http://juoradio.appspot.com/kbs1r"
 kbs2r="http://juoradio.appspot.com/kbs2r"
 kbs3r="http://juoradio.appspot.com/kbs3r"
kbsscr="http://juoradio.appspot.com/kbsscr"
kbsrki="http://juoradio.appspot.com/kbsrki"
 cbsfm="rtmp://aac.cbs.co.kr/cbs939/_definst_/cbs939.stream"

usage () {
 echo "$(basename "$0"): missing option"
 echo "Usage: $(basename "$0") [kbs1/2|kbs1/2/3r|kbsscr|kbsrki|cbsfm|stop]"
}

[ -z "$1" ] && usage && exit

case $1 in
 kbs1|kbs2|kbs1r|kbs2r|kbs3r|kbsscr|kbsrki|cbsfm)
  http_proxy=""
  sudo sleep 0.1
  pkill mplayer
  [ ! -e /usr/lib/arm-linux-gnueabihf/libasound.so.2 ] && [ -e /usr/lib/arm-linux-gnueabihf/libasound.so.2.sav ] && mv /usr/lib/arm-linux-gnueabihf/libasound.so.2.sav /usr/lib/arm-linux-gnueabihf/libasound.so.2
  /usr/bin/mplayer -novideo $(eval echo \"\$"$1"\") >/dev/null 2>&1 & ;;
 stop) pkill mplayer ; exit ;;
 *)    usage         ; exit ;;
esac

until [ $(pgrep -x mplayer | wc -l) -ge 2 ]; do
 sleep 1
done

opg_mplayer=$(pgrep -ox mplayer)
npg_mplayer=$(pgrep -nx mplayer)

if   [ "$(nproc --all)" -ge "4" ]; then
 taskset -cp 1 $opg_mplayer
 taskset -cp 3 $npg_mplayer
elif [ "$(nproc --all)" -eq "2" ]; then
 taskset -cp 1 $opg_mplayer
 taskset -cp 1 $npg_mplayer
fi

      renice +1 -p $opg_mplayer
 sudo renice -1 -p $npg_mplayer

[ -e /usr/lib/arm-linux-gnueabihf/libasound.so.2 ] && mv /usr/lib/arm-linux-gnueabihf/libasound.so.2 /usr/lib/arm-linux-gnueabihf/libasound.so.2.sav