#!/bin/sh

if [ $(pgrep -x mpd) -gt 0 ] 2>/dev/null; then
 sudo killall mpd
fi

until [ $(pgrep -x mpd) -gt 0 ] 2>/dev/null && $(pstree -np $(pgrep -x mpd) 2>/dev/null | grep -q output); do
 sleep 1
done

sleep 1

m_task=$(($(nproc --all)-1))
[ "$m_task" -ge 3 ] && s_task=$((m_task-2)) || s_task=0

pgr_mpd=$(pgrep -x mpd)

 sudo taskset -pc $m_task $pgr_mpd
#sudo renice -1 -p $pgr_mpd

echo "$(pstree -np $pgr_mpd)" | while read line ; do
 proc=$(echo "$line" | cut -d "{" -f2 | cut -d "}" -f1 | cut -d ":" -f1) # proc=$(echo "$line" | awk -F '[{,:,}]' '{ print $2 }')
 proc_nr=$(echo "$line" | cut -d "}" -f2 | cut -d "(" -f2 | cut -d ")" -f1) # proc_nr=$(echo "$line" | awk -F '[(,)]' '{ print $(NF-1) }')
 case $proc in
  mpd)		 sudo taskset -cp $s_task $proc_nr ;;
  io)		 sudo taskset -cp $s_task $proc_nr ;;
  player)	 sudo taskset -cp $s_task $proc_nr ;;
  decoder)	 sudo taskset -cp $s_task $proc_nr ;;
  output)	 sudo taskset -cp $m_task $proc_nr
		#sudo renice -2 -p	  $proc_nr
		 sudo chrt -opv 0	  $proc_nr ;;
 esac
done

nohup taskset -ac $s_task /usr/bin/upmpdcli -c /etc/upmpdcli.conf &

[ -e /usr/lib/arm-linux-gnueabihf/libasound.so.2 ] && sudo mv /usr/lib/arm-linux-gnueabihf/libasound.so.2 /usr/lib/arm-linux-gnueabihf/libasound.so.2.sav

sudo sh -c "echo none > /sys/class/leds/led0/trigger"
sudo sh -c "echo 0    > /sys/class/leds/led0/brightness"
[ -f /sys/class/leds/led1/brightness ] && sudo sh -c "echo 0 > /sys/class/leds/led1/brightness"
sudo /home/pi/llctl f0 l0 d0
