#!/bin/bash

countdown_clear () {
 echo
 echo "Back to Main after 3 seconds / 3초후에 주메뉴로 갑니다."
 for i in 3 2 1; do
  echo -n "$i"
  sleep 0.5
  echo -n "."
  sleep 0.5
 done
 clear
}

sound_card_intial () {
 sudo sed -i '/dtoverlay=hifiberry\|dtoverlay=iqaudio/d' /boot/config.txt
}

sound_card_intaudio () {
 sudo sed -i '/card/s/[1-9]/0/g'  /usr/share/alsa/alsa.conf | grep card
}

sound_card_usbaudio () {
 sudo sed -i '/card/s/[02-9]/1/g' /usr/share/alsa/alsa.conf | grep card
}

sound_card () {
clear
echo -n "
 ------------------------------
  Sound Card / 사운드카드 설정
 ------------------------------

(1) USB Audio Class 2.0 (Default / 기본값)
(2) HiFiBerry Amp+
(3) HiFiBerry DAC
(4) HiFiBerry DAC+
(5) HiFiBerry Digi
(6) HiFiBerry Digi+
(7) IQaudIO DAC
(8) IQaudIO DAC+
(9) IQaudIO Digi+
(u) Unmute IQaudIO (IQaudIO 음소거 제거)
(t) Mute   IQaudIO (IQaudIO 음소거 제거 취소)

(m) Main/주메뉴
(q) Quit/나가기

  * Choose/선택 (1-9,u,t,m,q) : "
read i
echo
case $i in
 1) sound_card_initial
    sound_card_usbaudio ;;
 2) sound_card_initial
    sudo sed -i '$adtoverlay=hifiberry-amp'             /boot/config.txt | grep dtoverlay
    sound_card_intaudio ;;
 3) sound_card_initial
    sudo sed -i '$adtoverlay=hifiberry-dac'             /boot/config.txt | grep dtoverlay
    sound_card_intaudio ;;
 4) sound_card_initial
    sudo sed -i '$adtoverlay=hifiberry-dacplus'         /boot/config.txt | grep dtoverlay
    sound_card_intaudio ;;
 5) sound_card_initial
    sudo sed -i '$adtoverlay=hifiberry-digi'            /boot/config.txt | grep dtoverlay
    sound_card_intaudiof ;;
 6) sound_card_initial
    sudo sed -i '$adtoverlay=hifiberry-digi-pro'        /boot/config.txt | grep dtoverlay
    sound_card_intaudio ;;
 7) sound_card_initial
    sudo sed -i '$adtoverlay=iqaudio-dac'               /boot/config.txt | grep dtoverlay
    sound_card_intaudio ;;
 8) sound_card_initial
    sudo sed -i '$adtoverlay=iqaudio-dacplus'           /boot/config.txt | grep dtoverlay
    sound_card_intaudio ;;
 9) sound_card_initial
    sudo sed -i '$adtoverlay=iqaudio-digi-wm8804-audio' /boot/config.txt | grep dtoverlay
    sound_card_intaudio ;;
 u) sudo sed -i '/exit 0/iecho "22" > /sys/class/gpio/export\necho "out" > /sys/class/gpio/gpio22/direction\necho "1" > /sys/class/gpio/gpio22/value\n' /etc/rc.local ;;
 t) sudo sed -i '/\/sys\/class\/gpio/d' /etc/rc.local ;;
 m) clear ; return ;;
 q) exit ;;
esac
countdown_clear
return
}

usb_signal_power () {
clear
echo -n "
 --------------------------------------
  USB Signal & Power / USB 신호와 전원
 --------------------------------------

        {USB } {USB4}
  {LAN} {USB3} {USB5}
 =====================[Back Port / 뒷면]
     USB3 is recommended for DAC / DAC은 USB3을 추천합니다

(1) Enable  All USB Signal & Power  (1) 모든 USB 신호와 전원 켜기 (기본값)
(2) Disable All USB Signal & Power  (2) 모든 USB 신호와 전원 끄기 (I2S DAC)
(3) Disable USB 4/5 Signal          (3) USB 4/5 신호만 끄기
(4) Disable USB 4/5 Signal & Power  (4) USB 4/5 신호와 전원 끄기
   (Powered USB DDC/DAC)               (자체 전원 USB DDC/DAC)

(m) Main                            (m) 주메뉴
(q) Quit                            (q) 나가기

  * Choose/선택 (1-4,m,q) : "
read i
echo
case $i in
 1) sudo sed -i '/hub-ctrl/s/^/#/g'                /etc/rc.local | grep hub-ctrl ;;
 2) sudo sed -i '/hub-ctrl -h 0 -P [2-5]/s/#*//g'  /etc/rc.local | grep hub-ctrl ;;
 3) sudo sed -i '/hub-ctrl -h 0 -P [4-5]/s/#*//g'  /etc/rc.local | grep hub-ctrl ;;
 4) sudo sed -i '/hub-ctrl -h 0 -P [24-5]/s/#*//g' /etc/rc.local | grep hub-ctrl ;;
 m) clear ; return ;;
 q) exit ;;
esac
countdown_clear
return
}

static_ip () {
clear
echo -n "
 ---------------------
  Static IP / 수동 IP
 ---------------------

(1) Dynamic IP (DHCP, Default)  (1) 자동 IP (DHCP, 기본값)
(2) Static  IP                  (2) 수동 IP

(m) Main                        (m) 주메뉴
(q) Quit                        (q) 나가기

  * Choose/선택 (1-2,m,q) : "
read i
echo
case $i in
 1) sudo sed -i '/iface eth0/s/static/dhcp/' /etc/network/interfaces
    sudo sed -i '/iface eth0/,+6d'           /etc/network/interfaces
    cat /etc/network/interfaces ;;
 2) echo -ne "Input Static IP address to use      사용할 수동 IP를 입력합니다.\nEnter will use the current IP       엔터를 누르면 현재 주소를 사용합니다.\nCurrent IP [ $(hostname -I)]         현재 주소 [ $(hostname -I)]\nOtherwise 192.168.0.3 will be used  잘못된 IP는 192.168.0.3으로 설정됩니다.\n:"
    read user_ip
    if [ -z "$user_ip" ]; then
     ip_1st=$(echo "$(hostname -I)" | cut -d "." -f1)
     ip_2nd=$(echo "$(hostname -I)" | cut -d "." -f2)
     ip_3rd=$(echo "$(hostname -I)" | cut -d "." -f3)
     ip_4th=$(echo "$(hostname -I)" | cut -d "." -f4)
    else
     ip_1st=$(echo "$user_ip" | cut -d "." -f1)
     ip_2nd=$(echo "$user_ip" | cut -d "." -f2)
     ip_3rd=$(echo "$user_ip" | cut -d "." -f3)
     ip_4th=$(echo "$user_ip" | cut -d "." -f4)
    fi
    if [ "$ip_1st" -ge "1" ] 2>/dev/null && [ "$ip_1st" -le "254" ] 2>/dev/null && [ "$ip_1st" -ne "127" ] 2>/dev/null && [ "$ip_2nd" -ge "0" ] 2>/dev/null && [ "$ip_2nd" -le "255" ] 2>/dev/null && [ "$ip_3rd" -ge "0" ] 2>/dev/null && [ "$ip_3rd" -le "255" ] 2>/dev/null && [ "$ip_4th" -ge "2" ] 2>/dev/null && [ "$ip_4th" -le "254" ] 2>/dev/null ; then
     ip=$ip_1st.$ip_2nd.$ip_3rd
     ip_all=$ip_1st.$ip_2nd.$ip_3rd.$ip_4th
    else
     ip=192.168.0
     ip_all=192.168.0.3
    fi
    sudo sed -i '/iface eth0/s/dhcp/static/' /etc/network/interfaces
    sudo sed -i "/iface eth0/aaddress\t\t$ip_all\n netmask\t\t255.255.255.0\n broadcast\t\t$ip.255\n network\t\t$ip.0\n gateway\t\t$ip.1\n#dns-nameservers\t168.126.63.1" /etc/network/interfaces
    echo
    echo -e "[!] My assumption might be wrong,\nplease edit with 'sudo nano /etc/network/interfaces'"
    echo -e "[!] 제 추정은 틀릴 수 있으므로, 아래 명령어로 직접 수정하시기 바랍니다.\n'sudo nano /etc/network/interfaces'" ;;
 m) clear ; return ;;
 q) exit ;;
esac
countdown_clear
return
}

clear
until [ "$i" == "q" ] ; do
 echo -n "
 --------------------------------------------
  Audio Renderer Main / 오디오 렌더러 주메뉴
 --------------------------------------------

(1) Sound Card...             (1) 사운드카드 설정...
(2) USB Signal & Power...     (2) USB 신호와 전원...
(3) Static IP...              (3) 수동 IP...
(4) Disable D-Bus             (4) D-Bus 사용 (Plug & Play)
(5) Enable  D-Bus             (5) D-Bus 사용 안 함
(6) Enable  DoP               (6) DoP 사용 (DSD over PCM)
(7) Disable DoP               (7) DoP 사용 안 함
(8) Disable MPD Folders       (8) MPD 폴더 사용
(9) Enable  MPD Folders       (9) MPD 폴더 사용 안 함 (UPnP나 Stream만 사용)
(0) Resolve ALSA Tweak Issue  (0) ALSA 트윅 오류 수정 (Library 재설치)
(u) Update Raspbian OS        (u) Raspbian OS 업데이트

(q) Quit                      (q) 나가기
(r) Reboot to take effect     (r) 재시작하여 적용
(p) Power off                 (p) 전원 끄기

  * Choose/선택 (0-9,u,q,r,p) : "
 read i
 echo
 case $i in
  1) sound_card ;;
  2) usb_signal_power ;;
  3) static_ip ;;
  4) sudo sed -i 's/# dbus/dbus #/g' /etc/rc.local | grep dbus
     countdown_clear ;;
  5) sudo sed -i 's/dbus #/# dbus/g' /etc/rc.local | grep dbus
     countdown_clear ;;
  6) sudo sed -i '/dop/s/^/#/g'  /etc/mpd.conf | grep dop
     countdown_clear ;;
  7) sudo sed -i '/dop/s/^#*//g' /etc/mpd.conf | grep dop
     countdown_clear ;;
  8) sudo sed -i '/^music_directory\|^playlist_directory\|^db_file/s/^/#/g'   /etc/mpd.conf
     grep -e ^#*music_directory -e ^#*playlist_directory -e ^#*db_file /etc/mpd.conf
     countdown_clear ;;
  9) sudo sed -i '/^#music_directory\|^#playlist_directory\|^#db_file/s/^#//' /etc/mpd.conf
     grep -e ^#*music_directory -e ^#*playlist_directory -e ^#*db_file /etc/mpd.conf
     countdown_clear ;;
  0) sudo cp /usr/share/alsa/alsa.conf /usr/share/alsa/alsa.conf.bak
     sudo apt-get install --reinstall libasound2 libasound2-data
     sudo cp /usr/share/alsa/alsa.conf.bak /usr/share/alsa/alsa.conf
     countdown_clear ;;
  u) sudo apt-get update
     sudo apt-get upgrade
     sudo apt-get dist-upgrade
     countdown_clear ;;
  q) exit ;;
  r) sudo reboot ;;
  p) sudo poweroff ;;
 esac
done