#!/bin/sh
sudo chmod -R -w /lib/modules/*/kernel/sound/
sudo sed -i 's/9995%/9992799689968994%/' /etc/mpd.conf.sav
sudo sed -i '/wakeup_granularity_ns/s/= .*/= 388306/; /sched_latency_ns/s/= .*/= 1394017/' /etc/sysctl.conf